package com.yfny.corepojo.entity.demandform.model;

public class Jsgn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_JSGN.INFOID
     *
     * @mbggenerated
     */
    private String infoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_JSGN.JSBS
     *
     * @mbggenerated
     */
    private String jsbs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_JSGN.GNBS
     *
     * @mbggenerated
     */
    private String gnbs;

    public Jsgn(String infoid, String jsbs, String gnbs) {
        this.infoid = infoid;
        this.jsbs = jsbs;
        this.gnbs = gnbs;
    }

    public Jsgn() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_JSGN.INFOID
     *
     * @return the value of NWIDP.IMP_XQD_JSGN.INFOID
     *
     * @mbggenerated
     */
    public String getInfoid() {
        return infoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_JSGN.INFOID
     *
     * @param infoid the value for NWIDP.IMP_XQD_JSGN.INFOID
     *
     * @mbggenerated
     */
    public void setInfoid(String infoid) {
        this.infoid = infoid == null ? null : infoid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_JSGN.JSBS
     *
     * @return the value of NWIDP.IMP_XQD_JSGN.JSBS
     *
     * @mbggenerated
     */
    public String getJsbs() {
        return jsbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_JSGN.JSBS
     *
     * @param jsbs the value for NWIDP.IMP_XQD_JSGN.JSBS
     *
     * @mbggenerated
     */
    public void setJsbs(String jsbs) {
        this.jsbs = jsbs == null ? null : jsbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_JSGN.GNBS
     *
     * @return the value of NWIDP.IMP_XQD_JSGN.GNBS
     *
     * @mbggenerated
     */
    public String getGnbs() {
        return gnbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_JSGN.GNBS
     *
     * @param gnbs the value for NWIDP.IMP_XQD_JSGN.GNBS
     *
     * @mbggenerated
     */
    public void setGnbs(String gnbs) {
        this.gnbs = gnbs == null ? null : gnbs.trim();
    }
}