package com.yfny.corepojo.entity.demandform.model;

import java.math.BigDecimal;

public class Kfdxx {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.KFDH
	 * @mbggenerated
	 */
	private String kfdh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.KFDMC
	 * @mbggenerated
	 */
	private String kfdmc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.SJDH
	 * @mbggenerated
	 */
	private String sjdh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.SJDMC
	 * @mbggenerated
	 */
	private String sjdmc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.KFDWMC
	 * @mbggenerated
	 */
	private String kfdwmc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.KFBMMC
	 * @mbggenerated
	 */
	private String kfbmmc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.KFFZRID
	 * @mbggenerated
	 */
	private String kffzrid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.KFFZRMC
	 * @mbggenerated
	 */
	private String kffzrmc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.LXFS
	 * @mbggenerated
	 */
	private String lxfs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.YJKSSJ
	 * @mbggenerated
	 */
	private String yjkssj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.YJJSSJ
	 * @mbggenerated
	 */
	private String yjjssj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.FPRID
	 * @mbggenerated
	 */
	private String fprid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.FPRXM
	 * @mbggenerated
	 */
	private String fprxm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.FPSJ
	 * @mbggenerated
	 */
	private String fpsj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.SJKSSJ
	 * @mbggenerated
	 */
	private String sjkssj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.SJJSSJ
	 * @mbggenerated
	 */
	private String sjjssj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.YWCBFB
	 * @mbggenerated
	 */
	private BigDecimal ywcbfb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.DQZT
	 * @mbggenerated
	 */
	private BigDecimal dqzt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.KFFY
	 * @mbggenerated
	 */
	private Double kffy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.CJRID
	 * @mbggenerated
	 */
	private String cjrid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.CJRMC
	 * @mbggenerated
	 */
	private String cjrmc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.CJSJ
	 * @mbggenerated
	 */
	private String cjsj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.TCSJ
	 * @mbggenerated
	 */
	private String tcsj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.SHRID
	 * @mbggenerated
	 */
	private String shrid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.SHR
	 * @mbggenerated
	 */
	private String shr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.SHYJ
	 * @mbggenerated
	 */
	private String shyj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.SHSJ
	 * @mbggenerated
	 */
	private String shsj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.GDZT
	 * @mbggenerated
	 */
	private String gdzt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.ZZID
	 * @mbggenerated
	 */
	private String zzid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_KFD_KFDXX.XQBBH
	 * @mbggenerated
	 */
	private String xqbbh;

	public Kfdxx(String kfdh, String kfdmc, String sjdh, String sjdmc,
			String kfdwmc, String kfbmmc, String kffzrid, String kffzrmc,
			String lxfs, String yjkssj, String yjjssj, String fprid,
			String fprxm, String fpsj, String sjkssj, String sjjssj,
			BigDecimal ywcbfb, BigDecimal dqzt, Double kffy, String cjrid,
			String cjrmc, String cjsj, String tcsj, String shrid, String shr,
			String shyj, String shsj, String gdzt, String zzid, String xqbbh) {
		this.kfdh = kfdh;
		this.kfdmc = kfdmc;
		this.sjdh = sjdh;
		this.sjdmc = sjdmc;
		this.kfdwmc = kfdwmc;
		this.kfbmmc = kfbmmc;
		this.kffzrid = kffzrid;
		this.kffzrmc = kffzrmc;
		this.lxfs = lxfs;
		this.yjkssj = yjkssj;
		this.yjjssj = yjjssj;
		this.fprid = fprid;
		this.fprxm = fprxm;
		this.fpsj = fpsj;
		this.sjkssj = sjkssj;
		this.sjjssj = sjjssj;
		this.ywcbfb = ywcbfb;
		this.dqzt = dqzt;
		this.kffy = kffy;
		this.cjrid = cjrid;
		this.cjrmc = cjrmc;
		this.cjsj = cjsj;
		this.tcsj = tcsj;
		this.shrid = shrid;
		this.shr = shr;
		this.shyj = shyj;
		this.shsj = shsj;
		this.gdzt = gdzt;
		this.zzid = zzid;
		this.xqbbh = xqbbh;
	}

	public Kfdxx() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.KFDH
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.KFDH
	 * @mbggenerated
	 */
	public String getKfdh() {
		return kfdh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.KFDH
	 * @param kfdh  the value for NWIDP.IMP_KFD_KFDXX.KFDH
	 * @mbggenerated
	 */
	public void setKfdh(String kfdh) {
		this.kfdh = kfdh == null ? null : kfdh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.KFDMC
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.KFDMC
	 * @mbggenerated
	 */
	public String getKfdmc() {
		return kfdmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.KFDMC
	 * @param kfdmc  the value for NWIDP.IMP_KFD_KFDXX.KFDMC
	 * @mbggenerated
	 */
	public void setKfdmc(String kfdmc) {
		this.kfdmc = kfdmc == null ? null : kfdmc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.SJDH
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.SJDH
	 * @mbggenerated
	 */
	public String getSjdh() {
		return sjdh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.SJDH
	 * @param sjdh  the value for NWIDP.IMP_KFD_KFDXX.SJDH
	 * @mbggenerated
	 */
	public void setSjdh(String sjdh) {
		this.sjdh = sjdh == null ? null : sjdh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.SJDMC
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.SJDMC
	 * @mbggenerated
	 */
	public String getSjdmc() {
		return sjdmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.SJDMC
	 * @param sjdmc  the value for NWIDP.IMP_KFD_KFDXX.SJDMC
	 * @mbggenerated
	 */
	public void setSjdmc(String sjdmc) {
		this.sjdmc = sjdmc == null ? null : sjdmc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.KFDWMC
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.KFDWMC
	 * @mbggenerated
	 */
	public String getKfdwmc() {
		return kfdwmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.KFDWMC
	 * @param kfdwmc  the value for NWIDP.IMP_KFD_KFDXX.KFDWMC
	 * @mbggenerated
	 */
	public void setKfdwmc(String kfdwmc) {
		this.kfdwmc = kfdwmc == null ? null : kfdwmc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.KFBMMC
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.KFBMMC
	 * @mbggenerated
	 */
	public String getKfbmmc() {
		return kfbmmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.KFBMMC
	 * @param kfbmmc  the value for NWIDP.IMP_KFD_KFDXX.KFBMMC
	 * @mbggenerated
	 */
	public void setKfbmmc(String kfbmmc) {
		this.kfbmmc = kfbmmc == null ? null : kfbmmc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.KFFZRID
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.KFFZRID
	 * @mbggenerated
	 */
	public String getKffzrid() {
		return kffzrid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.KFFZRID
	 * @param kffzrid  the value for NWIDP.IMP_KFD_KFDXX.KFFZRID
	 * @mbggenerated
	 */
	public void setKffzrid(String kffzrid) {
		this.kffzrid = kffzrid == null ? null : kffzrid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.KFFZRMC
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.KFFZRMC
	 * @mbggenerated
	 */
	public String getKffzrmc() {
		return kffzrmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.KFFZRMC
	 * @param kffzrmc  the value for NWIDP.IMP_KFD_KFDXX.KFFZRMC
	 * @mbggenerated
	 */
	public void setKffzrmc(String kffzrmc) {
		this.kffzrmc = kffzrmc == null ? null : kffzrmc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.LXFS
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.LXFS
	 * @mbggenerated
	 */
	public String getLxfs() {
		return lxfs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.LXFS
	 * @param lxfs  the value for NWIDP.IMP_KFD_KFDXX.LXFS
	 * @mbggenerated
	 */
	public void setLxfs(String lxfs) {
		this.lxfs = lxfs == null ? null : lxfs.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.YJKSSJ
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.YJKSSJ
	 * @mbggenerated
	 */
	public String getYjkssj() {
		return yjkssj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.YJKSSJ
	 * @param yjkssj  the value for NWIDP.IMP_KFD_KFDXX.YJKSSJ
	 * @mbggenerated
	 */
	public void setYjkssj(String yjkssj) {
		this.yjkssj = yjkssj == null ? null : yjkssj.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.YJJSSJ
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.YJJSSJ
	 * @mbggenerated
	 */
	public String getYjjssj() {
		return yjjssj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.YJJSSJ
	 * @param yjjssj  the value for NWIDP.IMP_KFD_KFDXX.YJJSSJ
	 * @mbggenerated
	 */
	public void setYjjssj(String yjjssj) {
		this.yjjssj = yjjssj == null ? null : yjjssj.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.FPRID
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.FPRID
	 * @mbggenerated
	 */
	public String getFprid() {
		return fprid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.FPRID
	 * @param fprid  the value for NWIDP.IMP_KFD_KFDXX.FPRID
	 * @mbggenerated
	 */
	public void setFprid(String fprid) {
		this.fprid = fprid == null ? null : fprid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.FPRXM
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.FPRXM
	 * @mbggenerated
	 */
	public String getFprxm() {
		return fprxm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.FPRXM
	 * @param fprxm  the value for NWIDP.IMP_KFD_KFDXX.FPRXM
	 * @mbggenerated
	 */
	public void setFprxm(String fprxm) {
		this.fprxm = fprxm == null ? null : fprxm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.FPSJ
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.FPSJ
	 * @mbggenerated
	 */
	public String getFpsj() {
		return fpsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.FPSJ
	 * @param fpsj  the value for NWIDP.IMP_KFD_KFDXX.FPSJ
	 * @mbggenerated
	 */
	public void setFpsj(String fpsj) {
		this.fpsj = fpsj == null ? null : fpsj.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.SJKSSJ
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.SJKSSJ
	 * @mbggenerated
	 */
	public String getSjkssj() {
		return sjkssj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.SJKSSJ
	 * @param sjkssj  the value for NWIDP.IMP_KFD_KFDXX.SJKSSJ
	 * @mbggenerated
	 */
	public void setSjkssj(String sjkssj) {
		this.sjkssj = sjkssj == null ? null : sjkssj.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.SJJSSJ
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.SJJSSJ
	 * @mbggenerated
	 */
	public String getSjjssj() {
		return sjjssj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.SJJSSJ
	 * @param sjjssj  the value for NWIDP.IMP_KFD_KFDXX.SJJSSJ
	 * @mbggenerated
	 */
	public void setSjjssj(String sjjssj) {
		this.sjjssj = sjjssj == null ? null : sjjssj.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.YWCBFB
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.YWCBFB
	 * @mbggenerated
	 */
	public BigDecimal getYwcbfb() {
		return ywcbfb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.YWCBFB
	 * @param ywcbfb  the value for NWIDP.IMP_KFD_KFDXX.YWCBFB
	 * @mbggenerated
	 */
	public void setYwcbfb(BigDecimal ywcbfb) {
		this.ywcbfb = ywcbfb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.DQZT
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.DQZT
	 * @mbggenerated
	 */
	public BigDecimal getDqzt() {
		return dqzt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.DQZT
	 * @param dqzt  the value for NWIDP.IMP_KFD_KFDXX.DQZT
	 * @mbggenerated
	 */
	public void setDqzt(BigDecimal dqzt) {
		this.dqzt = dqzt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.KFFY
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.KFFY
	 * @mbggenerated
	 */
	public Double getKffy() {
		return kffy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.KFFY
	 * @param kffy  the value for NWIDP.IMP_KFD_KFDXX.KFFY
	 * @mbggenerated
	 */
	public void setKffy(Double kffy) {
		this.kffy = kffy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.CJRID
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.CJRID
	 * @mbggenerated
	 */
	public String getCjrid() {
		return cjrid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.CJRID
	 * @param cjrid  the value for NWIDP.IMP_KFD_KFDXX.CJRID
	 * @mbggenerated
	 */
	public void setCjrid(String cjrid) {
		this.cjrid = cjrid == null ? null : cjrid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.CJRMC
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.CJRMC
	 * @mbggenerated
	 */
	public String getCjrmc() {
		return cjrmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.CJRMC
	 * @param cjrmc  the value for NWIDP.IMP_KFD_KFDXX.CJRMC
	 * @mbggenerated
	 */
	public void setCjrmc(String cjrmc) {
		this.cjrmc = cjrmc == null ? null : cjrmc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.CJSJ
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.CJSJ
	 * @mbggenerated
	 */
	public String getCjsj() {
		return cjsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.CJSJ
	 * @param cjsj  the value for NWIDP.IMP_KFD_KFDXX.CJSJ
	 * @mbggenerated
	 */
	public void setCjsj(String cjsj) {
		this.cjsj = cjsj == null ? null : cjsj.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.TCSJ
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.TCSJ
	 * @mbggenerated
	 */
	public String getTcsj() {
		return tcsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.TCSJ
	 * @param tcsj  the value for NWIDP.IMP_KFD_KFDXX.TCSJ
	 * @mbggenerated
	 */
	public void setTcsj(String tcsj) {
		this.tcsj = tcsj == null ? null : tcsj.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.SHRID
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.SHRID
	 * @mbggenerated
	 */
	public String getShrid() {
		return shrid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.SHRID
	 * @param shrid  the value for NWIDP.IMP_KFD_KFDXX.SHRID
	 * @mbggenerated
	 */
	public void setShrid(String shrid) {
		this.shrid = shrid == null ? null : shrid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.SHR
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.SHR
	 * @mbggenerated
	 */
	public String getShr() {
		return shr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.SHR
	 * @param shr  the value for NWIDP.IMP_KFD_KFDXX.SHR
	 * @mbggenerated
	 */
	public void setShr(String shr) {
		this.shr = shr == null ? null : shr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.SHYJ
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.SHYJ
	 * @mbggenerated
	 */
	public String getShyj() {
		return shyj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.SHYJ
	 * @param shyj  the value for NWIDP.IMP_KFD_KFDXX.SHYJ
	 * @mbggenerated
	 */
	public void setShyj(String shyj) {
		this.shyj = shyj == null ? null : shyj.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.SHSJ
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.SHSJ
	 * @mbggenerated
	 */
	public String getShsj() {
		return shsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.SHSJ
	 * @param shsj  the value for NWIDP.IMP_KFD_KFDXX.SHSJ
	 * @mbggenerated
	 */
	public void setShsj(String shsj) {
		this.shsj = shsj == null ? null : shsj.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.GDZT
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.GDZT
	 * @mbggenerated
	 */
	public String getGdzt() {
		return gdzt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.GDZT
	 * @param gdzt  the value for NWIDP.IMP_KFD_KFDXX.GDZT
	 * @mbggenerated
	 */
	public void setGdzt(String gdzt) {
		this.gdzt = gdzt == null ? null : gdzt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.ZZID
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.ZZID
	 * @mbggenerated
	 */
	public String getZzid() {
		return zzid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.ZZID
	 * @param zzid  the value for NWIDP.IMP_KFD_KFDXX.ZZID
	 * @mbggenerated
	 */
	public void setZzid(String zzid) {
		this.zzid = zzid == null ? null : zzid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_KFD_KFDXX.XQBBH
	 * @return  the value of NWIDP.IMP_KFD_KFDXX.XQBBH
	 * @mbggenerated
	 */
	public String getXqbbh() {
		return xqbbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_KFD_KFDXX.XQBBH
	 * @param xqbbh  the value for NWIDP.IMP_KFD_KFDXX.XQBBH
	 * @mbggenerated
	 */
	public void setXqbbh(String xqbbh) {
		this.xqbbh = xqbbh == null ? null : xqbbh.trim();
	}

	public Kfdxx(String kfdh, String kfdmc, String sjdh, String sjdmc,
			String kfdwmc, String kfbmmc, String kffzrid, String kffzrmc,
			String lxfs, String yjkssj, String yjjssj, String fprid,
			String fprxm, String fpsj, String sjkssj, String sjjssj,
			BigDecimal ywcbfb, BigDecimal dqzt, Double kffy, String cjrid,
			String cjrmc, String cjsj, String tcsj, String shrid, String shr,
			String shyj, String shsj, String gdzt, String zzid) {
		this.kfdh = kfdh;
		this.kfdmc = kfdmc;
		this.sjdh = sjdh;
		this.sjdmc = sjdmc;
		this.kfdwmc = kfdwmc;
		this.kfbmmc = kfbmmc;
		this.kffzrid = kffzrid;
		this.kffzrmc = kffzrmc;
		this.lxfs = lxfs;
		this.yjkssj = yjkssj;
		this.yjjssj = yjjssj;
		this.fprid = fprid;
		this.fprxm = fprxm;
		this.fpsj = fpsj;
		this.sjkssj = sjkssj;
		this.sjjssj = sjjssj;
		this.ywcbfb = ywcbfb;
		this.dqzt = dqzt;
		this.kffy = kffy;
		this.cjrid = cjrid;
		this.cjrmc = cjrmc;
		this.cjsj = cjsj;
		this.tcsj = tcsj;
		this.shrid = shrid;
		this.shr = shr;
		this.shyj = shyj;
		this.shsj = shsj;
		this.gdzt = gdzt;
		this.zzid = zzid;
	}
}