package com.yfny.corepojo.entity.demandform.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class KfdxxExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table NWIDP.IMP_KFD_KFDXX
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table NWIDP.IMP_KFD_KFDXX
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table NWIDP.IMP_KFD_KFDXX
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NWIDP.IMP_KFD_KFDXX
	 * @mbggenerated
	 */
	public KfdxxExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NWIDP.IMP_KFD_KFDXX
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NWIDP.IMP_KFD_KFDXX
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NWIDP.IMP_KFD_KFDXX
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NWIDP.IMP_KFD_KFDXX
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NWIDP.IMP_KFD_KFDXX
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NWIDP.IMP_KFD_KFDXX
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NWIDP.IMP_KFD_KFDXX
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NWIDP.IMP_KFD_KFDXX
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NWIDP.IMP_KFD_KFDXX
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NWIDP.IMP_KFD_KFDXX
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table NWIDP.IMP_KFD_KFDXX
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andKfdhIsNull() {
			addCriterion("KFDH is null");
			return (Criteria) this;
		}

		public Criteria andKfdhIsNotNull() {
			addCriterion("KFDH is not null");
			return (Criteria) this;
		}

		public Criteria andKfdhEqualTo(String value) {
			addCriterion("KFDH =", value, "kfdh");
			return (Criteria) this;
		}

		public Criteria andKfdhNotEqualTo(String value) {
			addCriterion("KFDH <>", value, "kfdh");
			return (Criteria) this;
		}

		public Criteria andKfdhGreaterThan(String value) {
			addCriterion("KFDH >", value, "kfdh");
			return (Criteria) this;
		}

		public Criteria andKfdhGreaterThanOrEqualTo(String value) {
			addCriterion("KFDH >=", value, "kfdh");
			return (Criteria) this;
		}

		public Criteria andKfdhLessThan(String value) {
			addCriterion("KFDH <", value, "kfdh");
			return (Criteria) this;
		}

		public Criteria andKfdhLessThanOrEqualTo(String value) {
			addCriterion("KFDH <=", value, "kfdh");
			return (Criteria) this;
		}

		public Criteria andKfdhLike(String value) {
			addCriterion("KFDH like", value, "kfdh");
			return (Criteria) this;
		}

		public Criteria andKfdhNotLike(String value) {
			addCriterion("KFDH not like", value, "kfdh");
			return (Criteria) this;
		}

		public Criteria andKfdhIn(List<String> values) {
			addCriterion("KFDH in", values, "kfdh");
			return (Criteria) this;
		}

		public Criteria andKfdhNotIn(List<String> values) {
			addCriterion("KFDH not in", values, "kfdh");
			return (Criteria) this;
		}

		public Criteria andKfdhBetween(String value1, String value2) {
			addCriterion("KFDH between", value1, value2, "kfdh");
			return (Criteria) this;
		}

		public Criteria andKfdhNotBetween(String value1, String value2) {
			addCriterion("KFDH not between", value1, value2, "kfdh");
			return (Criteria) this;
		}

		public Criteria andKfdmcIsNull() {
			addCriterion("KFDMC is null");
			return (Criteria) this;
		}

		public Criteria andKfdmcIsNotNull() {
			addCriterion("KFDMC is not null");
			return (Criteria) this;
		}

		public Criteria andKfdmcEqualTo(String value) {
			addCriterion("KFDMC =", value, "kfdmc");
			return (Criteria) this;
		}

		public Criteria andKfdmcNotEqualTo(String value) {
			addCriterion("KFDMC <>", value, "kfdmc");
			return (Criteria) this;
		}

		public Criteria andKfdmcGreaterThan(String value) {
			addCriterion("KFDMC >", value, "kfdmc");
			return (Criteria) this;
		}

		public Criteria andKfdmcGreaterThanOrEqualTo(String value) {
			addCriterion("KFDMC >=", value, "kfdmc");
			return (Criteria) this;
		}

		public Criteria andKfdmcLessThan(String value) {
			addCriterion("KFDMC <", value, "kfdmc");
			return (Criteria) this;
		}

		public Criteria andKfdmcLessThanOrEqualTo(String value) {
			addCriterion("KFDMC <=", value, "kfdmc");
			return (Criteria) this;
		}

		public Criteria andKfdmcLike(String value) {
			addCriterion("KFDMC like", value, "kfdmc");
			return (Criteria) this;
		}

		public Criteria andKfdmcNotLike(String value) {
			addCriterion("KFDMC not like", value, "kfdmc");
			return (Criteria) this;
		}

		public Criteria andKfdmcIn(List<String> values) {
			addCriterion("KFDMC in", values, "kfdmc");
			return (Criteria) this;
		}

		public Criteria andKfdmcNotIn(List<String> values) {
			addCriterion("KFDMC not in", values, "kfdmc");
			return (Criteria) this;
		}

		public Criteria andKfdmcBetween(String value1, String value2) {
			addCriterion("KFDMC between", value1, value2, "kfdmc");
			return (Criteria) this;
		}

		public Criteria andKfdmcNotBetween(String value1, String value2) {
			addCriterion("KFDMC not between", value1, value2, "kfdmc");
			return (Criteria) this;
		}

		public Criteria andSjdhIsNull() {
			addCriterion("SJDH is null");
			return (Criteria) this;
		}

		public Criteria andSjdhIsNotNull() {
			addCriterion("SJDH is not null");
			return (Criteria) this;
		}

		public Criteria andSjdhEqualTo(String value) {
			addCriterion("SJDH =", value, "sjdh");
			return (Criteria) this;
		}

		public Criteria andSjdhNotEqualTo(String value) {
			addCriterion("SJDH <>", value, "sjdh");
			return (Criteria) this;
		}

		public Criteria andSjdhGreaterThan(String value) {
			addCriterion("SJDH >", value, "sjdh");
			return (Criteria) this;
		}

		public Criteria andSjdhGreaterThanOrEqualTo(String value) {
			addCriterion("SJDH >=", value, "sjdh");
			return (Criteria) this;
		}

		public Criteria andSjdhLessThan(String value) {
			addCriterion("SJDH <", value, "sjdh");
			return (Criteria) this;
		}

		public Criteria andSjdhLessThanOrEqualTo(String value) {
			addCriterion("SJDH <=", value, "sjdh");
			return (Criteria) this;
		}

		public Criteria andSjdhLike(String value) {
			addCriterion("SJDH like", value, "sjdh");
			return (Criteria) this;
		}

		public Criteria andSjdhNotLike(String value) {
			addCriterion("SJDH not like", value, "sjdh");
			return (Criteria) this;
		}

		public Criteria andSjdhIn(List<String> values) {
			addCriterion("SJDH in", values, "sjdh");
			return (Criteria) this;
		}

		public Criteria andSjdhNotIn(List<String> values) {
			addCriterion("SJDH not in", values, "sjdh");
			return (Criteria) this;
		}

		public Criteria andSjdhBetween(String value1, String value2) {
			addCriterion("SJDH between", value1, value2, "sjdh");
			return (Criteria) this;
		}

		public Criteria andSjdhNotBetween(String value1, String value2) {
			addCriterion("SJDH not between", value1, value2, "sjdh");
			return (Criteria) this;
		}

		public Criteria andSjdmcIsNull() {
			addCriterion("SJDMC is null");
			return (Criteria) this;
		}

		public Criteria andSjdmcIsNotNull() {
			addCriterion("SJDMC is not null");
			return (Criteria) this;
		}

		public Criteria andSjdmcEqualTo(String value) {
			addCriterion("SJDMC =", value, "sjdmc");
			return (Criteria) this;
		}

		public Criteria andSjdmcNotEqualTo(String value) {
			addCriterion("SJDMC <>", value, "sjdmc");
			return (Criteria) this;
		}

		public Criteria andSjdmcGreaterThan(String value) {
			addCriterion("SJDMC >", value, "sjdmc");
			return (Criteria) this;
		}

		public Criteria andSjdmcGreaterThanOrEqualTo(String value) {
			addCriterion("SJDMC >=", value, "sjdmc");
			return (Criteria) this;
		}

		public Criteria andSjdmcLessThan(String value) {
			addCriterion("SJDMC <", value, "sjdmc");
			return (Criteria) this;
		}

		public Criteria andSjdmcLessThanOrEqualTo(String value) {
			addCriterion("SJDMC <=", value, "sjdmc");
			return (Criteria) this;
		}

		public Criteria andSjdmcLike(String value) {
			addCriterion("SJDMC like", value, "sjdmc");
			return (Criteria) this;
		}

		public Criteria andSjdmcNotLike(String value) {
			addCriterion("SJDMC not like", value, "sjdmc");
			return (Criteria) this;
		}

		public Criteria andSjdmcIn(List<String> values) {
			addCriterion("SJDMC in", values, "sjdmc");
			return (Criteria) this;
		}

		public Criteria andSjdmcNotIn(List<String> values) {
			addCriterion("SJDMC not in", values, "sjdmc");
			return (Criteria) this;
		}

		public Criteria andSjdmcBetween(String value1, String value2) {
			addCriterion("SJDMC between", value1, value2, "sjdmc");
			return (Criteria) this;
		}

		public Criteria andSjdmcNotBetween(String value1, String value2) {
			addCriterion("SJDMC not between", value1, value2, "sjdmc");
			return (Criteria) this;
		}

		public Criteria andKfdwmcIsNull() {
			addCriterion("KFDWMC is null");
			return (Criteria) this;
		}

		public Criteria andKfdwmcIsNotNull() {
			addCriterion("KFDWMC is not null");
			return (Criteria) this;
		}

		public Criteria andKfdwmcEqualTo(String value) {
			addCriterion("KFDWMC =", value, "kfdwmc");
			return (Criteria) this;
		}

		public Criteria andKfdwmcNotEqualTo(String value) {
			addCriterion("KFDWMC <>", value, "kfdwmc");
			return (Criteria) this;
		}

		public Criteria andKfdwmcGreaterThan(String value) {
			addCriterion("KFDWMC >", value, "kfdwmc");
			return (Criteria) this;
		}

		public Criteria andKfdwmcGreaterThanOrEqualTo(String value) {
			addCriterion("KFDWMC >=", value, "kfdwmc");
			return (Criteria) this;
		}

		public Criteria andKfdwmcLessThan(String value) {
			addCriterion("KFDWMC <", value, "kfdwmc");
			return (Criteria) this;
		}

		public Criteria andKfdwmcLessThanOrEqualTo(String value) {
			addCriterion("KFDWMC <=", value, "kfdwmc");
			return (Criteria) this;
		}

		public Criteria andKfdwmcLike(String value) {
			addCriterion("KFDWMC like", value, "kfdwmc");
			return (Criteria) this;
		}

		public Criteria andKfdwmcNotLike(String value) {
			addCriterion("KFDWMC not like", value, "kfdwmc");
			return (Criteria) this;
		}

		public Criteria andKfdwmcIn(List<String> values) {
			addCriterion("KFDWMC in", values, "kfdwmc");
			return (Criteria) this;
		}

		public Criteria andKfdwmcNotIn(List<String> values) {
			addCriterion("KFDWMC not in", values, "kfdwmc");
			return (Criteria) this;
		}

		public Criteria andKfdwmcBetween(String value1, String value2) {
			addCriterion("KFDWMC between", value1, value2, "kfdwmc");
			return (Criteria) this;
		}

		public Criteria andKfdwmcNotBetween(String value1, String value2) {
			addCriterion("KFDWMC not between", value1, value2, "kfdwmc");
			return (Criteria) this;
		}

		public Criteria andKfbmmcIsNull() {
			addCriterion("KFBMMC is null");
			return (Criteria) this;
		}

		public Criteria andKfbmmcIsNotNull() {
			addCriterion("KFBMMC is not null");
			return (Criteria) this;
		}

		public Criteria andKfbmmcEqualTo(String value) {
			addCriterion("KFBMMC =", value, "kfbmmc");
			return (Criteria) this;
		}

		public Criteria andKfbmmcNotEqualTo(String value) {
			addCriterion("KFBMMC <>", value, "kfbmmc");
			return (Criteria) this;
		}

		public Criteria andKfbmmcGreaterThan(String value) {
			addCriterion("KFBMMC >", value, "kfbmmc");
			return (Criteria) this;
		}

		public Criteria andKfbmmcGreaterThanOrEqualTo(String value) {
			addCriterion("KFBMMC >=", value, "kfbmmc");
			return (Criteria) this;
		}

		public Criteria andKfbmmcLessThan(String value) {
			addCriterion("KFBMMC <", value, "kfbmmc");
			return (Criteria) this;
		}

		public Criteria andKfbmmcLessThanOrEqualTo(String value) {
			addCriterion("KFBMMC <=", value, "kfbmmc");
			return (Criteria) this;
		}

		public Criteria andKfbmmcLike(String value) {
			addCriterion("KFBMMC like", value, "kfbmmc");
			return (Criteria) this;
		}

		public Criteria andKfbmmcNotLike(String value) {
			addCriterion("KFBMMC not like", value, "kfbmmc");
			return (Criteria) this;
		}

		public Criteria andKfbmmcIn(List<String> values) {
			addCriterion("KFBMMC in", values, "kfbmmc");
			return (Criteria) this;
		}

		public Criteria andKfbmmcNotIn(List<String> values) {
			addCriterion("KFBMMC not in", values, "kfbmmc");
			return (Criteria) this;
		}

		public Criteria andKfbmmcBetween(String value1, String value2) {
			addCriterion("KFBMMC between", value1, value2, "kfbmmc");
			return (Criteria) this;
		}

		public Criteria andKfbmmcNotBetween(String value1, String value2) {
			addCriterion("KFBMMC not between", value1, value2, "kfbmmc");
			return (Criteria) this;
		}

		public Criteria andKffzridIsNull() {
			addCriterion("KFFZRID is null");
			return (Criteria) this;
		}

		public Criteria andKffzridIsNotNull() {
			addCriterion("KFFZRID is not null");
			return (Criteria) this;
		}

		public Criteria andKffzridEqualTo(String value) {
			addCriterion("KFFZRID =", value, "kffzrid");
			return (Criteria) this;
		}

		public Criteria andKffzridNotEqualTo(String value) {
			addCriterion("KFFZRID <>", value, "kffzrid");
			return (Criteria) this;
		}

		public Criteria andKffzridGreaterThan(String value) {
			addCriterion("KFFZRID >", value, "kffzrid");
			return (Criteria) this;
		}

		public Criteria andKffzridGreaterThanOrEqualTo(String value) {
			addCriterion("KFFZRID >=", value, "kffzrid");
			return (Criteria) this;
		}

		public Criteria andKffzridLessThan(String value) {
			addCriterion("KFFZRID <", value, "kffzrid");
			return (Criteria) this;
		}

		public Criteria andKffzridLessThanOrEqualTo(String value) {
			addCriterion("KFFZRID <=", value, "kffzrid");
			return (Criteria) this;
		}

		public Criteria andKffzridLike(String value) {
			addCriterion("KFFZRID like", value, "kffzrid");
			return (Criteria) this;
		}

		public Criteria andKffzridNotLike(String value) {
			addCriterion("KFFZRID not like", value, "kffzrid");
			return (Criteria) this;
		}

		public Criteria andKffzridIn(List<String> values) {
			addCriterion("KFFZRID in", values, "kffzrid");
			return (Criteria) this;
		}

		public Criteria andKffzridNotIn(List<String> values) {
			addCriterion("KFFZRID not in", values, "kffzrid");
			return (Criteria) this;
		}

		public Criteria andKffzridBetween(String value1, String value2) {
			addCriterion("KFFZRID between", value1, value2, "kffzrid");
			return (Criteria) this;
		}

		public Criteria andKffzridNotBetween(String value1, String value2) {
			addCriterion("KFFZRID not between", value1, value2, "kffzrid");
			return (Criteria) this;
		}

		public Criteria andKffzrmcIsNull() {
			addCriterion("KFFZRMC is null");
			return (Criteria) this;
		}

		public Criteria andKffzrmcIsNotNull() {
			addCriterion("KFFZRMC is not null");
			return (Criteria) this;
		}

		public Criteria andKffzrmcEqualTo(String value) {
			addCriterion("KFFZRMC =", value, "kffzrmc");
			return (Criteria) this;
		}

		public Criteria andKffzrmcNotEqualTo(String value) {
			addCriterion("KFFZRMC <>", value, "kffzrmc");
			return (Criteria) this;
		}

		public Criteria andKffzrmcGreaterThan(String value) {
			addCriterion("KFFZRMC >", value, "kffzrmc");
			return (Criteria) this;
		}

		public Criteria andKffzrmcGreaterThanOrEqualTo(String value) {
			addCriterion("KFFZRMC >=", value, "kffzrmc");
			return (Criteria) this;
		}

		public Criteria andKffzrmcLessThan(String value) {
			addCriterion("KFFZRMC <", value, "kffzrmc");
			return (Criteria) this;
		}

		public Criteria andKffzrmcLessThanOrEqualTo(String value) {
			addCriterion("KFFZRMC <=", value, "kffzrmc");
			return (Criteria) this;
		}

		public Criteria andKffzrmcLike(String value) {
			addCriterion("KFFZRMC like", value, "kffzrmc");
			return (Criteria) this;
		}

		public Criteria andKffzrmcNotLike(String value) {
			addCriterion("KFFZRMC not like", value, "kffzrmc");
			return (Criteria) this;
		}

		public Criteria andKffzrmcIn(List<String> values) {
			addCriterion("KFFZRMC in", values, "kffzrmc");
			return (Criteria) this;
		}

		public Criteria andKffzrmcNotIn(List<String> values) {
			addCriterion("KFFZRMC not in", values, "kffzrmc");
			return (Criteria) this;
		}

		public Criteria andKffzrmcBetween(String value1, String value2) {
			addCriterion("KFFZRMC between", value1, value2, "kffzrmc");
			return (Criteria) this;
		}

		public Criteria andKffzrmcNotBetween(String value1, String value2) {
			addCriterion("KFFZRMC not between", value1, value2, "kffzrmc");
			return (Criteria) this;
		}

		public Criteria andLxfsIsNull() {
			addCriterion("LXFS is null");
			return (Criteria) this;
		}

		public Criteria andLxfsIsNotNull() {
			addCriterion("LXFS is not null");
			return (Criteria) this;
		}

		public Criteria andLxfsEqualTo(String value) {
			addCriterion("LXFS =", value, "lxfs");
			return (Criteria) this;
		}

		public Criteria andLxfsNotEqualTo(String value) {
			addCriterion("LXFS <>", value, "lxfs");
			return (Criteria) this;
		}

		public Criteria andLxfsGreaterThan(String value) {
			addCriterion("LXFS >", value, "lxfs");
			return (Criteria) this;
		}

		public Criteria andLxfsGreaterThanOrEqualTo(String value) {
			addCriterion("LXFS >=", value, "lxfs");
			return (Criteria) this;
		}

		public Criteria andLxfsLessThan(String value) {
			addCriterion("LXFS <", value, "lxfs");
			return (Criteria) this;
		}

		public Criteria andLxfsLessThanOrEqualTo(String value) {
			addCriterion("LXFS <=", value, "lxfs");
			return (Criteria) this;
		}

		public Criteria andLxfsLike(String value) {
			addCriterion("LXFS like", value, "lxfs");
			return (Criteria) this;
		}

		public Criteria andLxfsNotLike(String value) {
			addCriterion("LXFS not like", value, "lxfs");
			return (Criteria) this;
		}

		public Criteria andLxfsIn(List<String> values) {
			addCriterion("LXFS in", values, "lxfs");
			return (Criteria) this;
		}

		public Criteria andLxfsNotIn(List<String> values) {
			addCriterion("LXFS not in", values, "lxfs");
			return (Criteria) this;
		}

		public Criteria andLxfsBetween(String value1, String value2) {
			addCriterion("LXFS between", value1, value2, "lxfs");
			return (Criteria) this;
		}

		public Criteria andLxfsNotBetween(String value1, String value2) {
			addCriterion("LXFS not between", value1, value2, "lxfs");
			return (Criteria) this;
		}

		public Criteria andYjkssjIsNull() {
			addCriterion("YJKSSJ is null");
			return (Criteria) this;
		}

		public Criteria andYjkssjIsNotNull() {
			addCriterion("YJKSSJ is not null");
			return (Criteria) this;
		}

		public Criteria andYjkssjEqualTo(String value) {
			addCriterion("YJKSSJ =", value, "yjkssj");
			return (Criteria) this;
		}

		public Criteria andYjkssjNotEqualTo(String value) {
			addCriterion("YJKSSJ <>", value, "yjkssj");
			return (Criteria) this;
		}

		public Criteria andYjkssjGreaterThan(String value) {
			addCriterion("YJKSSJ >", value, "yjkssj");
			return (Criteria) this;
		}

		public Criteria andYjkssjGreaterThanOrEqualTo(String value) {
			addCriterion("YJKSSJ >=", value, "yjkssj");
			return (Criteria) this;
		}

		public Criteria andYjkssjLessThan(String value) {
			addCriterion("YJKSSJ <", value, "yjkssj");
			return (Criteria) this;
		}

		public Criteria andYjkssjLessThanOrEqualTo(String value) {
			addCriterion("YJKSSJ <=", value, "yjkssj");
			return (Criteria) this;
		}

		public Criteria andYjkssjLike(String value) {
			addCriterion("YJKSSJ like", value, "yjkssj");
			return (Criteria) this;
		}

		public Criteria andYjkssjNotLike(String value) {
			addCriterion("YJKSSJ not like", value, "yjkssj");
			return (Criteria) this;
		}

		public Criteria andYjkssjIn(List<String> values) {
			addCriterion("YJKSSJ in", values, "yjkssj");
			return (Criteria) this;
		}

		public Criteria andYjkssjNotIn(List<String> values) {
			addCriterion("YJKSSJ not in", values, "yjkssj");
			return (Criteria) this;
		}

		public Criteria andYjkssjBetween(String value1, String value2) {
			addCriterion("YJKSSJ between", value1, value2, "yjkssj");
			return (Criteria) this;
		}

		public Criteria andYjkssjNotBetween(String value1, String value2) {
			addCriterion("YJKSSJ not between", value1, value2, "yjkssj");
			return (Criteria) this;
		}

		public Criteria andYjjssjIsNull() {
			addCriterion("YJJSSJ is null");
			return (Criteria) this;
		}

		public Criteria andYjjssjIsNotNull() {
			addCriterion("YJJSSJ is not null");
			return (Criteria) this;
		}

		public Criteria andYjjssjEqualTo(String value) {
			addCriterion("YJJSSJ =", value, "yjjssj");
			return (Criteria) this;
		}

		public Criteria andYjjssjNotEqualTo(String value) {
			addCriterion("YJJSSJ <>", value, "yjjssj");
			return (Criteria) this;
		}

		public Criteria andYjjssjGreaterThan(String value) {
			addCriterion("YJJSSJ >", value, "yjjssj");
			return (Criteria) this;
		}

		public Criteria andYjjssjGreaterThanOrEqualTo(String value) {
			addCriterion("YJJSSJ >=", value, "yjjssj");
			return (Criteria) this;
		}

		public Criteria andYjjssjLessThan(String value) {
			addCriterion("YJJSSJ <", value, "yjjssj");
			return (Criteria) this;
		}

		public Criteria andYjjssjLessThanOrEqualTo(String value) {
			addCriterion("YJJSSJ <=", value, "yjjssj");
			return (Criteria) this;
		}

		public Criteria andYjjssjLike(String value) {
			addCriterion("YJJSSJ like", value, "yjjssj");
			return (Criteria) this;
		}

		public Criteria andYjjssjNotLike(String value) {
			addCriterion("YJJSSJ not like", value, "yjjssj");
			return (Criteria) this;
		}

		public Criteria andYjjssjIn(List<String> values) {
			addCriterion("YJJSSJ in", values, "yjjssj");
			return (Criteria) this;
		}

		public Criteria andYjjssjNotIn(List<String> values) {
			addCriterion("YJJSSJ not in", values, "yjjssj");
			return (Criteria) this;
		}

		public Criteria andYjjssjBetween(String value1, String value2) {
			addCriterion("YJJSSJ between", value1, value2, "yjjssj");
			return (Criteria) this;
		}

		public Criteria andYjjssjNotBetween(String value1, String value2) {
			addCriterion("YJJSSJ not between", value1, value2, "yjjssj");
			return (Criteria) this;
		}

		public Criteria andFpridIsNull() {
			addCriterion("FPRID is null");
			return (Criteria) this;
		}

		public Criteria andFpridIsNotNull() {
			addCriterion("FPRID is not null");
			return (Criteria) this;
		}

		public Criteria andFpridEqualTo(String value) {
			addCriterion("FPRID =", value, "fprid");
			return (Criteria) this;
		}

		public Criteria andFpridNotEqualTo(String value) {
			addCriterion("FPRID <>", value, "fprid");
			return (Criteria) this;
		}

		public Criteria andFpridGreaterThan(String value) {
			addCriterion("FPRID >", value, "fprid");
			return (Criteria) this;
		}

		public Criteria andFpridGreaterThanOrEqualTo(String value) {
			addCriterion("FPRID >=", value, "fprid");
			return (Criteria) this;
		}

		public Criteria andFpridLessThan(String value) {
			addCriterion("FPRID <", value, "fprid");
			return (Criteria) this;
		}

		public Criteria andFpridLessThanOrEqualTo(String value) {
			addCriterion("FPRID <=", value, "fprid");
			return (Criteria) this;
		}

		public Criteria andFpridLike(String value) {
			addCriterion("FPRID like", value, "fprid");
			return (Criteria) this;
		}

		public Criteria andFpridNotLike(String value) {
			addCriterion("FPRID not like", value, "fprid");
			return (Criteria) this;
		}

		public Criteria andFpridIn(List<String> values) {
			addCriterion("FPRID in", values, "fprid");
			return (Criteria) this;
		}

		public Criteria andFpridNotIn(List<String> values) {
			addCriterion("FPRID not in", values, "fprid");
			return (Criteria) this;
		}

		public Criteria andFpridBetween(String value1, String value2) {
			addCriterion("FPRID between", value1, value2, "fprid");
			return (Criteria) this;
		}

		public Criteria andFpridNotBetween(String value1, String value2) {
			addCriterion("FPRID not between", value1, value2, "fprid");
			return (Criteria) this;
		}

		public Criteria andFprxmIsNull() {
			addCriterion("FPRXM is null");
			return (Criteria) this;
		}

		public Criteria andFprxmIsNotNull() {
			addCriterion("FPRXM is not null");
			return (Criteria) this;
		}

		public Criteria andFprxmEqualTo(String value) {
			addCriterion("FPRXM =", value, "fprxm");
			return (Criteria) this;
		}

		public Criteria andFprxmNotEqualTo(String value) {
			addCriterion("FPRXM <>", value, "fprxm");
			return (Criteria) this;
		}

		public Criteria andFprxmGreaterThan(String value) {
			addCriterion("FPRXM >", value, "fprxm");
			return (Criteria) this;
		}

		public Criteria andFprxmGreaterThanOrEqualTo(String value) {
			addCriterion("FPRXM >=", value, "fprxm");
			return (Criteria) this;
		}

		public Criteria andFprxmLessThan(String value) {
			addCriterion("FPRXM <", value, "fprxm");
			return (Criteria) this;
		}

		public Criteria andFprxmLessThanOrEqualTo(String value) {
			addCriterion("FPRXM <=", value, "fprxm");
			return (Criteria) this;
		}

		public Criteria andFprxmLike(String value) {
			addCriterion("FPRXM like", value, "fprxm");
			return (Criteria) this;
		}

		public Criteria andFprxmNotLike(String value) {
			addCriterion("FPRXM not like", value, "fprxm");
			return (Criteria) this;
		}

		public Criteria andFprxmIn(List<String> values) {
			addCriterion("FPRXM in", values, "fprxm");
			return (Criteria) this;
		}

		public Criteria andFprxmNotIn(List<String> values) {
			addCriterion("FPRXM not in", values, "fprxm");
			return (Criteria) this;
		}

		public Criteria andFprxmBetween(String value1, String value2) {
			addCriterion("FPRXM between", value1, value2, "fprxm");
			return (Criteria) this;
		}

		public Criteria andFprxmNotBetween(String value1, String value2) {
			addCriterion("FPRXM not between", value1, value2, "fprxm");
			return (Criteria) this;
		}

		public Criteria andFpsjIsNull() {
			addCriterion("FPSJ is null");
			return (Criteria) this;
		}

		public Criteria andFpsjIsNotNull() {
			addCriterion("FPSJ is not null");
			return (Criteria) this;
		}

		public Criteria andFpsjEqualTo(String value) {
			addCriterion("FPSJ =", value, "fpsj");
			return (Criteria) this;
		}

		public Criteria andFpsjNotEqualTo(String value) {
			addCriterion("FPSJ <>", value, "fpsj");
			return (Criteria) this;
		}

		public Criteria andFpsjGreaterThan(String value) {
			addCriterion("FPSJ >", value, "fpsj");
			return (Criteria) this;
		}

		public Criteria andFpsjGreaterThanOrEqualTo(String value) {
			addCriterion("FPSJ >=", value, "fpsj");
			return (Criteria) this;
		}

		public Criteria andFpsjLessThan(String value) {
			addCriterion("FPSJ <", value, "fpsj");
			return (Criteria) this;
		}

		public Criteria andFpsjLessThanOrEqualTo(String value) {
			addCriterion("FPSJ <=", value, "fpsj");
			return (Criteria) this;
		}

		public Criteria andFpsjLike(String value) {
			addCriterion("FPSJ like", value, "fpsj");
			return (Criteria) this;
		}

		public Criteria andFpsjNotLike(String value) {
			addCriterion("FPSJ not like", value, "fpsj");
			return (Criteria) this;
		}

		public Criteria andFpsjIn(List<String> values) {
			addCriterion("FPSJ in", values, "fpsj");
			return (Criteria) this;
		}

		public Criteria andFpsjNotIn(List<String> values) {
			addCriterion("FPSJ not in", values, "fpsj");
			return (Criteria) this;
		}

		public Criteria andFpsjBetween(String value1, String value2) {
			addCriterion("FPSJ between", value1, value2, "fpsj");
			return (Criteria) this;
		}

		public Criteria andFpsjNotBetween(String value1, String value2) {
			addCriterion("FPSJ not between", value1, value2, "fpsj");
			return (Criteria) this;
		}

		public Criteria andSjkssjIsNull() {
			addCriterion("SJKSSJ is null");
			return (Criteria) this;
		}

		public Criteria andSjkssjIsNotNull() {
			addCriterion("SJKSSJ is not null");
			return (Criteria) this;
		}

		public Criteria andSjkssjEqualTo(String value) {
			addCriterion("SJKSSJ =", value, "sjkssj");
			return (Criteria) this;
		}

		public Criteria andSjkssjNotEqualTo(String value) {
			addCriterion("SJKSSJ <>", value, "sjkssj");
			return (Criteria) this;
		}

		public Criteria andSjkssjGreaterThan(String value) {
			addCriterion("SJKSSJ >", value, "sjkssj");
			return (Criteria) this;
		}

		public Criteria andSjkssjGreaterThanOrEqualTo(String value) {
			addCriterion("SJKSSJ >=", value, "sjkssj");
			return (Criteria) this;
		}

		public Criteria andSjkssjLessThan(String value) {
			addCriterion("SJKSSJ <", value, "sjkssj");
			return (Criteria) this;
		}

		public Criteria andSjkssjLessThanOrEqualTo(String value) {
			addCriterion("SJKSSJ <=", value, "sjkssj");
			return (Criteria) this;
		}

		public Criteria andSjkssjLike(String value) {
			addCriterion("SJKSSJ like", value, "sjkssj");
			return (Criteria) this;
		}

		public Criteria andSjkssjNotLike(String value) {
			addCriterion("SJKSSJ not like", value, "sjkssj");
			return (Criteria) this;
		}

		public Criteria andSjkssjIn(List<String> values) {
			addCriterion("SJKSSJ in", values, "sjkssj");
			return (Criteria) this;
		}

		public Criteria andSjkssjNotIn(List<String> values) {
			addCriterion("SJKSSJ not in", values, "sjkssj");
			return (Criteria) this;
		}

		public Criteria andSjkssjBetween(String value1, String value2) {
			addCriterion("SJKSSJ between", value1, value2, "sjkssj");
			return (Criteria) this;
		}

		public Criteria andSjkssjNotBetween(String value1, String value2) {
			addCriterion("SJKSSJ not between", value1, value2, "sjkssj");
			return (Criteria) this;
		}

		public Criteria andSjjssjIsNull() {
			addCriterion("SJJSSJ is null");
			return (Criteria) this;
		}

		public Criteria andSjjssjIsNotNull() {
			addCriterion("SJJSSJ is not null");
			return (Criteria) this;
		}

		public Criteria andSjjssjEqualTo(String value) {
			addCriterion("SJJSSJ =", value, "sjjssj");
			return (Criteria) this;
		}

		public Criteria andSjjssjNotEqualTo(String value) {
			addCriterion("SJJSSJ <>", value, "sjjssj");
			return (Criteria) this;
		}

		public Criteria andSjjssjGreaterThan(String value) {
			addCriterion("SJJSSJ >", value, "sjjssj");
			return (Criteria) this;
		}

		public Criteria andSjjssjGreaterThanOrEqualTo(String value) {
			addCriterion("SJJSSJ >=", value, "sjjssj");
			return (Criteria) this;
		}

		public Criteria andSjjssjLessThan(String value) {
			addCriterion("SJJSSJ <", value, "sjjssj");
			return (Criteria) this;
		}

		public Criteria andSjjssjLessThanOrEqualTo(String value) {
			addCriterion("SJJSSJ <=", value, "sjjssj");
			return (Criteria) this;
		}

		public Criteria andSjjssjLike(String value) {
			addCriterion("SJJSSJ like", value, "sjjssj");
			return (Criteria) this;
		}

		public Criteria andSjjssjNotLike(String value) {
			addCriterion("SJJSSJ not like", value, "sjjssj");
			return (Criteria) this;
		}

		public Criteria andSjjssjIn(List<String> values) {
			addCriterion("SJJSSJ in", values, "sjjssj");
			return (Criteria) this;
		}

		public Criteria andSjjssjNotIn(List<String> values) {
			addCriterion("SJJSSJ not in", values, "sjjssj");
			return (Criteria) this;
		}

		public Criteria andSjjssjBetween(String value1, String value2) {
			addCriterion("SJJSSJ between", value1, value2, "sjjssj");
			return (Criteria) this;
		}

		public Criteria andSjjssjNotBetween(String value1, String value2) {
			addCriterion("SJJSSJ not between", value1, value2, "sjjssj");
			return (Criteria) this;
		}

		public Criteria andYwcbfbIsNull() {
			addCriterion("YWCBFB is null");
			return (Criteria) this;
		}

		public Criteria andYwcbfbIsNotNull() {
			addCriterion("YWCBFB is not null");
			return (Criteria) this;
		}

		public Criteria andYwcbfbEqualTo(BigDecimal value) {
			addCriterion("YWCBFB =", value, "ywcbfb");
			return (Criteria) this;
		}

		public Criteria andYwcbfbNotEqualTo(BigDecimal value) {
			addCriterion("YWCBFB <>", value, "ywcbfb");
			return (Criteria) this;
		}

		public Criteria andYwcbfbGreaterThan(BigDecimal value) {
			addCriterion("YWCBFB >", value, "ywcbfb");
			return (Criteria) this;
		}

		public Criteria andYwcbfbGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("YWCBFB >=", value, "ywcbfb");
			return (Criteria) this;
		}

		public Criteria andYwcbfbLessThan(BigDecimal value) {
			addCriterion("YWCBFB <", value, "ywcbfb");
			return (Criteria) this;
		}

		public Criteria andYwcbfbLessThanOrEqualTo(BigDecimal value) {
			addCriterion("YWCBFB <=", value, "ywcbfb");
			return (Criteria) this;
		}

		public Criteria andYwcbfbIn(List<BigDecimal> values) {
			addCriterion("YWCBFB in", values, "ywcbfb");
			return (Criteria) this;
		}

		public Criteria andYwcbfbNotIn(List<BigDecimal> values) {
			addCriterion("YWCBFB not in", values, "ywcbfb");
			return (Criteria) this;
		}

		public Criteria andYwcbfbBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("YWCBFB between", value1, value2, "ywcbfb");
			return (Criteria) this;
		}

		public Criteria andYwcbfbNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("YWCBFB not between", value1, value2, "ywcbfb");
			return (Criteria) this;
		}

		public Criteria andDqztIsNull() {
			addCriterion("DQZT is null");
			return (Criteria) this;
		}

		public Criteria andDqztIsNotNull() {
			addCriterion("DQZT is not null");
			return (Criteria) this;
		}

		public Criteria andDqztEqualTo(BigDecimal value) {
			addCriterion("DQZT =", value, "dqzt");
			return (Criteria) this;
		}

		public Criteria andDqztNotEqualTo(BigDecimal value) {
			addCriterion("DQZT <>", value, "dqzt");
			return (Criteria) this;
		}

		public Criteria andDqztGreaterThan(BigDecimal value) {
			addCriterion("DQZT >", value, "dqzt");
			return (Criteria) this;
		}

		public Criteria andDqztGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("DQZT >=", value, "dqzt");
			return (Criteria) this;
		}

		public Criteria andDqztLessThan(BigDecimal value) {
			addCriterion("DQZT <", value, "dqzt");
			return (Criteria) this;
		}

		public Criteria andDqztLessThanOrEqualTo(BigDecimal value) {
			addCriterion("DQZT <=", value, "dqzt");
			return (Criteria) this;
		}

		public Criteria andDqztIn(List<BigDecimal> values) {
			addCriterion("DQZT in", values, "dqzt");
			return (Criteria) this;
		}

		public Criteria andDqztNotIn(List<BigDecimal> values) {
			addCriterion("DQZT not in", values, "dqzt");
			return (Criteria) this;
		}

		public Criteria andDqztBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("DQZT between", value1, value2, "dqzt");
			return (Criteria) this;
		}

		public Criteria andDqztNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("DQZT not between", value1, value2, "dqzt");
			return (Criteria) this;
		}

		public Criteria andKffyIsNull() {
			addCriterion("KFFY is null");
			return (Criteria) this;
		}

		public Criteria andKffyIsNotNull() {
			addCriterion("KFFY is not null");
			return (Criteria) this;
		}

		public Criteria andKffyEqualTo(Double value) {
			addCriterion("KFFY =", value, "kffy");
			return (Criteria) this;
		}

		public Criteria andKffyNotEqualTo(Double value) {
			addCriterion("KFFY <>", value, "kffy");
			return (Criteria) this;
		}

		public Criteria andKffyGreaterThan(Double value) {
			addCriterion("KFFY >", value, "kffy");
			return (Criteria) this;
		}

		public Criteria andKffyGreaterThanOrEqualTo(Double value) {
			addCriterion("KFFY >=", value, "kffy");
			return (Criteria) this;
		}

		public Criteria andKffyLessThan(Double value) {
			addCriterion("KFFY <", value, "kffy");
			return (Criteria) this;
		}

		public Criteria andKffyLessThanOrEqualTo(Double value) {
			addCriterion("KFFY <=", value, "kffy");
			return (Criteria) this;
		}

		public Criteria andKffyIn(List<Double> values) {
			addCriterion("KFFY in", values, "kffy");
			return (Criteria) this;
		}

		public Criteria andKffyNotIn(List<Double> values) {
			addCriterion("KFFY not in", values, "kffy");
			return (Criteria) this;
		}

		public Criteria andKffyBetween(Double value1, Double value2) {
			addCriterion("KFFY between", value1, value2, "kffy");
			return (Criteria) this;
		}

		public Criteria andKffyNotBetween(Double value1, Double value2) {
			addCriterion("KFFY not between", value1, value2, "kffy");
			return (Criteria) this;
		}

		public Criteria andCjridIsNull() {
			addCriterion("CJRID is null");
			return (Criteria) this;
		}

		public Criteria andCjridIsNotNull() {
			addCriterion("CJRID is not null");
			return (Criteria) this;
		}

		public Criteria andCjridEqualTo(String value) {
			addCriterion("CJRID =", value, "cjrid");
			return (Criteria) this;
		}

		public Criteria andCjridNotEqualTo(String value) {
			addCriterion("CJRID <>", value, "cjrid");
			return (Criteria) this;
		}

		public Criteria andCjridGreaterThan(String value) {
			addCriterion("CJRID >", value, "cjrid");
			return (Criteria) this;
		}

		public Criteria andCjridGreaterThanOrEqualTo(String value) {
			addCriterion("CJRID >=", value, "cjrid");
			return (Criteria) this;
		}

		public Criteria andCjridLessThan(String value) {
			addCriterion("CJRID <", value, "cjrid");
			return (Criteria) this;
		}

		public Criteria andCjridLessThanOrEqualTo(String value) {
			addCriterion("CJRID <=", value, "cjrid");
			return (Criteria) this;
		}

		public Criteria andCjridLike(String value) {
			addCriterion("CJRID like", value, "cjrid");
			return (Criteria) this;
		}

		public Criteria andCjridNotLike(String value) {
			addCriterion("CJRID not like", value, "cjrid");
			return (Criteria) this;
		}

		public Criteria andCjridIn(List<String> values) {
			addCriterion("CJRID in", values, "cjrid");
			return (Criteria) this;
		}

		public Criteria andCjridNotIn(List<String> values) {
			addCriterion("CJRID not in", values, "cjrid");
			return (Criteria) this;
		}

		public Criteria andCjridBetween(String value1, String value2) {
			addCriterion("CJRID between", value1, value2, "cjrid");
			return (Criteria) this;
		}

		public Criteria andCjridNotBetween(String value1, String value2) {
			addCriterion("CJRID not between", value1, value2, "cjrid");
			return (Criteria) this;
		}

		public Criteria andCjrmcIsNull() {
			addCriterion("CJRMC is null");
			return (Criteria) this;
		}

		public Criteria andCjrmcIsNotNull() {
			addCriterion("CJRMC is not null");
			return (Criteria) this;
		}

		public Criteria andCjrmcEqualTo(String value) {
			addCriterion("CJRMC =", value, "cjrmc");
			return (Criteria) this;
		}

		public Criteria andCjrmcNotEqualTo(String value) {
			addCriterion("CJRMC <>", value, "cjrmc");
			return (Criteria) this;
		}

		public Criteria andCjrmcGreaterThan(String value) {
			addCriterion("CJRMC >", value, "cjrmc");
			return (Criteria) this;
		}

		public Criteria andCjrmcGreaterThanOrEqualTo(String value) {
			addCriterion("CJRMC >=", value, "cjrmc");
			return (Criteria) this;
		}

		public Criteria andCjrmcLessThan(String value) {
			addCriterion("CJRMC <", value, "cjrmc");
			return (Criteria) this;
		}

		public Criteria andCjrmcLessThanOrEqualTo(String value) {
			addCriterion("CJRMC <=", value, "cjrmc");
			return (Criteria) this;
		}

		public Criteria andCjrmcLike(String value) {
			addCriterion("CJRMC like", value, "cjrmc");
			return (Criteria) this;
		}

		public Criteria andCjrmcNotLike(String value) {
			addCriterion("CJRMC not like", value, "cjrmc");
			return (Criteria) this;
		}

		public Criteria andCjrmcIn(List<String> values) {
			addCriterion("CJRMC in", values, "cjrmc");
			return (Criteria) this;
		}

		public Criteria andCjrmcNotIn(List<String> values) {
			addCriterion("CJRMC not in", values, "cjrmc");
			return (Criteria) this;
		}

		public Criteria andCjrmcBetween(String value1, String value2) {
			addCriterion("CJRMC between", value1, value2, "cjrmc");
			return (Criteria) this;
		}

		public Criteria andCjrmcNotBetween(String value1, String value2) {
			addCriterion("CJRMC not between", value1, value2, "cjrmc");
			return (Criteria) this;
		}

		public Criteria andCjsjIsNull() {
			addCriterion("CJSJ is null");
			return (Criteria) this;
		}

		public Criteria andCjsjIsNotNull() {
			addCriterion("CJSJ is not null");
			return (Criteria) this;
		}

		public Criteria andCjsjEqualTo(String value) {
			addCriterion("CJSJ =", value, "cjsj");
			return (Criteria) this;
		}

		public Criteria andCjsjNotEqualTo(String value) {
			addCriterion("CJSJ <>", value, "cjsj");
			return (Criteria) this;
		}

		public Criteria andCjsjGreaterThan(String value) {
			addCriterion("CJSJ >", value, "cjsj");
			return (Criteria) this;
		}

		public Criteria andCjsjGreaterThanOrEqualTo(String value) {
			addCriterion("CJSJ >=", value, "cjsj");
			return (Criteria) this;
		}

		public Criteria andCjsjLessThan(String value) {
			addCriterion("CJSJ <", value, "cjsj");
			return (Criteria) this;
		}

		public Criteria andCjsjLessThanOrEqualTo(String value) {
			addCriterion("CJSJ <=", value, "cjsj");
			return (Criteria) this;
		}

		public Criteria andCjsjLike(String value) {
			addCriterion("CJSJ like", value, "cjsj");
			return (Criteria) this;
		}

		public Criteria andCjsjNotLike(String value) {
			addCriterion("CJSJ not like", value, "cjsj");
			return (Criteria) this;
		}

		public Criteria andCjsjIn(List<String> values) {
			addCriterion("CJSJ in", values, "cjsj");
			return (Criteria) this;
		}

		public Criteria andCjsjNotIn(List<String> values) {
			addCriterion("CJSJ not in", values, "cjsj");
			return (Criteria) this;
		}

		public Criteria andCjsjBetween(String value1, String value2) {
			addCriterion("CJSJ between", value1, value2, "cjsj");
			return (Criteria) this;
		}

		public Criteria andCjsjNotBetween(String value1, String value2) {
			addCriterion("CJSJ not between", value1, value2, "cjsj");
			return (Criteria) this;
		}

		public Criteria andTcsjIsNull() {
			addCriterion("TCSJ is null");
			return (Criteria) this;
		}

		public Criteria andTcsjIsNotNull() {
			addCriterion("TCSJ is not null");
			return (Criteria) this;
		}

		public Criteria andTcsjEqualTo(String value) {
			addCriterion("TCSJ =", value, "tcsj");
			return (Criteria) this;
		}

		public Criteria andTcsjNotEqualTo(String value) {
			addCriterion("TCSJ <>", value, "tcsj");
			return (Criteria) this;
		}

		public Criteria andTcsjGreaterThan(String value) {
			addCriterion("TCSJ >", value, "tcsj");
			return (Criteria) this;
		}

		public Criteria andTcsjGreaterThanOrEqualTo(String value) {
			addCriterion("TCSJ >=", value, "tcsj");
			return (Criteria) this;
		}

		public Criteria andTcsjLessThan(String value) {
			addCriterion("TCSJ <", value, "tcsj");
			return (Criteria) this;
		}

		public Criteria andTcsjLessThanOrEqualTo(String value) {
			addCriterion("TCSJ <=", value, "tcsj");
			return (Criteria) this;
		}

		public Criteria andTcsjLike(String value) {
			addCriterion("TCSJ like", value, "tcsj");
			return (Criteria) this;
		}

		public Criteria andTcsjNotLike(String value) {
			addCriterion("TCSJ not like", value, "tcsj");
			return (Criteria) this;
		}

		public Criteria andTcsjIn(List<String> values) {
			addCriterion("TCSJ in", values, "tcsj");
			return (Criteria) this;
		}

		public Criteria andTcsjNotIn(List<String> values) {
			addCriterion("TCSJ not in", values, "tcsj");
			return (Criteria) this;
		}

		public Criteria andTcsjBetween(String value1, String value2) {
			addCriterion("TCSJ between", value1, value2, "tcsj");
			return (Criteria) this;
		}

		public Criteria andTcsjNotBetween(String value1, String value2) {
			addCriterion("TCSJ not between", value1, value2, "tcsj");
			return (Criteria) this;
		}

		public Criteria andShridIsNull() {
			addCriterion("SHRID is null");
			return (Criteria) this;
		}

		public Criteria andShridIsNotNull() {
			addCriterion("SHRID is not null");
			return (Criteria) this;
		}

		public Criteria andShridEqualTo(String value) {
			addCriterion("SHRID =", value, "shrid");
			return (Criteria) this;
		}

		public Criteria andShridNotEqualTo(String value) {
			addCriterion("SHRID <>", value, "shrid");
			return (Criteria) this;
		}

		public Criteria andShridGreaterThan(String value) {
			addCriterion("SHRID >", value, "shrid");
			return (Criteria) this;
		}

		public Criteria andShridGreaterThanOrEqualTo(String value) {
			addCriterion("SHRID >=", value, "shrid");
			return (Criteria) this;
		}

		public Criteria andShridLessThan(String value) {
			addCriterion("SHRID <", value, "shrid");
			return (Criteria) this;
		}

		public Criteria andShridLessThanOrEqualTo(String value) {
			addCriterion("SHRID <=", value, "shrid");
			return (Criteria) this;
		}

		public Criteria andShridLike(String value) {
			addCriterion("SHRID like", value, "shrid");
			return (Criteria) this;
		}

		public Criteria andShridNotLike(String value) {
			addCriterion("SHRID not like", value, "shrid");
			return (Criteria) this;
		}

		public Criteria andShridIn(List<String> values) {
			addCriterion("SHRID in", values, "shrid");
			return (Criteria) this;
		}

		public Criteria andShridNotIn(List<String> values) {
			addCriterion("SHRID not in", values, "shrid");
			return (Criteria) this;
		}

		public Criteria andShridBetween(String value1, String value2) {
			addCriterion("SHRID between", value1, value2, "shrid");
			return (Criteria) this;
		}

		public Criteria andShridNotBetween(String value1, String value2) {
			addCriterion("SHRID not between", value1, value2, "shrid");
			return (Criteria) this;
		}

		public Criteria andShrIsNull() {
			addCriterion("SHR is null");
			return (Criteria) this;
		}

		public Criteria andShrIsNotNull() {
			addCriterion("SHR is not null");
			return (Criteria) this;
		}

		public Criteria andShrEqualTo(String value) {
			addCriterion("SHR =", value, "shr");
			return (Criteria) this;
		}

		public Criteria andShrNotEqualTo(String value) {
			addCriterion("SHR <>", value, "shr");
			return (Criteria) this;
		}

		public Criteria andShrGreaterThan(String value) {
			addCriterion("SHR >", value, "shr");
			return (Criteria) this;
		}

		public Criteria andShrGreaterThanOrEqualTo(String value) {
			addCriterion("SHR >=", value, "shr");
			return (Criteria) this;
		}

		public Criteria andShrLessThan(String value) {
			addCriterion("SHR <", value, "shr");
			return (Criteria) this;
		}

		public Criteria andShrLessThanOrEqualTo(String value) {
			addCriterion("SHR <=", value, "shr");
			return (Criteria) this;
		}

		public Criteria andShrLike(String value) {
			addCriterion("SHR like", value, "shr");
			return (Criteria) this;
		}

		public Criteria andShrNotLike(String value) {
			addCriterion("SHR not like", value, "shr");
			return (Criteria) this;
		}

		public Criteria andShrIn(List<String> values) {
			addCriterion("SHR in", values, "shr");
			return (Criteria) this;
		}

		public Criteria andShrNotIn(List<String> values) {
			addCriterion("SHR not in", values, "shr");
			return (Criteria) this;
		}

		public Criteria andShrBetween(String value1, String value2) {
			addCriterion("SHR between", value1, value2, "shr");
			return (Criteria) this;
		}

		public Criteria andShrNotBetween(String value1, String value2) {
			addCriterion("SHR not between", value1, value2, "shr");
			return (Criteria) this;
		}

		public Criteria andShyjIsNull() {
			addCriterion("SHYJ is null");
			return (Criteria) this;
		}

		public Criteria andShyjIsNotNull() {
			addCriterion("SHYJ is not null");
			return (Criteria) this;
		}

		public Criteria andShyjEqualTo(String value) {
			addCriterion("SHYJ =", value, "shyj");
			return (Criteria) this;
		}

		public Criteria andShyjNotEqualTo(String value) {
			addCriterion("SHYJ <>", value, "shyj");
			return (Criteria) this;
		}

		public Criteria andShyjGreaterThan(String value) {
			addCriterion("SHYJ >", value, "shyj");
			return (Criteria) this;
		}

		public Criteria andShyjGreaterThanOrEqualTo(String value) {
			addCriterion("SHYJ >=", value, "shyj");
			return (Criteria) this;
		}

		public Criteria andShyjLessThan(String value) {
			addCriterion("SHYJ <", value, "shyj");
			return (Criteria) this;
		}

		public Criteria andShyjLessThanOrEqualTo(String value) {
			addCriterion("SHYJ <=", value, "shyj");
			return (Criteria) this;
		}

		public Criteria andShyjLike(String value) {
			addCriterion("SHYJ like", value, "shyj");
			return (Criteria) this;
		}

		public Criteria andShyjNotLike(String value) {
			addCriterion("SHYJ not like", value, "shyj");
			return (Criteria) this;
		}

		public Criteria andShyjIn(List<String> values) {
			addCriterion("SHYJ in", values, "shyj");
			return (Criteria) this;
		}

		public Criteria andShyjNotIn(List<String> values) {
			addCriterion("SHYJ not in", values, "shyj");
			return (Criteria) this;
		}

		public Criteria andShyjBetween(String value1, String value2) {
			addCriterion("SHYJ between", value1, value2, "shyj");
			return (Criteria) this;
		}

		public Criteria andShyjNotBetween(String value1, String value2) {
			addCriterion("SHYJ not between", value1, value2, "shyj");
			return (Criteria) this;
		}

		public Criteria andShsjIsNull() {
			addCriterion("SHSJ is null");
			return (Criteria) this;
		}

		public Criteria andShsjIsNotNull() {
			addCriterion("SHSJ is not null");
			return (Criteria) this;
		}

		public Criteria andShsjEqualTo(String value) {
			addCriterion("SHSJ =", value, "shsj");
			return (Criteria) this;
		}

		public Criteria andShsjNotEqualTo(String value) {
			addCriterion("SHSJ <>", value, "shsj");
			return (Criteria) this;
		}

		public Criteria andShsjGreaterThan(String value) {
			addCriterion("SHSJ >", value, "shsj");
			return (Criteria) this;
		}

		public Criteria andShsjGreaterThanOrEqualTo(String value) {
			addCriterion("SHSJ >=", value, "shsj");
			return (Criteria) this;
		}

		public Criteria andShsjLessThan(String value) {
			addCriterion("SHSJ <", value, "shsj");
			return (Criteria) this;
		}

		public Criteria andShsjLessThanOrEqualTo(String value) {
			addCriterion("SHSJ <=", value, "shsj");
			return (Criteria) this;
		}

		public Criteria andShsjLike(String value) {
			addCriterion("SHSJ like", value, "shsj");
			return (Criteria) this;
		}

		public Criteria andShsjNotLike(String value) {
			addCriterion("SHSJ not like", value, "shsj");
			return (Criteria) this;
		}

		public Criteria andShsjIn(List<String> values) {
			addCriterion("SHSJ in", values, "shsj");
			return (Criteria) this;
		}

		public Criteria andShsjNotIn(List<String> values) {
			addCriterion("SHSJ not in", values, "shsj");
			return (Criteria) this;
		}

		public Criteria andShsjBetween(String value1, String value2) {
			addCriterion("SHSJ between", value1, value2, "shsj");
			return (Criteria) this;
		}

		public Criteria andShsjNotBetween(String value1, String value2) {
			addCriterion("SHSJ not between", value1, value2, "shsj");
			return (Criteria) this;
		}

		public Criteria andGdztIsNull() {
			addCriterion("GDZT is null");
			return (Criteria) this;
		}

		public Criteria andGdztIsNotNull() {
			addCriterion("GDZT is not null");
			return (Criteria) this;
		}

		public Criteria andGdztEqualTo(String value) {
			addCriterion("GDZT =", value, "gdzt");
			return (Criteria) this;
		}

		public Criteria andGdztNotEqualTo(String value) {
			addCriterion("GDZT <>", value, "gdzt");
			return (Criteria) this;
		}

		public Criteria andGdztGreaterThan(String value) {
			addCriterion("GDZT >", value, "gdzt");
			return (Criteria) this;
		}

		public Criteria andGdztGreaterThanOrEqualTo(String value) {
			addCriterion("GDZT >=", value, "gdzt");
			return (Criteria) this;
		}

		public Criteria andGdztLessThan(String value) {
			addCriterion("GDZT <", value, "gdzt");
			return (Criteria) this;
		}

		public Criteria andGdztLessThanOrEqualTo(String value) {
			addCriterion("GDZT <=", value, "gdzt");
			return (Criteria) this;
		}

		public Criteria andGdztLike(String value) {
			addCriterion("GDZT like", value, "gdzt");
			return (Criteria) this;
		}

		public Criteria andGdztNotLike(String value) {
			addCriterion("GDZT not like", value, "gdzt");
			return (Criteria) this;
		}

		public Criteria andGdztIn(List<String> values) {
			addCriterion("GDZT in", values, "gdzt");
			return (Criteria) this;
		}

		public Criteria andGdztNotIn(List<String> values) {
			addCriterion("GDZT not in", values, "gdzt");
			return (Criteria) this;
		}

		public Criteria andGdztBetween(String value1, String value2) {
			addCriterion("GDZT between", value1, value2, "gdzt");
			return (Criteria) this;
		}

		public Criteria andGdztNotBetween(String value1, String value2) {
			addCriterion("GDZT not between", value1, value2, "gdzt");
			return (Criteria) this;
		}

		public Criteria andZzidIsNull() {
			addCriterion("ZZID is null");
			return (Criteria) this;
		}

		public Criteria andZzidIsNotNull() {
			addCriterion("ZZID is not null");
			return (Criteria) this;
		}

		public Criteria andZzidEqualTo(String value) {
			addCriterion("ZZID =", value, "zzid");
			return (Criteria) this;
		}

		public Criteria andZzidNotEqualTo(String value) {
			addCriterion("ZZID <>", value, "zzid");
			return (Criteria) this;
		}

		public Criteria andZzidGreaterThan(String value) {
			addCriterion("ZZID >", value, "zzid");
			return (Criteria) this;
		}

		public Criteria andZzidGreaterThanOrEqualTo(String value) {
			addCriterion("ZZID >=", value, "zzid");
			return (Criteria) this;
		}

		public Criteria andZzidLessThan(String value) {
			addCriterion("ZZID <", value, "zzid");
			return (Criteria) this;
		}

		public Criteria andZzidLessThanOrEqualTo(String value) {
			addCriterion("ZZID <=", value, "zzid");
			return (Criteria) this;
		}

		public Criteria andZzidLike(String value) {
			addCriterion("ZZID like", value, "zzid");
			return (Criteria) this;
		}

		public Criteria andZzidNotLike(String value) {
			addCriterion("ZZID not like", value, "zzid");
			return (Criteria) this;
		}

		public Criteria andZzidIn(List<String> values) {
			addCriterion("ZZID in", values, "zzid");
			return (Criteria) this;
		}

		public Criteria andZzidNotIn(List<String> values) {
			addCriterion("ZZID not in", values, "zzid");
			return (Criteria) this;
		}

		public Criteria andZzidBetween(String value1, String value2) {
			addCriterion("ZZID between", value1, value2, "zzid");
			return (Criteria) this;
		}

		public Criteria andZzidNotBetween(String value1, String value2) {
			addCriterion("ZZID not between", value1, value2, "zzid");
			return (Criteria) this;
		}

		public Criteria andXqbbhIsNull() {
			addCriterion("XQBBH is null");
			return (Criteria) this;
		}

		public Criteria andXqbbhIsNotNull() {
			addCriterion("XQBBH is not null");
			return (Criteria) this;
		}

		public Criteria andXqbbhEqualTo(String value) {
			addCriterion("XQBBH =", value, "xqbbh");
			return (Criteria) this;
		}

		public Criteria andXqbbhNotEqualTo(String value) {
			addCriterion("XQBBH <>", value, "xqbbh");
			return (Criteria) this;
		}

		public Criteria andXqbbhGreaterThan(String value) {
			addCriterion("XQBBH >", value, "xqbbh");
			return (Criteria) this;
		}

		public Criteria andXqbbhGreaterThanOrEqualTo(String value) {
			addCriterion("XQBBH >=", value, "xqbbh");
			return (Criteria) this;
		}

		public Criteria andXqbbhLessThan(String value) {
			addCriterion("XQBBH <", value, "xqbbh");
			return (Criteria) this;
		}

		public Criteria andXqbbhLessThanOrEqualTo(String value) {
			addCriterion("XQBBH <=", value, "xqbbh");
			return (Criteria) this;
		}

		public Criteria andXqbbhLike(String value) {
			addCriterion("XQBBH like", value, "xqbbh");
			return (Criteria) this;
		}

		public Criteria andXqbbhNotLike(String value) {
			addCriterion("XQBBH not like", value, "xqbbh");
			return (Criteria) this;
		}

		public Criteria andXqbbhIn(List<String> values) {
			addCriterion("XQBBH in", values, "xqbbh");
			return (Criteria) this;
		}

		public Criteria andXqbbhNotIn(List<String> values) {
			addCriterion("XQBBH not in", values, "xqbbh");
			return (Criteria) this;
		}

		public Criteria andXqbbhBetween(String value1, String value2) {
			addCriterion("XQBBH between", value1, value2, "xqbbh");
			return (Criteria) this;
		}

		public Criteria andXqbbhNotBetween(String value1, String value2) {
			addCriterion("XQBBH not between", value1, value2, "xqbbh");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table NWIDP.IMP_KFD_KFDXX
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NWIDP.IMP_KFD_KFDXX
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}