package com.yfny.corepojo.entity.demandform.model;

import java.util.ArrayList;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NWIDP.EDT_YH_YYGC
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NWIDP.EDT_YH_YYGC
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NWIDP.EDT_YH_YYGC
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.EDT_YH_YYGC
     *
     * @mbggenerated
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.EDT_YH_YYGC
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.EDT_YH_YYGC
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.EDT_YH_YYGC
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.EDT_YH_YYGC
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.EDT_YH_YYGC
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.EDT_YH_YYGC
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.EDT_YH_YYGC
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.EDT_YH_YYGC
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.EDT_YH_YYGC
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.EDT_YH_YYGC
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NWIDP.EDT_YH_YYGC
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andYhIdIsNull() {
            addCriterion("YH_ID is null");
            return (Criteria) this;
        }

        public Criteria andYhIdIsNotNull() {
            addCriterion("YH_ID is not null");
            return (Criteria) this;
        }

        public Criteria andYhIdEqualTo(String value) {
            addCriterion("YH_ID =", value, "yhId");
            return (Criteria) this;
        }

        public Criteria andYhIdNotEqualTo(String value) {
            addCriterion("YH_ID <>", value, "yhId");
            return (Criteria) this;
        }

        public Criteria andYhIdGreaterThan(String value) {
            addCriterion("YH_ID >", value, "yhId");
            return (Criteria) this;
        }

        public Criteria andYhIdGreaterThanOrEqualTo(String value) {
            addCriterion("YH_ID >=", value, "yhId");
            return (Criteria) this;
        }

        public Criteria andYhIdLessThan(String value) {
            addCriterion("YH_ID <", value, "yhId");
            return (Criteria) this;
        }

        public Criteria andYhIdLessThanOrEqualTo(String value) {
            addCriterion("YH_ID <=", value, "yhId");
            return (Criteria) this;
        }

        public Criteria andYhIdLike(String value) {
            addCriterion("YH_ID like", value, "yhId");
            return (Criteria) this;
        }

        public Criteria andYhIdNotLike(String value) {
            addCriterion("YH_ID not like", value, "yhId");
            return (Criteria) this;
        }

        public Criteria andYhIdIn(List<String> values) {
            addCriterion("YH_ID in", values, "yhId");
            return (Criteria) this;
        }

        public Criteria andYhIdNotIn(List<String> values) {
            addCriterion("YH_ID not in", values, "yhId");
            return (Criteria) this;
        }

        public Criteria andYhIdBetween(String value1, String value2) {
            addCriterion("YH_ID between", value1, value2, "yhId");
            return (Criteria) this;
        }

        public Criteria andYhIdNotBetween(String value1, String value2) {
            addCriterion("YH_ID not between", value1, value2, "yhId");
            return (Criteria) this;
        }

        public Criteria andYygcIdIsNull() {
            addCriterion("YYGC_ID is null");
            return (Criteria) this;
        }

        public Criteria andYygcIdIsNotNull() {
            addCriterion("YYGC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andYygcIdEqualTo(String value) {
            addCriterion("YYGC_ID =", value, "yygcId");
            return (Criteria) this;
        }

        public Criteria andYygcIdNotEqualTo(String value) {
            addCriterion("YYGC_ID <>", value, "yygcId");
            return (Criteria) this;
        }

        public Criteria andYygcIdGreaterThan(String value) {
            addCriterion("YYGC_ID >", value, "yygcId");
            return (Criteria) this;
        }

        public Criteria andYygcIdGreaterThanOrEqualTo(String value) {
            addCriterion("YYGC_ID >=", value, "yygcId");
            return (Criteria) this;
        }

        public Criteria andYygcIdLessThan(String value) {
            addCriterion("YYGC_ID <", value, "yygcId");
            return (Criteria) this;
        }

        public Criteria andYygcIdLessThanOrEqualTo(String value) {
            addCriterion("YYGC_ID <=", value, "yygcId");
            return (Criteria) this;
        }

        public Criteria andYygcIdLike(String value) {
            addCriterion("YYGC_ID like", value, "yygcId");
            return (Criteria) this;
        }

        public Criteria andYygcIdNotLike(String value) {
            addCriterion("YYGC_ID not like", value, "yygcId");
            return (Criteria) this;
        }

        public Criteria andYygcIdIn(List<String> values) {
            addCriterion("YYGC_ID in", values, "yygcId");
            return (Criteria) this;
        }

        public Criteria andYygcIdNotIn(List<String> values) {
            addCriterion("YYGC_ID not in", values, "yygcId");
            return (Criteria) this;
        }

        public Criteria andYygcIdBetween(String value1, String value2) {
            addCriterion("YYGC_ID between", value1, value2, "yygcId");
            return (Criteria) this;
        }

        public Criteria andYygcIdNotBetween(String value1, String value2) {
            addCriterion("YYGC_ID not between", value1, value2, "yygcId");
            return (Criteria) this;
        }

        public Criteria andYhmIsNull() {
            addCriterion("YHM is null");
            return (Criteria) this;
        }

        public Criteria andYhmIsNotNull() {
            addCriterion("YHM is not null");
            return (Criteria) this;
        }

        public Criteria andYhmEqualTo(String value) {
            addCriterion("YHM =", value, "yhm");
            return (Criteria) this;
        }

        public Criteria andYhmNotEqualTo(String value) {
            addCriterion("YHM <>", value, "yhm");
            return (Criteria) this;
        }

        public Criteria andYhmGreaterThan(String value) {
            addCriterion("YHM >", value, "yhm");
            return (Criteria) this;
        }

        public Criteria andYhmGreaterThanOrEqualTo(String value) {
            addCriterion("YHM >=", value, "yhm");
            return (Criteria) this;
        }

        public Criteria andYhmLessThan(String value) {
            addCriterion("YHM <", value, "yhm");
            return (Criteria) this;
        }

        public Criteria andYhmLessThanOrEqualTo(String value) {
            addCriterion("YHM <=", value, "yhm");
            return (Criteria) this;
        }

        public Criteria andYhmLike(String value) {
            addCriterion("YHM like", value, "yhm");
            return (Criteria) this;
        }

        public Criteria andYhmNotLike(String value) {
            addCriterion("YHM not like", value, "yhm");
            return (Criteria) this;
        }

        public Criteria andYhmIn(List<String> values) {
            addCriterion("YHM in", values, "yhm");
            return (Criteria) this;
        }

        public Criteria andYhmNotIn(List<String> values) {
            addCriterion("YHM not in", values, "yhm");
            return (Criteria) this;
        }

        public Criteria andYhmBetween(String value1, String value2) {
            addCriterion("YHM between", value1, value2, "yhm");
            return (Criteria) this;
        }

        public Criteria andYhmNotBetween(String value1, String value2) {
            addCriterion("YHM not between", value1, value2, "yhm");
            return (Criteria) this;
        }

        public Criteria andMmIsNull() {
            addCriterion("MM is null");
            return (Criteria) this;
        }

        public Criteria andMmIsNotNull() {
            addCriterion("MM is not null");
            return (Criteria) this;
        }

        public Criteria andMmEqualTo(String value) {
            addCriterion("MM =", value, "mm");
            return (Criteria) this;
        }

        public Criteria andMmNotEqualTo(String value) {
            addCriterion("MM <>", value, "mm");
            return (Criteria) this;
        }

        public Criteria andMmGreaterThan(String value) {
            addCriterion("MM >", value, "mm");
            return (Criteria) this;
        }

        public Criteria andMmGreaterThanOrEqualTo(String value) {
            addCriterion("MM >=", value, "mm");
            return (Criteria) this;
        }

        public Criteria andMmLessThan(String value) {
            addCriterion("MM <", value, "mm");
            return (Criteria) this;
        }

        public Criteria andMmLessThanOrEqualTo(String value) {
            addCriterion("MM <=", value, "mm");
            return (Criteria) this;
        }

        public Criteria andMmLike(String value) {
            addCriterion("MM like", value, "mm");
            return (Criteria) this;
        }

        public Criteria andMmNotLike(String value) {
            addCriterion("MM not like", value, "mm");
            return (Criteria) this;
        }

        public Criteria andMmIn(List<String> values) {
            addCriterion("MM in", values, "mm");
            return (Criteria) this;
        }

        public Criteria andMmNotIn(List<String> values) {
            addCriterion("MM not in", values, "mm");
            return (Criteria) this;
        }

        public Criteria andMmBetween(String value1, String value2) {
            addCriterion("MM between", value1, value2, "mm");
            return (Criteria) this;
        }

        public Criteria andMmNotBetween(String value1, String value2) {
            addCriterion("MM not between", value1, value2, "mm");
            return (Criteria) this;
        }

        public Criteria andBdIsNull() {
            addCriterion("BD is null");
            return (Criteria) this;
        }

        public Criteria andBdIsNotNull() {
            addCriterion("BD is not null");
            return (Criteria) this;
        }

        public Criteria andBdEqualTo(Short value) {
            addCriterion("BD =", value, "bd");
            return (Criteria) this;
        }

        public Criteria andBdNotEqualTo(Short value) {
            addCriterion("BD <>", value, "bd");
            return (Criteria) this;
        }

        public Criteria andBdGreaterThan(Short value) {
            addCriterion("BD >", value, "bd");
            return (Criteria) this;
        }

        public Criteria andBdGreaterThanOrEqualTo(Short value) {
            addCriterion("BD >=", value, "bd");
            return (Criteria) this;
        }

        public Criteria andBdLessThan(Short value) {
            addCriterion("BD <", value, "bd");
            return (Criteria) this;
        }

        public Criteria andBdLessThanOrEqualTo(Short value) {
            addCriterion("BD <=", value, "bd");
            return (Criteria) this;
        }

        public Criteria andBdIn(List<Short> values) {
            addCriterion("BD in", values, "bd");
            return (Criteria) this;
        }

        public Criteria andBdNotIn(List<Short> values) {
            addCriterion("BD not in", values, "bd");
            return (Criteria) this;
        }

        public Criteria andBdBetween(Short value1, Short value2) {
            addCriterion("BD between", value1, value2, "bd");
            return (Criteria) this;
        }

        public Criteria andBdNotBetween(Short value1, Short value2) {
            addCriterion("BD not between", value1, value2, "bd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NWIDP.EDT_YH_YYGC
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NWIDP.EDT_YH_YYGC
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}