package com.yfny.corepojo.entity.demandform.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.EDT_YH_YYGC.YH_ID
     *
     * @mbggenerated
     */
    private String yhId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.EDT_YH_YYGC.YYGC_ID
     *
     * @mbggenerated
     */
    private String yygcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.EDT_YH_YYGC.YHM
     *
     * @mbggenerated
     */
    private String yhm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.EDT_YH_YYGC.MM
     *
     * @mbggenerated
     */
    private String mm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.EDT_YH_YYGC.BD
     *
     * @mbggenerated
     */
    private Short bd;

    public User(String yhId, String yygcId, String yhm, String mm, Short bd) {
        this.yhId = yhId;
        this.yygcId = yygcId;
        this.yhm = yhm;
        this.mm = mm;
        this.bd = bd;
    }

    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.EDT_YH_YYGC.YH_ID
     *
     * @return the value of NWIDP.EDT_YH_YYGC.YH_ID
     *
     * @mbggenerated
     */
    public String getYhId() {
        return yhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.EDT_YH_YYGC.YH_ID
     *
     * @param yhId the value for NWIDP.EDT_YH_YYGC.YH_ID
     *
     * @mbggenerated
     */
    public void setYhId(String yhId) {
        this.yhId = yhId == null ? null : yhId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.EDT_YH_YYGC.YYGC_ID
     *
     * @return the value of NWIDP.EDT_YH_YYGC.YYGC_ID
     *
     * @mbggenerated
     */
    public String getYygcId() {
        return yygcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.EDT_YH_YYGC.YYGC_ID
     *
     * @param yygcId the value for NWIDP.EDT_YH_YYGC.YYGC_ID
     *
     * @mbggenerated
     */
    public void setYygcId(String yygcId) {
        this.yygcId = yygcId == null ? null : yygcId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.EDT_YH_YYGC.YHM
     *
     * @return the value of NWIDP.EDT_YH_YYGC.YHM
     *
     * @mbggenerated
     */
    public String getYhm() {
        return yhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.EDT_YH_YYGC.YHM
     *
     * @param yhm the value for NWIDP.EDT_YH_YYGC.YHM
     *
     * @mbggenerated
     */
    public void setYhm(String yhm) {
        this.yhm = yhm == null ? null : yhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.EDT_YH_YYGC.MM
     *
     * @return the value of NWIDP.EDT_YH_YYGC.MM
     *
     * @mbggenerated
     */
    public String getMm() {
        return mm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.EDT_YH_YYGC.MM
     *
     * @param mm the value for NWIDP.EDT_YH_YYGC.MM
     *
     * @mbggenerated
     */
    public void setMm(String mm) {
        this.mm = mm == null ? null : mm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.EDT_YH_YYGC.BD
     *
     * @return the value of NWIDP.EDT_YH_YYGC.BD
     *
     * @mbggenerated
     */
    public Short getBd() {
        return bd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.EDT_YH_YYGC.BD
     *
     * @param bd the value for NWIDP.EDT_YH_YYGC.BD
     *
     * @mbggenerated
     */
    public void setBd(Short bd) {
        this.bd = bd;
    }
}