package com.yfny.corepojo.entity.demandform.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class XqdFileExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NWIDP.IMP_XQD_FILES
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NWIDP.IMP_XQD_FILES
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NWIDP.IMP_XQD_FILES
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_FILES
     *
     * @mbggenerated
     */
    public XqdFileExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_FILES
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_FILES
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_FILES
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_FILES
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_FILES
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_FILES
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_FILES
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_FILES
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_FILES
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_FILES
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NWIDP.IMP_XQD_FILES
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFileIdIsNull() {
            addCriterion("FILE_ID is null");
            return (Criteria) this;
        }

        public Criteria andFileIdIsNotNull() {
            addCriterion("FILE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFileIdEqualTo(String value) {
            addCriterion("FILE_ID =", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdNotEqualTo(String value) {
            addCriterion("FILE_ID <>", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdGreaterThan(String value) {
            addCriterion("FILE_ID >", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdGreaterThanOrEqualTo(String value) {
            addCriterion("FILE_ID >=", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdLessThan(String value) {
            addCriterion("FILE_ID <", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdLessThanOrEqualTo(String value) {
            addCriterion("FILE_ID <=", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdLike(String value) {
            addCriterion("FILE_ID like", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdNotLike(String value) {
            addCriterion("FILE_ID not like", value, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdIn(List<String> values) {
            addCriterion("FILE_ID in", values, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdNotIn(List<String> values) {
            addCriterion("FILE_ID not in", values, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdBetween(String value1, String value2) {
            addCriterion("FILE_ID between", value1, value2, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileIdNotBetween(String value1, String value2) {
            addCriterion("FILE_ID not between", value1, value2, "fileId");
            return (Criteria) this;
        }

        public Criteria andFileMd5IsNull() {
            addCriterion("FILE_MD5 is null");
            return (Criteria) this;
        }

        public Criteria andFileMd5IsNotNull() {
            addCriterion("FILE_MD5 is not null");
            return (Criteria) this;
        }

        public Criteria andFileMd5EqualTo(String value) {
            addCriterion("FILE_MD5 =", value, "fileMd5");
            return (Criteria) this;
        }

        public Criteria andFileMd5NotEqualTo(String value) {
            addCriterion("FILE_MD5 <>", value, "fileMd5");
            return (Criteria) this;
        }

        public Criteria andFileMd5GreaterThan(String value) {
            addCriterion("FILE_MD5 >", value, "fileMd5");
            return (Criteria) this;
        }

        public Criteria andFileMd5GreaterThanOrEqualTo(String value) {
            addCriterion("FILE_MD5 >=", value, "fileMd5");
            return (Criteria) this;
        }

        public Criteria andFileMd5LessThan(String value) {
            addCriterion("FILE_MD5 <", value, "fileMd5");
            return (Criteria) this;
        }

        public Criteria andFileMd5LessThanOrEqualTo(String value) {
            addCriterion("FILE_MD5 <=", value, "fileMd5");
            return (Criteria) this;
        }

        public Criteria andFileMd5Like(String value) {
            addCriterion("FILE_MD5 like", value, "fileMd5");
            return (Criteria) this;
        }

        public Criteria andFileMd5NotLike(String value) {
            addCriterion("FILE_MD5 not like", value, "fileMd5");
            return (Criteria) this;
        }

        public Criteria andFileMd5In(List<String> values) {
            addCriterion("FILE_MD5 in", values, "fileMd5");
            return (Criteria) this;
        }

        public Criteria andFileMd5NotIn(List<String> values) {
            addCriterion("FILE_MD5 not in", values, "fileMd5");
            return (Criteria) this;
        }

        public Criteria andFileMd5Between(String value1, String value2) {
            addCriterion("FILE_MD5 between", value1, value2, "fileMd5");
            return (Criteria) this;
        }

        public Criteria andFileMd5NotBetween(String value1, String value2) {
            addCriterion("FILE_MD5 not between", value1, value2, "fileMd5");
            return (Criteria) this;
        }

        public Criteria andBlockNumIsNull() {
            addCriterion("BLOCK_NUM is null");
            return (Criteria) this;
        }

        public Criteria andBlockNumIsNotNull() {
            addCriterion("BLOCK_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andBlockNumEqualTo(BigDecimal value) {
            addCriterion("BLOCK_NUM =", value, "blockNum");
            return (Criteria) this;
        }

        public Criteria andBlockNumNotEqualTo(BigDecimal value) {
            addCriterion("BLOCK_NUM <>", value, "blockNum");
            return (Criteria) this;
        }

        public Criteria andBlockNumGreaterThan(BigDecimal value) {
            addCriterion("BLOCK_NUM >", value, "blockNum");
            return (Criteria) this;
        }

        public Criteria andBlockNumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BLOCK_NUM >=", value, "blockNum");
            return (Criteria) this;
        }

        public Criteria andBlockNumLessThan(BigDecimal value) {
            addCriterion("BLOCK_NUM <", value, "blockNum");
            return (Criteria) this;
        }

        public Criteria andBlockNumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BLOCK_NUM <=", value, "blockNum");
            return (Criteria) this;
        }

        public Criteria andBlockNumIn(List<BigDecimal> values) {
            addCriterion("BLOCK_NUM in", values, "blockNum");
            return (Criteria) this;
        }

        public Criteria andBlockNumNotIn(List<BigDecimal> values) {
            addCriterion("BLOCK_NUM not in", values, "blockNum");
            return (Criteria) this;
        }

        public Criteria andBlockNumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLOCK_NUM between", value1, value2, "blockNum");
            return (Criteria) this;
        }

        public Criteria andBlockNumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLOCK_NUM not between", value1, value2, "blockNum");
            return (Criteria) this;
        }

        public Criteria andBlockNoIsNull() {
            addCriterion("BLOCK_NO is null");
            return (Criteria) this;
        }

        public Criteria andBlockNoIsNotNull() {
            addCriterion("BLOCK_NO is not null");
            return (Criteria) this;
        }

        public Criteria andBlockNoEqualTo(BigDecimal value) {
            addCriterion("BLOCK_NO =", value, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoNotEqualTo(BigDecimal value) {
            addCriterion("BLOCK_NO <>", value, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoGreaterThan(BigDecimal value) {
            addCriterion("BLOCK_NO >", value, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BLOCK_NO >=", value, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoLessThan(BigDecimal value) {
            addCriterion("BLOCK_NO <", value, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BLOCK_NO <=", value, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoIn(List<BigDecimal> values) {
            addCriterion("BLOCK_NO in", values, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoNotIn(List<BigDecimal> values) {
            addCriterion("BLOCK_NO not in", values, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLOCK_NO between", value1, value2, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLOCK_NO not between", value1, value2, "blockNo");
            return (Criteria) this;
        }

        public Criteria andFileNameIsNull() {
            addCriterion("FILE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andFileNameIsNotNull() {
            addCriterion("FILE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andFileNameEqualTo(String value) {
            addCriterion("FILE_NAME =", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotEqualTo(String value) {
            addCriterion("FILE_NAME <>", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameGreaterThan(String value) {
            addCriterion("FILE_NAME >", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("FILE_NAME >=", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameLessThan(String value) {
            addCriterion("FILE_NAME <", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameLessThanOrEqualTo(String value) {
            addCriterion("FILE_NAME <=", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameLike(String value) {
            addCriterion("FILE_NAME like", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotLike(String value) {
            addCriterion("FILE_NAME not like", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameIn(List<String> values) {
            addCriterion("FILE_NAME in", values, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotIn(List<String> values) {
            addCriterion("FILE_NAME not in", values, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameBetween(String value1, String value2) {
            addCriterion("FILE_NAME between", value1, value2, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotBetween(String value1, String value2) {
            addCriterion("FILE_NAME not between", value1, value2, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileTypeIsNull() {
            addCriterion("FILE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andFileTypeIsNotNull() {
            addCriterion("FILE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andFileTypeEqualTo(String value) {
            addCriterion("FILE_TYPE =", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeNotEqualTo(String value) {
            addCriterion("FILE_TYPE <>", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeGreaterThan(String value) {
            addCriterion("FILE_TYPE >", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeGreaterThanOrEqualTo(String value) {
            addCriterion("FILE_TYPE >=", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeLessThan(String value) {
            addCriterion("FILE_TYPE <", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeLessThanOrEqualTo(String value) {
            addCriterion("FILE_TYPE <=", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeLike(String value) {
            addCriterion("FILE_TYPE like", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeNotLike(String value) {
            addCriterion("FILE_TYPE not like", value, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeIn(List<String> values) {
            addCriterion("FILE_TYPE in", values, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeNotIn(List<String> values) {
            addCriterion("FILE_TYPE not in", values, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeBetween(String value1, String value2) {
            addCriterion("FILE_TYPE between", value1, value2, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileTypeNotBetween(String value1, String value2) {
            addCriterion("FILE_TYPE not between", value1, value2, "fileType");
            return (Criteria) this;
        }

        public Criteria andFileSizeIsNull() {
            addCriterion("FILE_SIZE is null");
            return (Criteria) this;
        }

        public Criteria andFileSizeIsNotNull() {
            addCriterion("FILE_SIZE is not null");
            return (Criteria) this;
        }

        public Criteria andFileSizeEqualTo(Double value) {
            addCriterion("FILE_SIZE =", value, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeNotEqualTo(Double value) {
            addCriterion("FILE_SIZE <>", value, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeGreaterThan(Double value) {
            addCriterion("FILE_SIZE >", value, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeGreaterThanOrEqualTo(Double value) {
            addCriterion("FILE_SIZE >=", value, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeLessThan(Double value) {
            addCriterion("FILE_SIZE <", value, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeLessThanOrEqualTo(Double value) {
            addCriterion("FILE_SIZE <=", value, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeIn(List<Double> values) {
            addCriterion("FILE_SIZE in", values, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeNotIn(List<Double> values) {
            addCriterion("FILE_SIZE not in", values, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeBetween(Double value1, Double value2) {
            addCriterion("FILE_SIZE between", value1, value2, "fileSize");
            return (Criteria) this;
        }

        public Criteria andFileSizeNotBetween(Double value1, Double value2) {
            addCriterion("FILE_SIZE not between", value1, value2, "fileSize");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNull() {
            addCriterion("GROUP_ID is null");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNotNull() {
            addCriterion("GROUP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andGroupIdEqualTo(String value) {
            addCriterion("GROUP_ID =", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotEqualTo(String value) {
            addCriterion("GROUP_ID <>", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThan(String value) {
            addCriterion("GROUP_ID >", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThanOrEqualTo(String value) {
            addCriterion("GROUP_ID >=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThan(String value) {
            addCriterion("GROUP_ID <", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThanOrEqualTo(String value) {
            addCriterion("GROUP_ID <=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLike(String value) {
            addCriterion("GROUP_ID like", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotLike(String value) {
            addCriterion("GROUP_ID not like", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdIn(List<String> values) {
            addCriterion("GROUP_ID in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotIn(List<String> values) {
            addCriterion("GROUP_ID not in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdBetween(String value1, String value2) {
            addCriterion("GROUP_ID between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotBetween(String value1, String value2) {
            addCriterion("GROUP_ID not between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andPathIsNull() {
            addCriterion("PATH is null");
            return (Criteria) this;
        }

        public Criteria andPathIsNotNull() {
            addCriterion("PATH is not null");
            return (Criteria) this;
        }

        public Criteria andPathEqualTo(String value) {
            addCriterion("PATH =", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathNotEqualTo(String value) {
            addCriterion("PATH <>", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathGreaterThan(String value) {
            addCriterion("PATH >", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathGreaterThanOrEqualTo(String value) {
            addCriterion("PATH >=", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathLessThan(String value) {
            addCriterion("PATH <", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathLessThanOrEqualTo(String value) {
            addCriterion("PATH <=", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathLike(String value) {
            addCriterion("PATH like", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathNotLike(String value) {
            addCriterion("PATH not like", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathIn(List<String> values) {
            addCriterion("PATH in", values, "path");
            return (Criteria) this;
        }

        public Criteria andPathNotIn(List<String> values) {
            addCriterion("PATH not in", values, "path");
            return (Criteria) this;
        }

        public Criteria andPathBetween(String value1, String value2) {
            addCriterion("PATH between", value1, value2, "path");
            return (Criteria) this;
        }

        public Criteria andPathNotBetween(String value1, String value2) {
            addCriterion("PATH not between", value1, value2, "path");
            return (Criteria) this;
        }

        public Criteria andModifDateIsNull() {
            addCriterion("MODIF_DATE is null");
            return (Criteria) this;
        }

        public Criteria andModifDateIsNotNull() {
            addCriterion("MODIF_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andModifDateEqualTo(Date value) {
            addCriterion("MODIF_DATE =", value, "modifDate");
            return (Criteria) this;
        }

        public Criteria andModifDateNotEqualTo(Date value) {
            addCriterion("MODIF_DATE <>", value, "modifDate");
            return (Criteria) this;
        }

        public Criteria andModifDateGreaterThan(Date value) {
            addCriterion("MODIF_DATE >", value, "modifDate");
            return (Criteria) this;
        }

        public Criteria andModifDateGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIF_DATE >=", value, "modifDate");
            return (Criteria) this;
        }

        public Criteria andModifDateLessThan(Date value) {
            addCriterion("MODIF_DATE <", value, "modifDate");
            return (Criteria) this;
        }

        public Criteria andModifDateLessThanOrEqualTo(Date value) {
            addCriterion("MODIF_DATE <=", value, "modifDate");
            return (Criteria) this;
        }

        public Criteria andModifDateIn(List<Date> values) {
            addCriterion("MODIF_DATE in", values, "modifDate");
            return (Criteria) this;
        }

        public Criteria andModifDateNotIn(List<Date> values) {
            addCriterion("MODIF_DATE not in", values, "modifDate");
            return (Criteria) this;
        }

        public Criteria andModifDateBetween(Date value1, Date value2) {
            addCriterion("MODIF_DATE between", value1, value2, "modifDate");
            return (Criteria) this;
        }

        public Criteria andModifDateNotBetween(Date value1, Date value2) {
            addCriterion("MODIF_DATE not between", value1, value2, "modifDate");
            return (Criteria) this;
        }

        public Criteria andFileStateIsNull() {
            addCriterion("FILE_STATE is null");
            return (Criteria) this;
        }

        public Criteria andFileStateIsNotNull() {
            addCriterion("FILE_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andFileStateEqualTo(BigDecimal value) {
            addCriterion("FILE_STATE =", value, "fileState");
            return (Criteria) this;
        }

        public Criteria andFileStateNotEqualTo(BigDecimal value) {
            addCriterion("FILE_STATE <>", value, "fileState");
            return (Criteria) this;
        }

        public Criteria andFileStateGreaterThan(BigDecimal value) {
            addCriterion("FILE_STATE >", value, "fileState");
            return (Criteria) this;
        }

        public Criteria andFileStateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FILE_STATE >=", value, "fileState");
            return (Criteria) this;
        }

        public Criteria andFileStateLessThan(BigDecimal value) {
            addCriterion("FILE_STATE <", value, "fileState");
            return (Criteria) this;
        }

        public Criteria andFileStateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FILE_STATE <=", value, "fileState");
            return (Criteria) this;
        }

        public Criteria andFileStateIn(List<BigDecimal> values) {
            addCriterion("FILE_STATE in", values, "fileState");
            return (Criteria) this;
        }

        public Criteria andFileStateNotIn(List<BigDecimal> values) {
            addCriterion("FILE_STATE not in", values, "fileState");
            return (Criteria) this;
        }

        public Criteria andFileStateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FILE_STATE between", value1, value2, "fileState");
            return (Criteria) this;
        }

        public Criteria andFileStateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FILE_STATE not between", value1, value2, "fileState");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("VERSION =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("VERSION <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("VERSION >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("VERSION >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("VERSION <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("VERSION <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("VERSION like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("VERSION not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("VERSION in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("VERSION not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("VERSION between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("VERSION not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("DESCRIPTION =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("DESCRIPTION <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("DESCRIPTION >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("DESCRIPTION <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("DESCRIPTION like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("DESCRIPTION not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("DESCRIPTION in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("DESCRIPTION not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("DESCRIPTION between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPTION not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andApplicationIsNull() {
            addCriterion("APPLICATION is null");
            return (Criteria) this;
        }

        public Criteria andApplicationIsNotNull() {
            addCriterion("APPLICATION is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationEqualTo(BigDecimal value) {
            addCriterion("APPLICATION =", value, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationNotEqualTo(BigDecimal value) {
            addCriterion("APPLICATION <>", value, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationGreaterThan(BigDecimal value) {
            addCriterion("APPLICATION >", value, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("APPLICATION >=", value, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationLessThan(BigDecimal value) {
            addCriterion("APPLICATION <", value, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationLessThanOrEqualTo(BigDecimal value) {
            addCriterion("APPLICATION <=", value, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationIn(List<BigDecimal> values) {
            addCriterion("APPLICATION in", values, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationNotIn(List<BigDecimal> values) {
            addCriterion("APPLICATION not in", values, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("APPLICATION between", value1, value2, "application");
            return (Criteria) this;
        }

        public Criteria andApplicationNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("APPLICATION not between", value1, value2, "application");
            return (Criteria) this;
        }

        public Criteria andFileAliasIsNull() {
            addCriterion("FILE_ALIAS is null");
            return (Criteria) this;
        }

        public Criteria andFileAliasIsNotNull() {
            addCriterion("FILE_ALIAS is not null");
            return (Criteria) this;
        }

        public Criteria andFileAliasEqualTo(String value) {
            addCriterion("FILE_ALIAS =", value, "fileAlias");
            return (Criteria) this;
        }

        public Criteria andFileAliasNotEqualTo(String value) {
            addCriterion("FILE_ALIAS <>", value, "fileAlias");
            return (Criteria) this;
        }

        public Criteria andFileAliasGreaterThan(String value) {
            addCriterion("FILE_ALIAS >", value, "fileAlias");
            return (Criteria) this;
        }

        public Criteria andFileAliasGreaterThanOrEqualTo(String value) {
            addCriterion("FILE_ALIAS >=", value, "fileAlias");
            return (Criteria) this;
        }

        public Criteria andFileAliasLessThan(String value) {
            addCriterion("FILE_ALIAS <", value, "fileAlias");
            return (Criteria) this;
        }

        public Criteria andFileAliasLessThanOrEqualTo(String value) {
            addCriterion("FILE_ALIAS <=", value, "fileAlias");
            return (Criteria) this;
        }

        public Criteria andFileAliasLike(String value) {
            addCriterion("FILE_ALIAS like", value, "fileAlias");
            return (Criteria) this;
        }

        public Criteria andFileAliasNotLike(String value) {
            addCriterion("FILE_ALIAS not like", value, "fileAlias");
            return (Criteria) this;
        }

        public Criteria andFileAliasIn(List<String> values) {
            addCriterion("FILE_ALIAS in", values, "fileAlias");
            return (Criteria) this;
        }

        public Criteria andFileAliasNotIn(List<String> values) {
            addCriterion("FILE_ALIAS not in", values, "fileAlias");
            return (Criteria) this;
        }

        public Criteria andFileAliasBetween(String value1, String value2) {
            addCriterion("FILE_ALIAS between", value1, value2, "fileAlias");
            return (Criteria) this;
        }

        public Criteria andFileAliasNotBetween(String value1, String value2) {
            addCriterion("FILE_ALIAS not between", value1, value2, "fileAlias");
            return (Criteria) this;
        }

        public Criteria andColumn17IsNull() {
            addCriterion("COLUMN_17 is null");
            return (Criteria) this;
        }

        public Criteria andColumn17IsNotNull() {
            addCriterion("COLUMN_17 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn17EqualTo(String value) {
            addCriterion("COLUMN_17 =", value, "column17");
            return (Criteria) this;
        }

        public Criteria andColumn17NotEqualTo(String value) {
            addCriterion("COLUMN_17 <>", value, "column17");
            return (Criteria) this;
        }

        public Criteria andColumn17GreaterThan(String value) {
            addCriterion("COLUMN_17 >", value, "column17");
            return (Criteria) this;
        }

        public Criteria andColumn17GreaterThanOrEqualTo(String value) {
            addCriterion("COLUMN_17 >=", value, "column17");
            return (Criteria) this;
        }

        public Criteria andColumn17LessThan(String value) {
            addCriterion("COLUMN_17 <", value, "column17");
            return (Criteria) this;
        }

        public Criteria andColumn17LessThanOrEqualTo(String value) {
            addCriterion("COLUMN_17 <=", value, "column17");
            return (Criteria) this;
        }

        public Criteria andColumn17Like(String value) {
            addCriterion("COLUMN_17 like", value, "column17");
            return (Criteria) this;
        }

        public Criteria andColumn17NotLike(String value) {
            addCriterion("COLUMN_17 not like", value, "column17");
            return (Criteria) this;
        }

        public Criteria andColumn17In(List<String> values) {
            addCriterion("COLUMN_17 in", values, "column17");
            return (Criteria) this;
        }

        public Criteria andColumn17NotIn(List<String> values) {
            addCriterion("COLUMN_17 not in", values, "column17");
            return (Criteria) this;
        }

        public Criteria andColumn17Between(String value1, String value2) {
            addCriterion("COLUMN_17 between", value1, value2, "column17");
            return (Criteria) this;
        }

        public Criteria andColumn17NotBetween(String value1, String value2) {
            addCriterion("COLUMN_17 not between", value1, value2, "column17");
            return (Criteria) this;
        }

        public Criteria andColumn18IsNull() {
            addCriterion("COLUMN_18 is null");
            return (Criteria) this;
        }

        public Criteria andColumn18IsNotNull() {
            addCriterion("COLUMN_18 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn18EqualTo(String value) {
            addCriterion("COLUMN_18 =", value, "column18");
            return (Criteria) this;
        }

        public Criteria andColumn18NotEqualTo(String value) {
            addCriterion("COLUMN_18 <>", value, "column18");
            return (Criteria) this;
        }

        public Criteria andColumn18GreaterThan(String value) {
            addCriterion("COLUMN_18 >", value, "column18");
            return (Criteria) this;
        }

        public Criteria andColumn18GreaterThanOrEqualTo(String value) {
            addCriterion("COLUMN_18 >=", value, "column18");
            return (Criteria) this;
        }

        public Criteria andColumn18LessThan(String value) {
            addCriterion("COLUMN_18 <", value, "column18");
            return (Criteria) this;
        }

        public Criteria andColumn18LessThanOrEqualTo(String value) {
            addCriterion("COLUMN_18 <=", value, "column18");
            return (Criteria) this;
        }

        public Criteria andColumn18Like(String value) {
            addCriterion("COLUMN_18 like", value, "column18");
            return (Criteria) this;
        }

        public Criteria andColumn18NotLike(String value) {
            addCriterion("COLUMN_18 not like", value, "column18");
            return (Criteria) this;
        }

        public Criteria andColumn18In(List<String> values) {
            addCriterion("COLUMN_18 in", values, "column18");
            return (Criteria) this;
        }

        public Criteria andColumn18NotIn(List<String> values) {
            addCriterion("COLUMN_18 not in", values, "column18");
            return (Criteria) this;
        }

        public Criteria andColumn18Between(String value1, String value2) {
            addCriterion("COLUMN_18 between", value1, value2, "column18");
            return (Criteria) this;
        }

        public Criteria andColumn18NotBetween(String value1, String value2) {
            addCriterion("COLUMN_18 not between", value1, value2, "column18");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NWIDP.IMP_XQD_FILES
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NWIDP.IMP_XQD_FILES
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}