package com.yfny.corepojo.entity.demandform.model;

import java.math.BigDecimal;
import java.util.Date;

public class XqdFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_FILES.FILE_ID
     *
     * @mbggenerated
     */
    private String fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_FILES.FILE_MD5
     *
     * @mbggenerated
     */
    private String fileMd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_FILES.BLOCK_NUM
     *
     * @mbggenerated
     */
    private BigDecimal blockNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_FILES.BLOCK_NO
     *
     * @mbggenerated
     */
    private BigDecimal blockNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_FILES.FILE_NAME
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_FILES.FILE_TYPE
     *
     * @mbggenerated
     */
    private String fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_FILES.FILE_SIZE
     *
     * @mbggenerated
     */
    private Double fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_FILES.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_FILES.GROUP_ID
     *
     * @mbggenerated
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_FILES.PATH
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_FILES.MODIF_DATE
     *
     * @mbggenerated
     */
    private Date modifDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_FILES.FILE_STATE
     *
     * @mbggenerated
     */
    private BigDecimal fileState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_FILES.VERSION
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_FILES.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_FILES.APPLICATION
     *
     * @mbggenerated
     */
    private BigDecimal application;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_FILES.FILE_ALIAS
     *
     * @mbggenerated
     */
    private String fileAlias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_FILES.COLUMN_17
     *
     * @mbggenerated
     */
    private String column17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_FILES.COLUMN_18
     *
     * @mbggenerated
     */
    private String column18;

    public XqdFile(String fileId, String fileMd5, BigDecimal blockNum, BigDecimal blockNo, String fileName, String fileType, Double fileSize, String userId, String groupId, String path, Date modifDate, BigDecimal fileState, String version, String description, BigDecimal application, String fileAlias, String column17, String column18) {
        this.fileId = fileId;
        this.fileMd5 = fileMd5;
        this.blockNum = blockNum;
        this.blockNo = blockNo;
        this.fileName = fileName;
        this.fileType = fileType;
        this.fileSize = fileSize;
        this.userId = userId;
        this.groupId = groupId;
        this.path = path;
        this.modifDate = modifDate;
        this.fileState = fileState;
        this.version = version;
        this.description = description;
        this.application = application;
        this.fileAlias = fileAlias;
        this.column17 = column17;
        this.column18 = column18;
    }

    public XqdFile() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_FILES.FILE_ID
     *
     * @return the value of NWIDP.IMP_XQD_FILES.FILE_ID
     *
     * @mbggenerated
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_FILES.FILE_ID
     *
     * @param fileId the value for NWIDP.IMP_XQD_FILES.FILE_ID
     *
     * @mbggenerated
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_FILES.FILE_MD5
     *
     * @return the value of NWIDP.IMP_XQD_FILES.FILE_MD5
     *
     * @mbggenerated
     */
    public String getFileMd5() {
        return fileMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_FILES.FILE_MD5
     *
     * @param fileMd5 the value for NWIDP.IMP_XQD_FILES.FILE_MD5
     *
     * @mbggenerated
     */
    public void setFileMd5(String fileMd5) {
        this.fileMd5 = fileMd5 == null ? null : fileMd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_FILES.BLOCK_NUM
     *
     * @return the value of NWIDP.IMP_XQD_FILES.BLOCK_NUM
     *
     * @mbggenerated
     */
    public BigDecimal getBlockNum() {
        return blockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_FILES.BLOCK_NUM
     *
     * @param blockNum the value for NWIDP.IMP_XQD_FILES.BLOCK_NUM
     *
     * @mbggenerated
     */
    public void setBlockNum(BigDecimal blockNum) {
        this.blockNum = blockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_FILES.BLOCK_NO
     *
     * @return the value of NWIDP.IMP_XQD_FILES.BLOCK_NO
     *
     * @mbggenerated
     */
    public BigDecimal getBlockNo() {
        return blockNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_FILES.BLOCK_NO
     *
     * @param blockNo the value for NWIDP.IMP_XQD_FILES.BLOCK_NO
     *
     * @mbggenerated
     */
    public void setBlockNo(BigDecimal blockNo) {
        this.blockNo = blockNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_FILES.FILE_NAME
     *
     * @return the value of NWIDP.IMP_XQD_FILES.FILE_NAME
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_FILES.FILE_NAME
     *
     * @param fileName the value for NWIDP.IMP_XQD_FILES.FILE_NAME
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_FILES.FILE_TYPE
     *
     * @return the value of NWIDP.IMP_XQD_FILES.FILE_TYPE
     *
     * @mbggenerated
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_FILES.FILE_TYPE
     *
     * @param fileType the value for NWIDP.IMP_XQD_FILES.FILE_TYPE
     *
     * @mbggenerated
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_FILES.FILE_SIZE
     *
     * @return the value of NWIDP.IMP_XQD_FILES.FILE_SIZE
     *
     * @mbggenerated
     */
    public Double getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_FILES.FILE_SIZE
     *
     * @param fileSize the value for NWIDP.IMP_XQD_FILES.FILE_SIZE
     *
     * @mbggenerated
     */
    public void setFileSize(Double fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_FILES.USER_ID
     *
     * @return the value of NWIDP.IMP_XQD_FILES.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_FILES.USER_ID
     *
     * @param userId the value for NWIDP.IMP_XQD_FILES.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_FILES.GROUP_ID
     *
     * @return the value of NWIDP.IMP_XQD_FILES.GROUP_ID
     *
     * @mbggenerated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_FILES.GROUP_ID
     *
     * @param groupId the value for NWIDP.IMP_XQD_FILES.GROUP_ID
     *
     * @mbggenerated
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_FILES.PATH
     *
     * @return the value of NWIDP.IMP_XQD_FILES.PATH
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_FILES.PATH
     *
     * @param path the value for NWIDP.IMP_XQD_FILES.PATH
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_FILES.MODIF_DATE
     *
     * @return the value of NWIDP.IMP_XQD_FILES.MODIF_DATE
     *
     * @mbggenerated
     */
    public Date getModifDate() {
        return modifDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_FILES.MODIF_DATE
     *
     * @param modifDate the value for NWIDP.IMP_XQD_FILES.MODIF_DATE
     *
     * @mbggenerated
     */
    public void setModifDate(Date modifDate) {
        this.modifDate = modifDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_FILES.FILE_STATE
     *
     * @return the value of NWIDP.IMP_XQD_FILES.FILE_STATE
     *
     * @mbggenerated
     */
    public BigDecimal getFileState() {
        return fileState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_FILES.FILE_STATE
     *
     * @param fileState the value for NWIDP.IMP_XQD_FILES.FILE_STATE
     *
     * @mbggenerated
     */
    public void setFileState(BigDecimal fileState) {
        this.fileState = fileState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_FILES.VERSION
     *
     * @return the value of NWIDP.IMP_XQD_FILES.VERSION
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_FILES.VERSION
     *
     * @param version the value for NWIDP.IMP_XQD_FILES.VERSION
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_FILES.DESCRIPTION
     *
     * @return the value of NWIDP.IMP_XQD_FILES.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_FILES.DESCRIPTION
     *
     * @param description the value for NWIDP.IMP_XQD_FILES.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_FILES.APPLICATION
     *
     * @return the value of NWIDP.IMP_XQD_FILES.APPLICATION
     *
     * @mbggenerated
     */
    public BigDecimal getApplication() {
        return application;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_FILES.APPLICATION
     *
     * @param application the value for NWIDP.IMP_XQD_FILES.APPLICATION
     *
     * @mbggenerated
     */
    public void setApplication(BigDecimal application) {
        this.application = application;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_FILES.FILE_ALIAS
     *
     * @return the value of NWIDP.IMP_XQD_FILES.FILE_ALIAS
     *
     * @mbggenerated
     */
    public String getFileAlias() {
        return fileAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_FILES.FILE_ALIAS
     *
     * @param fileAlias the value for NWIDP.IMP_XQD_FILES.FILE_ALIAS
     *
     * @mbggenerated
     */
    public void setFileAlias(String fileAlias) {
        this.fileAlias = fileAlias == null ? null : fileAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_FILES.COLUMN_17
     *
     * @return the value of NWIDP.IMP_XQD_FILES.COLUMN_17
     *
     * @mbggenerated
     */
    public String getColumn17() {
        return column17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_FILES.COLUMN_17
     *
     * @param column17 the value for NWIDP.IMP_XQD_FILES.COLUMN_17
     *
     * @mbggenerated
     */
    public void setColumn17(String column17) {
        this.column17 = column17 == null ? null : column17.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_FILES.COLUMN_18
     *
     * @return the value of NWIDP.IMP_XQD_FILES.COLUMN_18
     *
     * @mbggenerated
     */
    public String getColumn18() {
        return column18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_FILES.COLUMN_18
     *
     * @param column18 the value for NWIDP.IMP_XQD_FILES.COLUMN_18
     *
     * @mbggenerated
     */
    public void setColumn18(String column18) {
        this.column18 = column18 == null ? null : column18.trim();
    }
}