package com.yfny.corepojo.entity.demandform.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class XqdFileBlocksExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NWIDP.IMP_XQD_FILEBLOCKS
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NWIDP.IMP_XQD_FILEBLOCKS
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NWIDP.IMP_XQD_FILEBLOCKS
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_FILEBLOCKS
     *
     * @mbggenerated
     */
    public XqdFileBlocksExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_FILEBLOCKS
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_FILEBLOCKS
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_FILEBLOCKS
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_FILEBLOCKS
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_FILEBLOCKS
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_FILEBLOCKS
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_FILEBLOCKS
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_FILEBLOCKS
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_FILEBLOCKS
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_FILEBLOCKS
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NWIDP.IMP_XQD_FILEBLOCKS
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBlockIdIsNull() {
            addCriterion("BLOCK_ID is null");
            return (Criteria) this;
        }

        public Criteria andBlockIdIsNotNull() {
            addCriterion("BLOCK_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBlockIdEqualTo(String value) {
            addCriterion("BLOCK_ID =", value, "blockId");
            return (Criteria) this;
        }

        public Criteria andBlockIdNotEqualTo(String value) {
            addCriterion("BLOCK_ID <>", value, "blockId");
            return (Criteria) this;
        }

        public Criteria andBlockIdGreaterThan(String value) {
            addCriterion("BLOCK_ID >", value, "blockId");
            return (Criteria) this;
        }

        public Criteria andBlockIdGreaterThanOrEqualTo(String value) {
            addCriterion("BLOCK_ID >=", value, "blockId");
            return (Criteria) this;
        }

        public Criteria andBlockIdLessThan(String value) {
            addCriterion("BLOCK_ID <", value, "blockId");
            return (Criteria) this;
        }

        public Criteria andBlockIdLessThanOrEqualTo(String value) {
            addCriterion("BLOCK_ID <=", value, "blockId");
            return (Criteria) this;
        }

        public Criteria andBlockIdLike(String value) {
            addCriterion("BLOCK_ID like", value, "blockId");
            return (Criteria) this;
        }

        public Criteria andBlockIdNotLike(String value) {
            addCriterion("BLOCK_ID not like", value, "blockId");
            return (Criteria) this;
        }

        public Criteria andBlockIdIn(List<String> values) {
            addCriterion("BLOCK_ID in", values, "blockId");
            return (Criteria) this;
        }

        public Criteria andBlockIdNotIn(List<String> values) {
            addCriterion("BLOCK_ID not in", values, "blockId");
            return (Criteria) this;
        }

        public Criteria andBlockIdBetween(String value1, String value2) {
            addCriterion("BLOCK_ID between", value1, value2, "blockId");
            return (Criteria) this;
        }

        public Criteria andBlockIdNotBetween(String value1, String value2) {
            addCriterion("BLOCK_ID not between", value1, value2, "blockId");
            return (Criteria) this;
        }

        public Criteria andFileMd5IsNull() {
            addCriterion("FILE_MD5 is null");
            return (Criteria) this;
        }

        public Criteria andFileMd5IsNotNull() {
            addCriterion("FILE_MD5 is not null");
            return (Criteria) this;
        }

        public Criteria andFileMd5EqualTo(String value) {
            addCriterion("FILE_MD5 =", value, "fileMd5");
            return (Criteria) this;
        }

        public Criteria andFileMd5NotEqualTo(String value) {
            addCriterion("FILE_MD5 <>", value, "fileMd5");
            return (Criteria) this;
        }

        public Criteria andFileMd5GreaterThan(String value) {
            addCriterion("FILE_MD5 >", value, "fileMd5");
            return (Criteria) this;
        }

        public Criteria andFileMd5GreaterThanOrEqualTo(String value) {
            addCriterion("FILE_MD5 >=", value, "fileMd5");
            return (Criteria) this;
        }

        public Criteria andFileMd5LessThan(String value) {
            addCriterion("FILE_MD5 <", value, "fileMd5");
            return (Criteria) this;
        }

        public Criteria andFileMd5LessThanOrEqualTo(String value) {
            addCriterion("FILE_MD5 <=", value, "fileMd5");
            return (Criteria) this;
        }

        public Criteria andFileMd5Like(String value) {
            addCriterion("FILE_MD5 like", value, "fileMd5");
            return (Criteria) this;
        }

        public Criteria andFileMd5NotLike(String value) {
            addCriterion("FILE_MD5 not like", value, "fileMd5");
            return (Criteria) this;
        }

        public Criteria andFileMd5In(List<String> values) {
            addCriterion("FILE_MD5 in", values, "fileMd5");
            return (Criteria) this;
        }

        public Criteria andFileMd5NotIn(List<String> values) {
            addCriterion("FILE_MD5 not in", values, "fileMd5");
            return (Criteria) this;
        }

        public Criteria andFileMd5Between(String value1, String value2) {
            addCriterion("FILE_MD5 between", value1, value2, "fileMd5");
            return (Criteria) this;
        }

        public Criteria andFileMd5NotBetween(String value1, String value2) {
            addCriterion("FILE_MD5 not between", value1, value2, "fileMd5");
            return (Criteria) this;
        }

        public Criteria andBlockNoIsNull() {
            addCriterion("BLOCK_NO is null");
            return (Criteria) this;
        }

        public Criteria andBlockNoIsNotNull() {
            addCriterion("BLOCK_NO is not null");
            return (Criteria) this;
        }

        public Criteria andBlockNoEqualTo(BigDecimal value) {
            addCriterion("BLOCK_NO =", value, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoNotEqualTo(BigDecimal value) {
            addCriterion("BLOCK_NO <>", value, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoGreaterThan(BigDecimal value) {
            addCriterion("BLOCK_NO >", value, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BLOCK_NO >=", value, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoLessThan(BigDecimal value) {
            addCriterion("BLOCK_NO <", value, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BLOCK_NO <=", value, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoIn(List<BigDecimal> values) {
            addCriterion("BLOCK_NO in", values, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoNotIn(List<BigDecimal> values) {
            addCriterion("BLOCK_NO not in", values, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLOCK_NO between", value1, value2, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockNoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLOCK_NO not between", value1, value2, "blockNo");
            return (Criteria) this;
        }

        public Criteria andBlockMd5IsNull() {
            addCriterion("BLOCK_MD5 is null");
            return (Criteria) this;
        }

        public Criteria andBlockMd5IsNotNull() {
            addCriterion("BLOCK_MD5 is not null");
            return (Criteria) this;
        }

        public Criteria andBlockMd5EqualTo(String value) {
            addCriterion("BLOCK_MD5 =", value, "blockMd5");
            return (Criteria) this;
        }

        public Criteria andBlockMd5NotEqualTo(String value) {
            addCriterion("BLOCK_MD5 <>", value, "blockMd5");
            return (Criteria) this;
        }

        public Criteria andBlockMd5GreaterThan(String value) {
            addCriterion("BLOCK_MD5 >", value, "blockMd5");
            return (Criteria) this;
        }

        public Criteria andBlockMd5GreaterThanOrEqualTo(String value) {
            addCriterion("BLOCK_MD5 >=", value, "blockMd5");
            return (Criteria) this;
        }

        public Criteria andBlockMd5LessThan(String value) {
            addCriterion("BLOCK_MD5 <", value, "blockMd5");
            return (Criteria) this;
        }

        public Criteria andBlockMd5LessThanOrEqualTo(String value) {
            addCriterion("BLOCK_MD5 <=", value, "blockMd5");
            return (Criteria) this;
        }

        public Criteria andBlockMd5Like(String value) {
            addCriterion("BLOCK_MD5 like", value, "blockMd5");
            return (Criteria) this;
        }

        public Criteria andBlockMd5NotLike(String value) {
            addCriterion("BLOCK_MD5 not like", value, "blockMd5");
            return (Criteria) this;
        }

        public Criteria andBlockMd5In(List<String> values) {
            addCriterion("BLOCK_MD5 in", values, "blockMd5");
            return (Criteria) this;
        }

        public Criteria andBlockMd5NotIn(List<String> values) {
            addCriterion("BLOCK_MD5 not in", values, "blockMd5");
            return (Criteria) this;
        }

        public Criteria andBlockMd5Between(String value1, String value2) {
            addCriterion("BLOCK_MD5 between", value1, value2, "blockMd5");
            return (Criteria) this;
        }

        public Criteria andBlockMd5NotBetween(String value1, String value2) {
            addCriterion("BLOCK_MD5 not between", value1, value2, "blockMd5");
            return (Criteria) this;
        }

        public Criteria andBlockStatusIsNull() {
            addCriterion("BLOCK_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andBlockStatusIsNotNull() {
            addCriterion("BLOCK_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andBlockStatusEqualTo(BigDecimal value) {
            addCriterion("BLOCK_STATUS =", value, "blockStatus");
            return (Criteria) this;
        }

        public Criteria andBlockStatusNotEqualTo(BigDecimal value) {
            addCriterion("BLOCK_STATUS <>", value, "blockStatus");
            return (Criteria) this;
        }

        public Criteria andBlockStatusGreaterThan(BigDecimal value) {
            addCriterion("BLOCK_STATUS >", value, "blockStatus");
            return (Criteria) this;
        }

        public Criteria andBlockStatusGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BLOCK_STATUS >=", value, "blockStatus");
            return (Criteria) this;
        }

        public Criteria andBlockStatusLessThan(BigDecimal value) {
            addCriterion("BLOCK_STATUS <", value, "blockStatus");
            return (Criteria) this;
        }

        public Criteria andBlockStatusLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BLOCK_STATUS <=", value, "blockStatus");
            return (Criteria) this;
        }

        public Criteria andBlockStatusIn(List<BigDecimal> values) {
            addCriterion("BLOCK_STATUS in", values, "blockStatus");
            return (Criteria) this;
        }

        public Criteria andBlockStatusNotIn(List<BigDecimal> values) {
            addCriterion("BLOCK_STATUS not in", values, "blockStatus");
            return (Criteria) this;
        }

        public Criteria andBlockStatusBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLOCK_STATUS between", value1, value2, "blockStatus");
            return (Criteria) this;
        }

        public Criteria andBlockStatusNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BLOCK_STATUS not between", value1, value2, "blockStatus");
            return (Criteria) this;
        }

        public Criteria andBlockSizeIsNull() {
            addCriterion("BLOCK_SIZE is null");
            return (Criteria) this;
        }

        public Criteria andBlockSizeIsNotNull() {
            addCriterion("BLOCK_SIZE is not null");
            return (Criteria) this;
        }

        public Criteria andBlockSizeEqualTo(Double value) {
            addCriterion("BLOCK_SIZE =", value, "blockSize");
            return (Criteria) this;
        }

        public Criteria andBlockSizeNotEqualTo(Double value) {
            addCriterion("BLOCK_SIZE <>", value, "blockSize");
            return (Criteria) this;
        }

        public Criteria andBlockSizeGreaterThan(Double value) {
            addCriterion("BLOCK_SIZE >", value, "blockSize");
            return (Criteria) this;
        }

        public Criteria andBlockSizeGreaterThanOrEqualTo(Double value) {
            addCriterion("BLOCK_SIZE >=", value, "blockSize");
            return (Criteria) this;
        }

        public Criteria andBlockSizeLessThan(Double value) {
            addCriterion("BLOCK_SIZE <", value, "blockSize");
            return (Criteria) this;
        }

        public Criteria andBlockSizeLessThanOrEqualTo(Double value) {
            addCriterion("BLOCK_SIZE <=", value, "blockSize");
            return (Criteria) this;
        }

        public Criteria andBlockSizeIn(List<Double> values) {
            addCriterion("BLOCK_SIZE in", values, "blockSize");
            return (Criteria) this;
        }

        public Criteria andBlockSizeNotIn(List<Double> values) {
            addCriterion("BLOCK_SIZE not in", values, "blockSize");
            return (Criteria) this;
        }

        public Criteria andBlockSizeBetween(Double value1, Double value2) {
            addCriterion("BLOCK_SIZE between", value1, value2, "blockSize");
            return (Criteria) this;
        }

        public Criteria andBlockSizeNotBetween(Double value1, Double value2) {
            addCriterion("BLOCK_SIZE not between", value1, value2, "blockSize");
            return (Criteria) this;
        }

        public Criteria andModifDateIsNull() {
            addCriterion("MODIF_DATE is null");
            return (Criteria) this;
        }

        public Criteria andModifDateIsNotNull() {
            addCriterion("MODIF_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andModifDateEqualTo(Date value) {
            addCriterion("MODIF_DATE =", value, "modifDate");
            return (Criteria) this;
        }

        public Criteria andModifDateNotEqualTo(Date value) {
            addCriterion("MODIF_DATE <>", value, "modifDate");
            return (Criteria) this;
        }

        public Criteria andModifDateGreaterThan(Date value) {
            addCriterion("MODIF_DATE >", value, "modifDate");
            return (Criteria) this;
        }

        public Criteria andModifDateGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIF_DATE >=", value, "modifDate");
            return (Criteria) this;
        }

        public Criteria andModifDateLessThan(Date value) {
            addCriterion("MODIF_DATE <", value, "modifDate");
            return (Criteria) this;
        }

        public Criteria andModifDateLessThanOrEqualTo(Date value) {
            addCriterion("MODIF_DATE <=", value, "modifDate");
            return (Criteria) this;
        }

        public Criteria andModifDateIn(List<Date> values) {
            addCriterion("MODIF_DATE in", values, "modifDate");
            return (Criteria) this;
        }

        public Criteria andModifDateNotIn(List<Date> values) {
            addCriterion("MODIF_DATE not in", values, "modifDate");
            return (Criteria) this;
        }

        public Criteria andModifDateBetween(Date value1, Date value2) {
            addCriterion("MODIF_DATE between", value1, value2, "modifDate");
            return (Criteria) this;
        }

        public Criteria andModifDateNotBetween(Date value1, Date value2) {
            addCriterion("MODIF_DATE not between", value1, value2, "modifDate");
            return (Criteria) this;
        }

        public Criteria andPathIsNull() {
            addCriterion("PATH is null");
            return (Criteria) this;
        }

        public Criteria andPathIsNotNull() {
            addCriterion("PATH is not null");
            return (Criteria) this;
        }

        public Criteria andPathEqualTo(String value) {
            addCriterion("PATH =", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathNotEqualTo(String value) {
            addCriterion("PATH <>", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathGreaterThan(String value) {
            addCriterion("PATH >", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathGreaterThanOrEqualTo(String value) {
            addCriterion("PATH >=", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathLessThan(String value) {
            addCriterion("PATH <", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathLessThanOrEqualTo(String value) {
            addCriterion("PATH <=", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathLike(String value) {
            addCriterion("PATH like", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathNotLike(String value) {
            addCriterion("PATH not like", value, "path");
            return (Criteria) this;
        }

        public Criteria andPathIn(List<String> values) {
            addCriterion("PATH in", values, "path");
            return (Criteria) this;
        }

        public Criteria andPathNotIn(List<String> values) {
            addCriterion("PATH not in", values, "path");
            return (Criteria) this;
        }

        public Criteria andPathBetween(String value1, String value2) {
            addCriterion("PATH between", value1, value2, "path");
            return (Criteria) this;
        }

        public Criteria andPathNotBetween(String value1, String value2) {
            addCriterion("PATH not between", value1, value2, "path");
            return (Criteria) this;
        }

        public Criteria andColumn9IsNull() {
            addCriterion("COLUMN_9 is null");
            return (Criteria) this;
        }

        public Criteria andColumn9IsNotNull() {
            addCriterion("COLUMN_9 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn9EqualTo(String value) {
            addCriterion("COLUMN_9 =", value, "column9");
            return (Criteria) this;
        }

        public Criteria andColumn9NotEqualTo(String value) {
            addCriterion("COLUMN_9 <>", value, "column9");
            return (Criteria) this;
        }

        public Criteria andColumn9GreaterThan(String value) {
            addCriterion("COLUMN_9 >", value, "column9");
            return (Criteria) this;
        }

        public Criteria andColumn9GreaterThanOrEqualTo(String value) {
            addCriterion("COLUMN_9 >=", value, "column9");
            return (Criteria) this;
        }

        public Criteria andColumn9LessThan(String value) {
            addCriterion("COLUMN_9 <", value, "column9");
            return (Criteria) this;
        }

        public Criteria andColumn9LessThanOrEqualTo(String value) {
            addCriterion("COLUMN_9 <=", value, "column9");
            return (Criteria) this;
        }

        public Criteria andColumn9Like(String value) {
            addCriterion("COLUMN_9 like", value, "column9");
            return (Criteria) this;
        }

        public Criteria andColumn9NotLike(String value) {
            addCriterion("COLUMN_9 not like", value, "column9");
            return (Criteria) this;
        }

        public Criteria andColumn9In(List<String> values) {
            addCriterion("COLUMN_9 in", values, "column9");
            return (Criteria) this;
        }

        public Criteria andColumn9NotIn(List<String> values) {
            addCriterion("COLUMN_9 not in", values, "column9");
            return (Criteria) this;
        }

        public Criteria andColumn9Between(String value1, String value2) {
            addCriterion("COLUMN_9 between", value1, value2, "column9");
            return (Criteria) this;
        }

        public Criteria andColumn9NotBetween(String value1, String value2) {
            addCriterion("COLUMN_9 not between", value1, value2, "column9");
            return (Criteria) this;
        }

        public Criteria andColumn10IsNull() {
            addCriterion("COLUMN_10 is null");
            return (Criteria) this;
        }

        public Criteria andColumn10IsNotNull() {
            addCriterion("COLUMN_10 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn10EqualTo(String value) {
            addCriterion("COLUMN_10 =", value, "column10");
            return (Criteria) this;
        }

        public Criteria andColumn10NotEqualTo(String value) {
            addCriterion("COLUMN_10 <>", value, "column10");
            return (Criteria) this;
        }

        public Criteria andColumn10GreaterThan(String value) {
            addCriterion("COLUMN_10 >", value, "column10");
            return (Criteria) this;
        }

        public Criteria andColumn10GreaterThanOrEqualTo(String value) {
            addCriterion("COLUMN_10 >=", value, "column10");
            return (Criteria) this;
        }

        public Criteria andColumn10LessThan(String value) {
            addCriterion("COLUMN_10 <", value, "column10");
            return (Criteria) this;
        }

        public Criteria andColumn10LessThanOrEqualTo(String value) {
            addCriterion("COLUMN_10 <=", value, "column10");
            return (Criteria) this;
        }

        public Criteria andColumn10Like(String value) {
            addCriterion("COLUMN_10 like", value, "column10");
            return (Criteria) this;
        }

        public Criteria andColumn10NotLike(String value) {
            addCriterion("COLUMN_10 not like", value, "column10");
            return (Criteria) this;
        }

        public Criteria andColumn10In(List<String> values) {
            addCriterion("COLUMN_10 in", values, "column10");
            return (Criteria) this;
        }

        public Criteria andColumn10NotIn(List<String> values) {
            addCriterion("COLUMN_10 not in", values, "column10");
            return (Criteria) this;
        }

        public Criteria andColumn10Between(String value1, String value2) {
            addCriterion("COLUMN_10 between", value1, value2, "column10");
            return (Criteria) this;
        }

        public Criteria andColumn10NotBetween(String value1, String value2) {
            addCriterion("COLUMN_10 not between", value1, value2, "column10");
            return (Criteria) this;
        }

        public Criteria andColumn11IsNull() {
            addCriterion("COLUMN_11 is null");
            return (Criteria) this;
        }

        public Criteria andColumn11IsNotNull() {
            addCriterion("COLUMN_11 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn11EqualTo(String value) {
            addCriterion("COLUMN_11 =", value, "column11");
            return (Criteria) this;
        }

        public Criteria andColumn11NotEqualTo(String value) {
            addCriterion("COLUMN_11 <>", value, "column11");
            return (Criteria) this;
        }

        public Criteria andColumn11GreaterThan(String value) {
            addCriterion("COLUMN_11 >", value, "column11");
            return (Criteria) this;
        }

        public Criteria andColumn11GreaterThanOrEqualTo(String value) {
            addCriterion("COLUMN_11 >=", value, "column11");
            return (Criteria) this;
        }

        public Criteria andColumn11LessThan(String value) {
            addCriterion("COLUMN_11 <", value, "column11");
            return (Criteria) this;
        }

        public Criteria andColumn11LessThanOrEqualTo(String value) {
            addCriterion("COLUMN_11 <=", value, "column11");
            return (Criteria) this;
        }

        public Criteria andColumn11Like(String value) {
            addCriterion("COLUMN_11 like", value, "column11");
            return (Criteria) this;
        }

        public Criteria andColumn11NotLike(String value) {
            addCriterion("COLUMN_11 not like", value, "column11");
            return (Criteria) this;
        }

        public Criteria andColumn11In(List<String> values) {
            addCriterion("COLUMN_11 in", values, "column11");
            return (Criteria) this;
        }

        public Criteria andColumn11NotIn(List<String> values) {
            addCriterion("COLUMN_11 not in", values, "column11");
            return (Criteria) this;
        }

        public Criteria andColumn11Between(String value1, String value2) {
            addCriterion("COLUMN_11 between", value1, value2, "column11");
            return (Criteria) this;
        }

        public Criteria andColumn11NotBetween(String value1, String value2) {
            addCriterion("COLUMN_11 not between", value1, value2, "column11");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NWIDP.IMP_XQD_FILEBLOCKS
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NWIDP.IMP_XQD_FILEBLOCKS
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}