package com.yfny.corepojo.entity.demandform.model;

public class XqdSjqx {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_SJQX.XXBS
     *
     * @mbggenerated
     */
    private String xxbs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_SJQX.JSBS
     *
     * @mbggenerated
     */
    private String jsbs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_SJQX.JGBS
     *
     * @mbggenerated
     */
    private String jgbs;

    public XqdSjqx(String xxbs, String jsbs, String jgbs) {
        this.xxbs = xxbs;
        this.jsbs = jsbs;
        this.jgbs = jgbs;
    }

    public XqdSjqx() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_SJQX.XXBS
     *
     * @return the value of NWIDP.IMP_XQD_SJQX.XXBS
     *
     * @mbggenerated
     */
    public String getXxbs() {
        return xxbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_SJQX.XXBS
     *
     * @param xxbs the value for NWIDP.IMP_XQD_SJQX.XXBS
     *
     * @mbggenerated
     */
    public void setXxbs(String xxbs) {
        this.xxbs = xxbs == null ? null : xxbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_SJQX.JSBS
     *
     * @return the value of NWIDP.IMP_XQD_SJQX.JSBS
     *
     * @mbggenerated
     */
    public String getJsbs() {
        return jsbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_SJQX.JSBS
     *
     * @param jsbs the value for NWIDP.IMP_XQD_SJQX.JSBS
     *
     * @mbggenerated
     */
    public void setJsbs(String jsbs) {
        this.jsbs = jsbs == null ? null : jsbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_SJQX.JGBS
     *
     * @return the value of NWIDP.IMP_XQD_SJQX.JGBS
     *
     * @mbggenerated
     */
    public String getJgbs() {
        return jgbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_SJQX.JGBS
     *
     * @param jgbs the value for NWIDP.IMP_XQD_SJQX.JGBS
     *
     * @mbggenerated
     */
    public void setJgbs(String jgbs) {
        this.jgbs = jgbs == null ? null : jgbs.trim();
    }
}