package com.yfny.corepojo.entity.demandform.model;

import java.util.List;

public class Xqdxx {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.XQDH
	 * @mbggenerated
	 */
	private String xqdh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.SQBMMC
	 * @mbggenerated
	 */
	private String sqbmmc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.TCSJ
	 * @mbggenerated
	 */
	private String tcsj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.XQMC
	 * @mbggenerated
	 */
	private String xqmc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.SQRXM
	 * @mbggenerated
	 */
	private String sqrxm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.SQRLXFS
	 * @mbggenerated
	 */
	private String sqrlxfs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.SQRYX
	 * @mbggenerated
	 */
	private String sqryx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.XQFL
	 * @mbggenerated
	 */
	private String xqfl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.QWWCSJ
	 * @mbggenerated
	 */
	private String qwwcsj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.CJRID
	 * @mbggenerated
	 */
	private String cjrid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.CJSJ
	 * @mbggenerated
	 */
	private String cjsj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.SHRID
	 * @mbggenerated
	 */
	private String shrid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.SHR
	 * @mbggenerated
	 */
	private String shr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.SHYJ
	 * @mbggenerated
	 */
	private String shyj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.SHSJ
	 * @mbggenerated
	 */
	private String shsj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.GDZT
	 * @mbggenerated
	 */
	private String gdzt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.TJSJ
	 * @mbggenerated
	 */
	private String tjsj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.XQZS
	 * @mbggenerated
	 */
	private String xqzs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.ZZID
	 * @mbggenerated
	 */
	private String zzid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.BMJB
	 * @mbggenerated
	 */
	private String bmjb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.WJSHQR
	 * @mbggenerated
	 */
	private String wjshqr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.SSHRID
	 * @mbggenerated
	 */
	private String sshrid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.SSHR
	 * @mbggenerated
	 */
	private String sshr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.SSHYJ
	 * @mbggenerated
	 */
	private String sshyj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.SSHSJ
	 * @mbggenerated
	 */
	private String sshsj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.WSHRID
	 * @mbggenerated
	 */
	private String wshrid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.WSHR
	 * @mbggenerated
	 */
	private String wshr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.WSHYJ
	 * @mbggenerated
	 */
	private String wshyj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NWIDP.IMP_XQD_XQDXX.WSHSJ
	 * @mbggenerated
	 */
	private String wshsj;

	//专业类别
	private String zylb;

	private Long shtlsj;

	private List<Object> zzids;

	//省级审核确认
	private String sjshqr;

	//流程实例ID
	private String taskId;

	public Xqdxx(String xqdh, String sqbmmc, String tcsj, String xqmc, String sqrxm, String sqrlxfs, String sqryx, String xqfl, String qwwcsj, String cjrid, String cjsj, String shrid, String shr, String shyj, String shsj, String gdzt, String tjsj, String xqzs, String zzid, String bmjb, String wjshqr, String sshrid, String sshr, String sshyj, String sshsj, String wshrid, String wshr, String wshyj, String wshsj, String zylb,Long shtlsj,String sjshqr,String taskId) {
		this.xqdh = xqdh;
		this.sqbmmc = sqbmmc;
		this.tcsj = tcsj;
		this.xqmc = xqmc;
		this.sqrxm = sqrxm;
		this.sqrlxfs = sqrlxfs;
		this.sqryx = sqryx;
		this.xqfl = xqfl;
		this.qwwcsj = qwwcsj;
		this.cjrid = cjrid;
		this.cjsj = cjsj;
		this.shrid = shrid;
		this.shr = shr;
		this.shyj = shyj;
		this.shsj = shsj;
		this.gdzt = gdzt;
		this.tjsj = tjsj;
		this.xqzs = xqzs;
		this.zzid = zzid;
		this.bmjb = bmjb;
		this.wjshqr = wjshqr;
		this.sshrid = sshrid;
		this.sshr = sshr;
		this.sshyj = sshyj;
		this.sshsj = sshsj;
		this.wshrid = wshrid;
		this.wshr = wshr;
		this.wshyj = wshyj;
		this.wshsj = wshsj;
		this.zylb = zylb;
		this.shtlsj = shtlsj;
		this.sjshqr = sjshqr;
		this.taskId = taskId;
	}

	public Xqdxx() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.XQDH
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.XQDH
	 * @mbggenerated
	 */
	public String getXqdh() {
		return xqdh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.XQDH
	 * @param xqdh  the value for NWIDP.IMP_XQD_XQDXX.XQDH
	 * @mbggenerated
	 */
	public void setXqdh(String xqdh) {
		this.xqdh = xqdh == null ? null : xqdh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.SQBMMC
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.SQBMMC
	 * @mbggenerated
	 */
	public String getSqbmmc() {
		return sqbmmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.SQBMMC
	 * @param sqbmmc  the value for NWIDP.IMP_XQD_XQDXX.SQBMMC
	 * @mbggenerated
	 */
	public void setSqbmmc(String sqbmmc) {
		this.sqbmmc = sqbmmc == null ? null : sqbmmc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.TCSJ
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.TCSJ
	 * @mbggenerated
	 */
	public String getTcsj() {
		return tcsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.TCSJ
	 * @param tcsj  the value for NWIDP.IMP_XQD_XQDXX.TCSJ
	 * @mbggenerated
	 */
	public void setTcsj(String tcsj) {
		this.tcsj = tcsj == null ? null : tcsj.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.XQMC
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.XQMC
	 * @mbggenerated
	 */
	public String getXqmc() {
		return xqmc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.XQMC
	 * @param xqmc  the value for NWIDP.IMP_XQD_XQDXX.XQMC
	 * @mbggenerated
	 */
	public void setXqmc(String xqmc) {
		this.xqmc = xqmc == null ? null : xqmc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.SQRXM
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.SQRXM
	 * @mbggenerated
	 */
	public String getSqrxm() {
		return sqrxm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.SQRXM
	 * @param sqrxm  the value for NWIDP.IMP_XQD_XQDXX.SQRXM
	 * @mbggenerated
	 */
	public void setSqrxm(String sqrxm) {
		this.sqrxm = sqrxm == null ? null : sqrxm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.SQRLXFS
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.SQRLXFS
	 * @mbggenerated
	 */
	public String getSqrlxfs() {
		return sqrlxfs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.SQRLXFS
	 * @param sqrlxfs  the value for NWIDP.IMP_XQD_XQDXX.SQRLXFS
	 * @mbggenerated
	 */
	public void setSqrlxfs(String sqrlxfs) {
		this.sqrlxfs = sqrlxfs == null ? null : sqrlxfs.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.SQRYX
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.SQRYX
	 * @mbggenerated
	 */
	public String getSqryx() {
		return sqryx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.SQRYX
	 * @param sqryx  the value for NWIDP.IMP_XQD_XQDXX.SQRYX
	 * @mbggenerated
	 */
	public void setSqryx(String sqryx) {
		this.sqryx = sqryx == null ? null : sqryx.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.XQFL
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.XQFL
	 * @mbggenerated
	 */
	public String getXqfl() {
		return xqfl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.XQFL
	 * @param xqfl  the value for NWIDP.IMP_XQD_XQDXX.XQFL
	 * @mbggenerated
	 */
	public void setXqfl(String xqfl) {
		this.xqfl = xqfl == null ? null : xqfl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.QWWCSJ
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.QWWCSJ
	 * @mbggenerated
	 */
	public String getQwwcsj() {
		return qwwcsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.QWWCSJ
	 * @param qwwcsj  the value for NWIDP.IMP_XQD_XQDXX.QWWCSJ
	 * @mbggenerated
	 */
	public void setQwwcsj(String qwwcsj) {
		this.qwwcsj = qwwcsj == null ? null : qwwcsj.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.CJRID
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.CJRID
	 * @mbggenerated
	 */
	public String getCjrid() {
		return cjrid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.CJRID
	 * @param cjrid  the value for NWIDP.IMP_XQD_XQDXX.CJRID
	 * @mbggenerated
	 */
	public void setCjrid(String cjrid) {
		this.cjrid = cjrid == null ? null : cjrid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.CJSJ
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.CJSJ
	 * @mbggenerated
	 */
	public String getCjsj() {
		return cjsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.CJSJ
	 * @param cjsj  the value for NWIDP.IMP_XQD_XQDXX.CJSJ
	 * @mbggenerated
	 */
	public void setCjsj(String cjsj) {
		this.cjsj = cjsj == null ? null : cjsj.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.SHRID
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.SHRID
	 * @mbggenerated
	 */
	public String getShrid() {
		return shrid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.SHRID
	 * @param shrid  the value for NWIDP.IMP_XQD_XQDXX.SHRID
	 * @mbggenerated
	 */
	public void setShrid(String shrid) {
		this.shrid = shrid == null ? null : shrid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.SHR
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.SHR
	 * @mbggenerated
	 */
	public String getShr() {
		return shr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.SHR
	 * @param shr  the value for NWIDP.IMP_XQD_XQDXX.SHR
	 * @mbggenerated
	 */
	public void setShr(String shr) {
		this.shr = shr == null ? null : shr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.SHYJ
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.SHYJ
	 * @mbggenerated
	 */
	public String getShyj() {
		return shyj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.SHYJ
	 * @param shyj  the value for NWIDP.IMP_XQD_XQDXX.SHYJ
	 * @mbggenerated
	 */
	public void setShyj(String shyj) {
		this.shyj = shyj == null ? null : shyj.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.SHSJ
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.SHSJ
	 * @mbggenerated
	 */
	public String getShsj() {
		return shsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.SHSJ
	 * @param shsj  the value for NWIDP.IMP_XQD_XQDXX.SHSJ
	 * @mbggenerated
	 */
	public void setShsj(String shsj) {
		this.shsj = shsj == null ? null : shsj.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.GDZT
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.GDZT
	 * @mbggenerated
	 */
	public String getGdzt() {
		return gdzt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.GDZT
	 * @param gdzt  the value for NWIDP.IMP_XQD_XQDXX.GDZT
	 * @mbggenerated
	 */
	public void setGdzt(String gdzt) {
		this.gdzt = gdzt == null ? null : gdzt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.TJSJ
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.TJSJ
	 * @mbggenerated
	 */
	public String getTjsj() {
		return tjsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.TJSJ
	 * @param tjsj  the value for NWIDP.IMP_XQD_XQDXX.TJSJ
	 * @mbggenerated
	 */
	public void setTjsj(String tjsj) {
		this.tjsj = tjsj == null ? null : tjsj.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.XQZS
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.XQZS
	 * @mbggenerated
	 */
	public String getXqzs() {
		return xqzs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.XQZS
	 * @param xqzs  the value for NWIDP.IMP_XQD_XQDXX.XQZS
	 * @mbggenerated
	 */
	public void setXqzs(String xqzs) {
		this.xqzs = xqzs == null ? null : xqzs.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.ZZID
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.ZZID
	 * @mbggenerated
	 */
	public String getZzid() {
		return zzid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.ZZID
	 * @param zzid  the value for NWIDP.IMP_XQD_XQDXX.ZZID
	 * @mbggenerated
	 */
	public void setZzid(String zzid) {
		this.zzid = zzid == null ? null : zzid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.BMJB
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.BMJB
	 * @mbggenerated
	 */
	public String getBmjb() {
		return bmjb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.BMJB
	 * @param bmjb  the value for NWIDP.IMP_XQD_XQDXX.BMJB
	 * @mbggenerated
	 */
	public void setBmjb(String bmjb) {
		this.bmjb = bmjb == null ? null : bmjb.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.WJSHQR
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.WJSHQR
	 * @mbggenerated
	 */
	public String getWjshqr() {
		return wjshqr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.WJSHQR
	 * @param wjshqr  the value for NWIDP.IMP_XQD_XQDXX.WJSHQR
	 * @mbggenerated
	 */
	public void setWjshqr(String wjshqr) {
		this.wjshqr = wjshqr == null ? null : wjshqr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.SSHRID
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.SSHRID
	 * @mbggenerated
	 */
	public String getSshrid() {
		return sshrid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.SSHRID
	 * @param sshrid  the value for NWIDP.IMP_XQD_XQDXX.SSHRID
	 * @mbggenerated
	 */
	public void setSshrid(String sshrid) {
		this.sshrid = sshrid == null ? null : sshrid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.SSHR
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.SSHR
	 * @mbggenerated
	 */
	public String getSshr() {
		return sshr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.SSHR
	 * @param sshr  the value for NWIDP.IMP_XQD_XQDXX.SSHR
	 * @mbggenerated
	 */
	public void setSshr(String sshr) {
		this.sshr = sshr == null ? null : sshr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.SSHYJ
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.SSHYJ
	 * @mbggenerated
	 */
	public String getSshyj() {
		return sshyj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.SSHYJ
	 * @param sshyj  the value for NWIDP.IMP_XQD_XQDXX.SSHYJ
	 * @mbggenerated
	 */
	public void setSshyj(String sshyj) {
		this.sshyj = sshyj == null ? null : sshyj.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.SSHSJ
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.SSHSJ
	 * @mbggenerated
	 */
	public String getSshsj() {
		return sshsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.SSHSJ
	 * @param sshsj  the value for NWIDP.IMP_XQD_XQDXX.SSHSJ
	 * @mbggenerated
	 */
	public void setSshsj(String sshsj) {
		this.sshsj = sshsj == null ? null : sshsj.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.WSHRID
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.WSHRID
	 * @mbggenerated
	 */
	public String getWshrid() {
		return wshrid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.WSHRID
	 * @param wshrid  the value for NWIDP.IMP_XQD_XQDXX.WSHRID
	 * @mbggenerated
	 */
	public void setWshrid(String wshrid) {
		this.wshrid = wshrid == null ? null : wshrid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.WSHR
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.WSHR
	 * @mbggenerated
	 */
	public String getWshr() {
		return wshr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.WSHR
	 * @param wshr  the value for NWIDP.IMP_XQD_XQDXX.WSHR
	 * @mbggenerated
	 */
	public void setWshr(String wshr) {
		this.wshr = wshr == null ? null : wshr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.WSHYJ
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.WSHYJ
	 * @mbggenerated
	 */
	public String getWshyj() {
		return wshyj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.WSHYJ
	 * @param wshyj  the value for NWIDP.IMP_XQD_XQDXX.WSHYJ
	 * @mbggenerated
	 */
	public void setWshyj(String wshyj) {
		this.wshyj = wshyj == null ? null : wshyj.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NWIDP.IMP_XQD_XQDXX.WSHSJ
	 * @return  the value of NWIDP.IMP_XQD_XQDXX.WSHSJ
	 * @mbggenerated
	 */
	public String getWshsj() {
		return wshsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NWIDP.IMP_XQD_XQDXX.WSHSJ
	 * @param wshsj  the value for NWIDP.IMP_XQD_XQDXX.WSHSJ
	 * @mbggenerated
	 */
	public void setWshsj(String wshsj) {
		this.wshsj = wshsj == null ? null : wshsj.trim();
	}

	public String getZylb() {
		return zylb;
	}

	public void setZylb(String zylb) {
		this.zylb = zylb;
	}

	public Long getShtlsj() {
		return shtlsj;
	}

	public void setShtlsj(Long shtlsj) {
		this.shtlsj = shtlsj;
	}

	public String getSjshqr() {
		return sjshqr;
	}

	public void setSjshqr(String sjshqr) {
		this.sjshqr = sjshqr;
	}

	public List getZzids() {
		return zzids;
	}

	public void setZzids(List zzids) {
		this.zzids = zzids;
	}

	public String getTaskId() {
		return taskId;
	}

	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	public Xqdxx(String xqdh, String sqbmmc, String tcsj, String xqmc, String sqrxm, String sqrlxfs, String sqryx, String xqfl, String qwwcsj, String cjrid, String cjsj, String shrid, String shr, String shyj, String shsj, String gdzt, String tjsj, String xqzs, String zzid, String zylb, Long shtlsj) {
        this.xqdh = xqdh;
        this.sqbmmc = sqbmmc;
        this.tcsj = tcsj;
        this.xqmc = xqmc;
        this.sqrxm = sqrxm;
        this.sqrlxfs = sqrlxfs;
        this.sqryx = sqryx;
        this.xqfl = xqfl;
        this.qwwcsj = qwwcsj;
        this.cjrid = cjrid;
        this.cjsj = cjsj;
        this.shrid = shrid;
        this.shr = shr;
        this.shyj = shyj;
        this.shsj = shsj;
        this.gdzt = gdzt;
        this.tjsj = tjsj;
        this.xqzs = xqzs;
        this.zzid = zzid;
        this.zylb = zylb;
        this.shtlsj = shtlsj;
    }

}
