package com.yfny.corepojo.entity.demandform.model;

public class Xtgn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_XTGN.GNBS
     *
     * @mbggenerated
     */
    private String gnbs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_XTGN.GNMC
     *
     * @mbggenerated
     */
    private String gnmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_XTGN.ICON
     *
     * @mbggenerated
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_XTGN.GNURL
     *
     * @mbggenerated
     */
    private String gnurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_XTGN.FJD
     *
     * @mbggenerated
     */
    private String fjd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_XTGN.SX
     *
     * @mbggenerated
     */
    private Short sx;

    public Xtgn(String gnbs, String gnmc, String icon, String gnurl, String fjd, Short sx) {
        this.gnbs = gnbs;
        this.gnmc = gnmc;
        this.icon = icon;
        this.gnurl = gnurl;
        this.fjd = fjd;
        this.sx = sx;
    }

    public Xtgn() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_XTGN.GNBS
     *
     * @return the value of NWIDP.IMP_XQD_XTGN.GNBS
     *
     * @mbggenerated
     */
    public String getGnbs() {
        return gnbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_XTGN.GNBS
     *
     * @param gnbs the value for NWIDP.IMP_XQD_XTGN.GNBS
     *
     * @mbggenerated
     */
    public void setGnbs(String gnbs) {
        this.gnbs = gnbs == null ? null : gnbs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_XTGN.GNMC
     *
     * @return the value of NWIDP.IMP_XQD_XTGN.GNMC
     *
     * @mbggenerated
     */
    public String getGnmc() {
        return gnmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_XTGN.GNMC
     *
     * @param gnmc the value for NWIDP.IMP_XQD_XTGN.GNMC
     *
     * @mbggenerated
     */
    public void setGnmc(String gnmc) {
        this.gnmc = gnmc == null ? null : gnmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_XTGN.ICON
     *
     * @return the value of NWIDP.IMP_XQD_XTGN.ICON
     *
     * @mbggenerated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_XTGN.ICON
     *
     * @param icon the value for NWIDP.IMP_XQD_XTGN.ICON
     *
     * @mbggenerated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_XTGN.GNURL
     *
     * @return the value of NWIDP.IMP_XQD_XTGN.GNURL
     *
     * @mbggenerated
     */
    public String getGnurl() {
        return gnurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_XTGN.GNURL
     *
     * @param gnurl the value for NWIDP.IMP_XQD_XTGN.GNURL
     *
     * @mbggenerated
     */
    public void setGnurl(String gnurl) {
        this.gnurl = gnurl == null ? null : gnurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_XTGN.FJD
     *
     * @return the value of NWIDP.IMP_XQD_XTGN.FJD
     *
     * @mbggenerated
     */
    public String getFjd() {
        return fjd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_XTGN.FJD
     *
     * @param fjd the value for NWIDP.IMP_XQD_XTGN.FJD
     *
     * @mbggenerated
     */
    public void setFjd(String fjd) {
        this.fjd = fjd == null ? null : fjd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_XTGN.SX
     *
     * @return the value of NWIDP.IMP_XQD_XTGN.SX
     *
     * @mbggenerated
     */
    public Short getSx() {
        return sx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_XTGN.SX
     *
     * @param sx the value for NWIDP.IMP_XQD_XTGN.SX
     *
     * @mbggenerated
     */
    public void setSx(Short sx) {
        this.sx = sx;
    }
}