package com.yfny.corepojo.entity.demandform.model;

import java.util.ArrayList;
import java.util.List;

public class XtgnExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NWIDP.IMP_XQD_XTGN
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NWIDP.IMP_XQD_XTGN
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NWIDP.IMP_XQD_XTGN
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_XTGN
     *
     * @mbggenerated
     */
    public XtgnExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_XTGN
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_XTGN
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_XTGN
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_XTGN
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_XTGN
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_XTGN
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_XTGN
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_XTGN
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_XTGN
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_XTGN
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NWIDP.IMP_XQD_XTGN
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGnbsIsNull() {
            addCriterion("GNBS is null");
            return (Criteria) this;
        }

        public Criteria andGnbsIsNotNull() {
            addCriterion("GNBS is not null");
            return (Criteria) this;
        }

        public Criteria andGnbsEqualTo(String value) {
            addCriterion("GNBS =", value, "gnbs");
            return (Criteria) this;
        }

        public Criteria andGnbsNotEqualTo(String value) {
            addCriterion("GNBS <>", value, "gnbs");
            return (Criteria) this;
        }

        public Criteria andGnbsGreaterThan(String value) {
            addCriterion("GNBS >", value, "gnbs");
            return (Criteria) this;
        }

        public Criteria andGnbsGreaterThanOrEqualTo(String value) {
            addCriterion("GNBS >=", value, "gnbs");
            return (Criteria) this;
        }

        public Criteria andGnbsLessThan(String value) {
            addCriterion("GNBS <", value, "gnbs");
            return (Criteria) this;
        }

        public Criteria andGnbsLessThanOrEqualTo(String value) {
            addCriterion("GNBS <=", value, "gnbs");
            return (Criteria) this;
        }

        public Criteria andGnbsLike(String value) {
            addCriterion("GNBS like", value, "gnbs");
            return (Criteria) this;
        }

        public Criteria andGnbsNotLike(String value) {
            addCriterion("GNBS not like", value, "gnbs");
            return (Criteria) this;
        }

        public Criteria andGnbsIn(List<String> values) {
            addCriterion("GNBS in", values, "gnbs");
            return (Criteria) this;
        }

        public Criteria andGnbsNotIn(List<String> values) {
            addCriterion("GNBS not in", values, "gnbs");
            return (Criteria) this;
        }

        public Criteria andGnbsBetween(String value1, String value2) {
            addCriterion("GNBS between", value1, value2, "gnbs");
            return (Criteria) this;
        }

        public Criteria andGnbsNotBetween(String value1, String value2) {
            addCriterion("GNBS not between", value1, value2, "gnbs");
            return (Criteria) this;
        }

        public Criteria andGnmcIsNull() {
            addCriterion("GNMC is null");
            return (Criteria) this;
        }

        public Criteria andGnmcIsNotNull() {
            addCriterion("GNMC is not null");
            return (Criteria) this;
        }

        public Criteria andGnmcEqualTo(String value) {
            addCriterion("GNMC =", value, "gnmc");
            return (Criteria) this;
        }

        public Criteria andGnmcNotEqualTo(String value) {
            addCriterion("GNMC <>", value, "gnmc");
            return (Criteria) this;
        }

        public Criteria andGnmcGreaterThan(String value) {
            addCriterion("GNMC >", value, "gnmc");
            return (Criteria) this;
        }

        public Criteria andGnmcGreaterThanOrEqualTo(String value) {
            addCriterion("GNMC >=", value, "gnmc");
            return (Criteria) this;
        }

        public Criteria andGnmcLessThan(String value) {
            addCriterion("GNMC <", value, "gnmc");
            return (Criteria) this;
        }

        public Criteria andGnmcLessThanOrEqualTo(String value) {
            addCriterion("GNMC <=", value, "gnmc");
            return (Criteria) this;
        }

        public Criteria andGnmcLike(String value) {
            addCriterion("GNMC like", value, "gnmc");
            return (Criteria) this;
        }

        public Criteria andGnmcNotLike(String value) {
            addCriterion("GNMC not like", value, "gnmc");
            return (Criteria) this;
        }

        public Criteria andGnmcIn(List<String> values) {
            addCriterion("GNMC in", values, "gnmc");
            return (Criteria) this;
        }

        public Criteria andGnmcNotIn(List<String> values) {
            addCriterion("GNMC not in", values, "gnmc");
            return (Criteria) this;
        }

        public Criteria andGnmcBetween(String value1, String value2) {
            addCriterion("GNMC between", value1, value2, "gnmc");
            return (Criteria) this;
        }

        public Criteria andGnmcNotBetween(String value1, String value2) {
            addCriterion("GNMC not between", value1, value2, "gnmc");
            return (Criteria) this;
        }

        public Criteria andIconIsNull() {
            addCriterion("ICON is null");
            return (Criteria) this;
        }

        public Criteria andIconIsNotNull() {
            addCriterion("ICON is not null");
            return (Criteria) this;
        }

        public Criteria andIconEqualTo(String value) {
            addCriterion("ICON =", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotEqualTo(String value) {
            addCriterion("ICON <>", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconGreaterThan(String value) {
            addCriterion("ICON >", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconGreaterThanOrEqualTo(String value) {
            addCriterion("ICON >=", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconLessThan(String value) {
            addCriterion("ICON <", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconLessThanOrEqualTo(String value) {
            addCriterion("ICON <=", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconLike(String value) {
            addCriterion("ICON like", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotLike(String value) {
            addCriterion("ICON not like", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconIn(List<String> values) {
            addCriterion("ICON in", values, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotIn(List<String> values) {
            addCriterion("ICON not in", values, "icon");
            return (Criteria) this;
        }

        public Criteria andIconBetween(String value1, String value2) {
            addCriterion("ICON between", value1, value2, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotBetween(String value1, String value2) {
            addCriterion("ICON not between", value1, value2, "icon");
            return (Criteria) this;
        }

        public Criteria andGnurlIsNull() {
            addCriterion("GNURL is null");
            return (Criteria) this;
        }

        public Criteria andGnurlIsNotNull() {
            addCriterion("GNURL is not null");
            return (Criteria) this;
        }

        public Criteria andGnurlEqualTo(String value) {
            addCriterion("GNURL =", value, "gnurl");
            return (Criteria) this;
        }

        public Criteria andGnurlNotEqualTo(String value) {
            addCriterion("GNURL <>", value, "gnurl");
            return (Criteria) this;
        }

        public Criteria andGnurlGreaterThan(String value) {
            addCriterion("GNURL >", value, "gnurl");
            return (Criteria) this;
        }

        public Criteria andGnurlGreaterThanOrEqualTo(String value) {
            addCriterion("GNURL >=", value, "gnurl");
            return (Criteria) this;
        }

        public Criteria andGnurlLessThan(String value) {
            addCriterion("GNURL <", value, "gnurl");
            return (Criteria) this;
        }

        public Criteria andGnurlLessThanOrEqualTo(String value) {
            addCriterion("GNURL <=", value, "gnurl");
            return (Criteria) this;
        }

        public Criteria andGnurlLike(String value) {
            addCriterion("GNURL like", value, "gnurl");
            return (Criteria) this;
        }

        public Criteria andGnurlNotLike(String value) {
            addCriterion("GNURL not like", value, "gnurl");
            return (Criteria) this;
        }

        public Criteria andGnurlIn(List<String> values) {
            addCriterion("GNURL in", values, "gnurl");
            return (Criteria) this;
        }

        public Criteria andGnurlNotIn(List<String> values) {
            addCriterion("GNURL not in", values, "gnurl");
            return (Criteria) this;
        }

        public Criteria andGnurlBetween(String value1, String value2) {
            addCriterion("GNURL between", value1, value2, "gnurl");
            return (Criteria) this;
        }

        public Criteria andGnurlNotBetween(String value1, String value2) {
            addCriterion("GNURL not between", value1, value2, "gnurl");
            return (Criteria) this;
        }

        public Criteria andFjdIsNull() {
            addCriterion("FJD is null");
            return (Criteria) this;
        }

        public Criteria andFjdIsNotNull() {
            addCriterion("FJD is not null");
            return (Criteria) this;
        }

        public Criteria andFjdEqualTo(String value) {
            addCriterion("FJD =", value, "fjd");
            return (Criteria) this;
        }

        public Criteria andFjdNotEqualTo(String value) {
            addCriterion("FJD <>", value, "fjd");
            return (Criteria) this;
        }

        public Criteria andFjdGreaterThan(String value) {
            addCriterion("FJD >", value, "fjd");
            return (Criteria) this;
        }

        public Criteria andFjdGreaterThanOrEqualTo(String value) {
            addCriterion("FJD >=", value, "fjd");
            return (Criteria) this;
        }

        public Criteria andFjdLessThan(String value) {
            addCriterion("FJD <", value, "fjd");
            return (Criteria) this;
        }

        public Criteria andFjdLessThanOrEqualTo(String value) {
            addCriterion("FJD <=", value, "fjd");
            return (Criteria) this;
        }

        public Criteria andFjdLike(String value) {
            addCriterion("FJD like", value, "fjd");
            return (Criteria) this;
        }

        public Criteria andFjdNotLike(String value) {
            addCriterion("FJD not like", value, "fjd");
            return (Criteria) this;
        }

        public Criteria andFjdIn(List<String> values) {
            addCriterion("FJD in", values, "fjd");
            return (Criteria) this;
        }

        public Criteria andFjdNotIn(List<String> values) {
            addCriterion("FJD not in", values, "fjd");
            return (Criteria) this;
        }

        public Criteria andFjdBetween(String value1, String value2) {
            addCriterion("FJD between", value1, value2, "fjd");
            return (Criteria) this;
        }

        public Criteria andFjdNotBetween(String value1, String value2) {
            addCriterion("FJD not between", value1, value2, "fjd");
            return (Criteria) this;
        }

        public Criteria andSxIsNull() {
            addCriterion("SX is null");
            return (Criteria) this;
        }

        public Criteria andSxIsNotNull() {
            addCriterion("SX is not null");
            return (Criteria) this;
        }

        public Criteria andSxEqualTo(Short value) {
            addCriterion("SX =", value, "sx");
            return (Criteria) this;
        }

        public Criteria andSxNotEqualTo(Short value) {
            addCriterion("SX <>", value, "sx");
            return (Criteria) this;
        }

        public Criteria andSxGreaterThan(Short value) {
            addCriterion("SX >", value, "sx");
            return (Criteria) this;
        }

        public Criteria andSxGreaterThanOrEqualTo(Short value) {
            addCriterion("SX >=", value, "sx");
            return (Criteria) this;
        }

        public Criteria andSxLessThan(Short value) {
            addCriterion("SX <", value, "sx");
            return (Criteria) this;
        }

        public Criteria andSxLessThanOrEqualTo(Short value) {
            addCriterion("SX <=", value, "sx");
            return (Criteria) this;
        }

        public Criteria andSxIn(List<Short> values) {
            addCriterion("SX in", values, "sx");
            return (Criteria) this;
        }

        public Criteria andSxNotIn(List<Short> values) {
            addCriterion("SX not in", values, "sx");
            return (Criteria) this;
        }

        public Criteria andSxBetween(Short value1, Short value2) {
            addCriterion("SX between", value1, value2, "sx");
            return (Criteria) this;
        }

        public Criteria andSxNotBetween(Short value1, Short value2) {
            addCriterion("SX not between", value1, value2, "sx");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NWIDP.IMP_XQD_XTGN
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NWIDP.IMP_XQD_XTGN
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}