package com.yfny.corepojo.entity.demandform.model;

import java.util.ArrayList;
import java.util.List;

public class YwyxxExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NWIDP.IMP_XQD_YWYXX
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NWIDP.IMP_XQD_YWYXX
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NWIDP.IMP_XQD_YWYXX
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_YWYXX
     *
     * @mbggenerated
     */
    public YwyxxExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_YWYXX
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_YWYXX
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_YWYXX
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_YWYXX
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_YWYXX
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_YWYXX
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_YWYXX
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_YWYXX
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_YWYXX
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_YWYXX
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NWIDP.IMP_XQD_YWYXX
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andYwybsIsNull() {
            addCriterion("YWYBS is null");
            return (Criteria) this;
        }

        public Criteria andYwybsIsNotNull() {
            addCriterion("YWYBS is not null");
            return (Criteria) this;
        }

        public Criteria andYwybsEqualTo(String value) {
            addCriterion("YWYBS =", value, "ywybs");
            return (Criteria) this;
        }

        public Criteria andYwybsNotEqualTo(String value) {
            addCriterion("YWYBS <>", value, "ywybs");
            return (Criteria) this;
        }

        public Criteria andYwybsGreaterThan(String value) {
            addCriterion("YWYBS >", value, "ywybs");
            return (Criteria) this;
        }

        public Criteria andYwybsGreaterThanOrEqualTo(String value) {
            addCriterion("YWYBS >=", value, "ywybs");
            return (Criteria) this;
        }

        public Criteria andYwybsLessThan(String value) {
            addCriterion("YWYBS <", value, "ywybs");
            return (Criteria) this;
        }

        public Criteria andYwybsLessThanOrEqualTo(String value) {
            addCriterion("YWYBS <=", value, "ywybs");
            return (Criteria) this;
        }

        public Criteria andYwybsLike(String value) {
            addCriterion("YWYBS like", value, "ywybs");
            return (Criteria) this;
        }

        public Criteria andYwybsNotLike(String value) {
            addCriterion("YWYBS not like", value, "ywybs");
            return (Criteria) this;
        }

        public Criteria andYwybsIn(List<String> values) {
            addCriterion("YWYBS in", values, "ywybs");
            return (Criteria) this;
        }

        public Criteria andYwybsNotIn(List<String> values) {
            addCriterion("YWYBS not in", values, "ywybs");
            return (Criteria) this;
        }

        public Criteria andYwybsBetween(String value1, String value2) {
            addCriterion("YWYBS between", value1, value2, "ywybs");
            return (Criteria) this;
        }

        public Criteria andYwybsNotBetween(String value1, String value2) {
            addCriterion("YWYBS not between", value1, value2, "ywybs");
            return (Criteria) this;
        }

        public Criteria andXqdhIsNull() {
            addCriterion("XQDH is null");
            return (Criteria) this;
        }

        public Criteria andXqdhIsNotNull() {
            addCriterion("XQDH is not null");
            return (Criteria) this;
        }

        public Criteria andXqdhEqualTo(String value) {
            addCriterion("XQDH =", value, "xqdh");
            return (Criteria) this;
        }

        public Criteria andXqdhNotEqualTo(String value) {
            addCriterion("XQDH <>", value, "xqdh");
            return (Criteria) this;
        }

        public Criteria andXqdhGreaterThan(String value) {
            addCriterion("XQDH >", value, "xqdh");
            return (Criteria) this;
        }

        public Criteria andXqdhGreaterThanOrEqualTo(String value) {
            addCriterion("XQDH >=", value, "xqdh");
            return (Criteria) this;
        }

        public Criteria andXqdhLessThan(String value) {
            addCriterion("XQDH <", value, "xqdh");
            return (Criteria) this;
        }

        public Criteria andXqdhLessThanOrEqualTo(String value) {
            addCriterion("XQDH <=", value, "xqdh");
            return (Criteria) this;
        }

        public Criteria andXqdhLike(String value) {
            addCriterion("XQDH like", value, "xqdh");
            return (Criteria) this;
        }

        public Criteria andXqdhNotLike(String value) {
            addCriterion("XQDH not like", value, "xqdh");
            return (Criteria) this;
        }

        public Criteria andXqdhIn(List<String> values) {
            addCriterion("XQDH in", values, "xqdh");
            return (Criteria) this;
        }

        public Criteria andXqdhNotIn(List<String> values) {
            addCriterion("XQDH not in", values, "xqdh");
            return (Criteria) this;
        }

        public Criteria andXqdhBetween(String value1, String value2) {
            addCriterion("XQDH between", value1, value2, "xqdh");
            return (Criteria) this;
        }

        public Criteria andXqdhNotBetween(String value1, String value2) {
            addCriterion("XQDH not between", value1, value2, "xqdh");
            return (Criteria) this;
        }

        public Criteria andSsywyIsNull() {
            addCriterion("SSYWY is null");
            return (Criteria) this;
        }

        public Criteria andSsywyIsNotNull() {
            addCriterion("SSYWY is not null");
            return (Criteria) this;
        }

        public Criteria andSsywyEqualTo(String value) {
            addCriterion("SSYWY =", value, "ssywy");
            return (Criteria) this;
        }

        public Criteria andSsywyNotEqualTo(String value) {
            addCriterion("SSYWY <>", value, "ssywy");
            return (Criteria) this;
        }

        public Criteria andSsywyGreaterThan(String value) {
            addCriterion("SSYWY >", value, "ssywy");
            return (Criteria) this;
        }

        public Criteria andSsywyGreaterThanOrEqualTo(String value) {
            addCriterion("SSYWY >=", value, "ssywy");
            return (Criteria) this;
        }

        public Criteria andSsywyLessThan(String value) {
            addCriterion("SSYWY <", value, "ssywy");
            return (Criteria) this;
        }

        public Criteria andSsywyLessThanOrEqualTo(String value) {
            addCriterion("SSYWY <=", value, "ssywy");
            return (Criteria) this;
        }

        public Criteria andSsywyLike(String value) {
            addCriterion("SSYWY like", value, "ssywy");
            return (Criteria) this;
        }

        public Criteria andSsywyNotLike(String value) {
            addCriterion("SSYWY not like", value, "ssywy");
            return (Criteria) this;
        }

        public Criteria andSsywyIn(List<String> values) {
            addCriterion("SSYWY in", values, "ssywy");
            return (Criteria) this;
        }

        public Criteria andSsywyNotIn(List<String> values) {
            addCriterion("SSYWY not in", values, "ssywy");
            return (Criteria) this;
        }

        public Criteria andSsywyBetween(String value1, String value2) {
            addCriterion("SSYWY between", value1, value2, "ssywy");
            return (Criteria) this;
        }

        public Criteria andSsywyNotBetween(String value1, String value2) {
            addCriterion("SSYWY not between", value1, value2, "ssywy");
            return (Criteria) this;
        }

        public Criteria andSsywflIsNull() {
            addCriterion("SSYWFL is null");
            return (Criteria) this;
        }

        public Criteria andSsywflIsNotNull() {
            addCriterion("SSYWFL is not null");
            return (Criteria) this;
        }

        public Criteria andSsywflEqualTo(String value) {
            addCriterion("SSYWFL =", value, "ssywfl");
            return (Criteria) this;
        }

        public Criteria andSsywflNotEqualTo(String value) {
            addCriterion("SSYWFL <>", value, "ssywfl");
            return (Criteria) this;
        }

        public Criteria andSsywflGreaterThan(String value) {
            addCriterion("SSYWFL >", value, "ssywfl");
            return (Criteria) this;
        }

        public Criteria andSsywflGreaterThanOrEqualTo(String value) {
            addCriterion("SSYWFL >=", value, "ssywfl");
            return (Criteria) this;
        }

        public Criteria andSsywflLessThan(String value) {
            addCriterion("SSYWFL <", value, "ssywfl");
            return (Criteria) this;
        }

        public Criteria andSsywflLessThanOrEqualTo(String value) {
            addCriterion("SSYWFL <=", value, "ssywfl");
            return (Criteria) this;
        }

        public Criteria andSsywflLike(String value) {
            addCriterion("SSYWFL like", value, "ssywfl");
            return (Criteria) this;
        }

        public Criteria andSsywflNotLike(String value) {
            addCriterion("SSYWFL not like", value, "ssywfl");
            return (Criteria) this;
        }

        public Criteria andSsywflIn(List<String> values) {
            addCriterion("SSYWFL in", values, "ssywfl");
            return (Criteria) this;
        }

        public Criteria andSsywflNotIn(List<String> values) {
            addCriterion("SSYWFL not in", values, "ssywfl");
            return (Criteria) this;
        }

        public Criteria andSsywflBetween(String value1, String value2) {
            addCriterion("SSYWFL between", value1, value2, "ssywfl");
            return (Criteria) this;
        }

        public Criteria andSsywflNotBetween(String value1, String value2) {
            addCriterion("SSYWFL not between", value1, value2, "ssywfl");
            return (Criteria) this;
        }

        public Criteria andSsywmcIsNull() {
            addCriterion("SSYWMC is null");
            return (Criteria) this;
        }

        public Criteria andSsywmcIsNotNull() {
            addCriterion("SSYWMC is not null");
            return (Criteria) this;
        }

        public Criteria andSsywmcEqualTo(String value) {
            addCriterion("SSYWMC =", value, "ssywmc");
            return (Criteria) this;
        }

        public Criteria andSsywmcNotEqualTo(String value) {
            addCriterion("SSYWMC <>", value, "ssywmc");
            return (Criteria) this;
        }

        public Criteria andSsywmcGreaterThan(String value) {
            addCriterion("SSYWMC >", value, "ssywmc");
            return (Criteria) this;
        }

        public Criteria andSsywmcGreaterThanOrEqualTo(String value) {
            addCriterion("SSYWMC >=", value, "ssywmc");
            return (Criteria) this;
        }

        public Criteria andSsywmcLessThan(String value) {
            addCriterion("SSYWMC <", value, "ssywmc");
            return (Criteria) this;
        }

        public Criteria andSsywmcLessThanOrEqualTo(String value) {
            addCriterion("SSYWMC <=", value, "ssywmc");
            return (Criteria) this;
        }

        public Criteria andSsywmcLike(String value) {
            addCriterion("SSYWMC like", value, "ssywmc");
            return (Criteria) this;
        }

        public Criteria andSsywmcNotLike(String value) {
            addCriterion("SSYWMC not like", value, "ssywmc");
            return (Criteria) this;
        }

        public Criteria andSsywmcIn(List<String> values) {
            addCriterion("SSYWMC in", values, "ssywmc");
            return (Criteria) this;
        }

        public Criteria andSsywmcNotIn(List<String> values) {
            addCriterion("SSYWMC not in", values, "ssywmc");
            return (Criteria) this;
        }

        public Criteria andSsywmcBetween(String value1, String value2) {
            addCriterion("SSYWMC between", value1, value2, "ssywmc");
            return (Criteria) this;
        }

        public Criteria andSsywmcNotBetween(String value1, String value2) {
            addCriterion("SSYWMC not between", value1, value2, "ssywmc");
            return (Criteria) this;
        }

        public Criteria andSsywmsIsNull() {
            addCriterion("SSYWMS is null");
            return (Criteria) this;
        }

        public Criteria andSsywmsIsNotNull() {
            addCriterion("SSYWMS is not null");
            return (Criteria) this;
        }

        public Criteria andSsywmsEqualTo(String value) {
            addCriterion("SSYWMS =", value, "ssywms");
            return (Criteria) this;
        }

        public Criteria andSsywmsNotEqualTo(String value) {
            addCriterion("SSYWMS <>", value, "ssywms");
            return (Criteria) this;
        }

        public Criteria andSsywmsGreaterThan(String value) {
            addCriterion("SSYWMS >", value, "ssywms");
            return (Criteria) this;
        }

        public Criteria andSsywmsGreaterThanOrEqualTo(String value) {
            addCriterion("SSYWMS >=", value, "ssywms");
            return (Criteria) this;
        }

        public Criteria andSsywmsLessThan(String value) {
            addCriterion("SSYWMS <", value, "ssywms");
            return (Criteria) this;
        }

        public Criteria andSsywmsLessThanOrEqualTo(String value) {
            addCriterion("SSYWMS <=", value, "ssywms");
            return (Criteria) this;
        }

        public Criteria andSsywmsLike(String value) {
            addCriterion("SSYWMS like", value, "ssywms");
            return (Criteria) this;
        }

        public Criteria andSsywmsNotLike(String value) {
            addCriterion("SSYWMS not like", value, "ssywms");
            return (Criteria) this;
        }

        public Criteria andSsywmsIn(List<String> values) {
            addCriterion("SSYWMS in", values, "ssywms");
            return (Criteria) this;
        }

        public Criteria andSsywmsNotIn(List<String> values) {
            addCriterion("SSYWMS not in", values, "ssywms");
            return (Criteria) this;
        }

        public Criteria andSsywmsBetween(String value1, String value2) {
            addCriterion("SSYWMS between", value1, value2, "ssywms");
            return (Criteria) this;
        }

        public Criteria andSsywmsNotBetween(String value1, String value2) {
            addCriterion("SSYWMS not between", value1, value2, "ssywms");
            return (Criteria) this;
        }

        public Criteria andSsywgfclIsNull() {
            addCriterion("SSYWGFCL is null");
            return (Criteria) this;
        }

        public Criteria andSsywgfclIsNotNull() {
            addCriterion("SSYWGFCL is not null");
            return (Criteria) this;
        }

        public Criteria andSsywgfclEqualTo(String value) {
            addCriterion("SSYWGFCL =", value, "ssywgfcl");
            return (Criteria) this;
        }

        public Criteria andSsywgfclNotEqualTo(String value) {
            addCriterion("SSYWGFCL <>", value, "ssywgfcl");
            return (Criteria) this;
        }

        public Criteria andSsywgfclGreaterThan(String value) {
            addCriterion("SSYWGFCL >", value, "ssywgfcl");
            return (Criteria) this;
        }

        public Criteria andSsywgfclGreaterThanOrEqualTo(String value) {
            addCriterion("SSYWGFCL >=", value, "ssywgfcl");
            return (Criteria) this;
        }

        public Criteria andSsywgfclLessThan(String value) {
            addCriterion("SSYWGFCL <", value, "ssywgfcl");
            return (Criteria) this;
        }

        public Criteria andSsywgfclLessThanOrEqualTo(String value) {
            addCriterion("SSYWGFCL <=", value, "ssywgfcl");
            return (Criteria) this;
        }

        public Criteria andSsywgfclLike(String value) {
            addCriterion("SSYWGFCL like", value, "ssywgfcl");
            return (Criteria) this;
        }

        public Criteria andSsywgfclNotLike(String value) {
            addCriterion("SSYWGFCL not like", value, "ssywgfcl");
            return (Criteria) this;
        }

        public Criteria andSsywgfclIn(List<String> values) {
            addCriterion("SSYWGFCL in", values, "ssywgfcl");
            return (Criteria) this;
        }

        public Criteria andSsywgfclNotIn(List<String> values) {
            addCriterion("SSYWGFCL not in", values, "ssywgfcl");
            return (Criteria) this;
        }

        public Criteria andSsywgfclBetween(String value1, String value2) {
            addCriterion("SSYWGFCL between", value1, value2, "ssywgfcl");
            return (Criteria) this;
        }

        public Criteria andSsywgfclNotBetween(String value1, String value2) {
            addCriterion("SSYWGFCL not between", value1, value2, "ssywgfcl");
            return (Criteria) this;
        }

        public Criteria andYwlcmcIsNull() {
            addCriterion("YWLCMC is null");
            return (Criteria) this;
        }

        public Criteria andYwlcmcIsNotNull() {
            addCriterion("YWLCMC is not null");
            return (Criteria) this;
        }

        public Criteria andYwlcmcEqualTo(String value) {
            addCriterion("YWLCMC =", value, "ywlcmc");
            return (Criteria) this;
        }

        public Criteria andYwlcmcNotEqualTo(String value) {
            addCriterion("YWLCMC <>", value, "ywlcmc");
            return (Criteria) this;
        }

        public Criteria andYwlcmcGreaterThan(String value) {
            addCriterion("YWLCMC >", value, "ywlcmc");
            return (Criteria) this;
        }

        public Criteria andYwlcmcGreaterThanOrEqualTo(String value) {
            addCriterion("YWLCMC >=", value, "ywlcmc");
            return (Criteria) this;
        }

        public Criteria andYwlcmcLessThan(String value) {
            addCriterion("YWLCMC <", value, "ywlcmc");
            return (Criteria) this;
        }

        public Criteria andYwlcmcLessThanOrEqualTo(String value) {
            addCriterion("YWLCMC <=", value, "ywlcmc");
            return (Criteria) this;
        }

        public Criteria andYwlcmcLike(String value) {
            addCriterion("YWLCMC like", value, "ywlcmc");
            return (Criteria) this;
        }

        public Criteria andYwlcmcNotLike(String value) {
            addCriterion("YWLCMC not like", value, "ywlcmc");
            return (Criteria) this;
        }

        public Criteria andYwlcmcIn(List<String> values) {
            addCriterion("YWLCMC in", values, "ywlcmc");
            return (Criteria) this;
        }

        public Criteria andYwlcmcNotIn(List<String> values) {
            addCriterion("YWLCMC not in", values, "ywlcmc");
            return (Criteria) this;
        }

        public Criteria andYwlcmcBetween(String value1, String value2) {
            addCriterion("YWLCMC between", value1, value2, "ywlcmc");
            return (Criteria) this;
        }

        public Criteria andYwlcmcNotBetween(String value1, String value2) {
            addCriterion("YWLCMC not between", value1, value2, "ywlcmc");
            return (Criteria) this;
        }

        public Criteria andYwlcmsIsNull() {
            addCriterion("YWLCMS is null");
            return (Criteria) this;
        }

        public Criteria andYwlcmsIsNotNull() {
            addCriterion("YWLCMS is not null");
            return (Criteria) this;
        }

        public Criteria andYwlcmsEqualTo(String value) {
            addCriterion("YWLCMS =", value, "ywlcms");
            return (Criteria) this;
        }

        public Criteria andYwlcmsNotEqualTo(String value) {
            addCriterion("YWLCMS <>", value, "ywlcms");
            return (Criteria) this;
        }

        public Criteria andYwlcmsGreaterThan(String value) {
            addCriterion("YWLCMS >", value, "ywlcms");
            return (Criteria) this;
        }

        public Criteria andYwlcmsGreaterThanOrEqualTo(String value) {
            addCriterion("YWLCMS >=", value, "ywlcms");
            return (Criteria) this;
        }

        public Criteria andYwlcmsLessThan(String value) {
            addCriterion("YWLCMS <", value, "ywlcms");
            return (Criteria) this;
        }

        public Criteria andYwlcmsLessThanOrEqualTo(String value) {
            addCriterion("YWLCMS <=", value, "ywlcms");
            return (Criteria) this;
        }

        public Criteria andYwlcmsLike(String value) {
            addCriterion("YWLCMS like", value, "ywlcms");
            return (Criteria) this;
        }

        public Criteria andYwlcmsNotLike(String value) {
            addCriterion("YWLCMS not like", value, "ywlcms");
            return (Criteria) this;
        }

        public Criteria andYwlcmsIn(List<String> values) {
            addCriterion("YWLCMS in", values, "ywlcms");
            return (Criteria) this;
        }

        public Criteria andYwlcmsNotIn(List<String> values) {
            addCriterion("YWLCMS not in", values, "ywlcms");
            return (Criteria) this;
        }

        public Criteria andYwlcmsBetween(String value1, String value2) {
            addCriterion("YWLCMS between", value1, value2, "ywlcms");
            return (Criteria) this;
        }

        public Criteria andYwlcmsNotBetween(String value1, String value2) {
            addCriterion("YWLCMS not between", value1, value2, "ywlcms");
            return (Criteria) this;
        }

        public Criteria andYwlcgfclIsNull() {
            addCriterion("YWLCGFCL is null");
            return (Criteria) this;
        }

        public Criteria andYwlcgfclIsNotNull() {
            addCriterion("YWLCGFCL is not null");
            return (Criteria) this;
        }

        public Criteria andYwlcgfclEqualTo(String value) {
            addCriterion("YWLCGFCL =", value, "ywlcgfcl");
            return (Criteria) this;
        }

        public Criteria andYwlcgfclNotEqualTo(String value) {
            addCriterion("YWLCGFCL <>", value, "ywlcgfcl");
            return (Criteria) this;
        }

        public Criteria andYwlcgfclGreaterThan(String value) {
            addCriterion("YWLCGFCL >", value, "ywlcgfcl");
            return (Criteria) this;
        }

        public Criteria andYwlcgfclGreaterThanOrEqualTo(String value) {
            addCriterion("YWLCGFCL >=", value, "ywlcgfcl");
            return (Criteria) this;
        }

        public Criteria andYwlcgfclLessThan(String value) {
            addCriterion("YWLCGFCL <", value, "ywlcgfcl");
            return (Criteria) this;
        }

        public Criteria andYwlcgfclLessThanOrEqualTo(String value) {
            addCriterion("YWLCGFCL <=", value, "ywlcgfcl");
            return (Criteria) this;
        }

        public Criteria andYwlcgfclLike(String value) {
            addCriterion("YWLCGFCL like", value, "ywlcgfcl");
            return (Criteria) this;
        }

        public Criteria andYwlcgfclNotLike(String value) {
            addCriterion("YWLCGFCL not like", value, "ywlcgfcl");
            return (Criteria) this;
        }

        public Criteria andYwlcgfclIn(List<String> values) {
            addCriterion("YWLCGFCL in", values, "ywlcgfcl");
            return (Criteria) this;
        }

        public Criteria andYwlcgfclNotIn(List<String> values) {
            addCriterion("YWLCGFCL not in", values, "ywlcgfcl");
            return (Criteria) this;
        }

        public Criteria andYwlcgfclBetween(String value1, String value2) {
            addCriterion("YWLCGFCL between", value1, value2, "ywlcgfcl");
            return (Criteria) this;
        }

        public Criteria andYwlcgfclNotBetween(String value1, String value2) {
            addCriterion("YWLCGFCL not between", value1, value2, "ywlcgfcl");
            return (Criteria) this;
        }

        public Criteria andLcjdmcIsNull() {
            addCriterion("LCJDMC is null");
            return (Criteria) this;
        }

        public Criteria andLcjdmcIsNotNull() {
            addCriterion("LCJDMC is not null");
            return (Criteria) this;
        }

        public Criteria andLcjdmcEqualTo(String value) {
            addCriterion("LCJDMC =", value, "lcjdmc");
            return (Criteria) this;
        }

        public Criteria andLcjdmcNotEqualTo(String value) {
            addCriterion("LCJDMC <>", value, "lcjdmc");
            return (Criteria) this;
        }

        public Criteria andLcjdmcGreaterThan(String value) {
            addCriterion("LCJDMC >", value, "lcjdmc");
            return (Criteria) this;
        }

        public Criteria andLcjdmcGreaterThanOrEqualTo(String value) {
            addCriterion("LCJDMC >=", value, "lcjdmc");
            return (Criteria) this;
        }

        public Criteria andLcjdmcLessThan(String value) {
            addCriterion("LCJDMC <", value, "lcjdmc");
            return (Criteria) this;
        }

        public Criteria andLcjdmcLessThanOrEqualTo(String value) {
            addCriterion("LCJDMC <=", value, "lcjdmc");
            return (Criteria) this;
        }

        public Criteria andLcjdmcLike(String value) {
            addCriterion("LCJDMC like", value, "lcjdmc");
            return (Criteria) this;
        }

        public Criteria andLcjdmcNotLike(String value) {
            addCriterion("LCJDMC not like", value, "lcjdmc");
            return (Criteria) this;
        }

        public Criteria andLcjdmcIn(List<String> values) {
            addCriterion("LCJDMC in", values, "lcjdmc");
            return (Criteria) this;
        }

        public Criteria andLcjdmcNotIn(List<String> values) {
            addCriterion("LCJDMC not in", values, "lcjdmc");
            return (Criteria) this;
        }

        public Criteria andLcjdmcBetween(String value1, String value2) {
            addCriterion("LCJDMC between", value1, value2, "lcjdmc");
            return (Criteria) this;
        }

        public Criteria andLcjdmcNotBetween(String value1, String value2) {
            addCriterion("LCJDMC not between", value1, value2, "lcjdmc");
            return (Criteria) this;
        }

        public Criteria andLcjdmsIsNull() {
            addCriterion("LCJDMS is null");
            return (Criteria) this;
        }

        public Criteria andLcjdmsIsNotNull() {
            addCriterion("LCJDMS is not null");
            return (Criteria) this;
        }

        public Criteria andLcjdmsEqualTo(String value) {
            addCriterion("LCJDMS =", value, "lcjdms");
            return (Criteria) this;
        }

        public Criteria andLcjdmsNotEqualTo(String value) {
            addCriterion("LCJDMS <>", value, "lcjdms");
            return (Criteria) this;
        }

        public Criteria andLcjdmsGreaterThan(String value) {
            addCriterion("LCJDMS >", value, "lcjdms");
            return (Criteria) this;
        }

        public Criteria andLcjdmsGreaterThanOrEqualTo(String value) {
            addCriterion("LCJDMS >=", value, "lcjdms");
            return (Criteria) this;
        }

        public Criteria andLcjdmsLessThan(String value) {
            addCriterion("LCJDMS <", value, "lcjdms");
            return (Criteria) this;
        }

        public Criteria andLcjdmsLessThanOrEqualTo(String value) {
            addCriterion("LCJDMS <=", value, "lcjdms");
            return (Criteria) this;
        }

        public Criteria andLcjdmsLike(String value) {
            addCriterion("LCJDMS like", value, "lcjdms");
            return (Criteria) this;
        }

        public Criteria andLcjdmsNotLike(String value) {
            addCriterion("LCJDMS not like", value, "lcjdms");
            return (Criteria) this;
        }

        public Criteria andLcjdmsIn(List<String> values) {
            addCriterion("LCJDMS in", values, "lcjdms");
            return (Criteria) this;
        }

        public Criteria andLcjdmsNotIn(List<String> values) {
            addCriterion("LCJDMS not in", values, "lcjdms");
            return (Criteria) this;
        }

        public Criteria andLcjdmsBetween(String value1, String value2) {
            addCriterion("LCJDMS between", value1, value2, "lcjdms");
            return (Criteria) this;
        }

        public Criteria andLcjdmsNotBetween(String value1, String value2) {
            addCriterion("LCJDMS not between", value1, value2, "lcjdms");
            return (Criteria) this;
        }

        public Criteria andLcjdgfclIsNull() {
            addCriterion("LCJDGFCL is null");
            return (Criteria) this;
        }

        public Criteria andLcjdgfclIsNotNull() {
            addCriterion("LCJDGFCL is not null");
            return (Criteria) this;
        }

        public Criteria andLcjdgfclEqualTo(String value) {
            addCriterion("LCJDGFCL =", value, "lcjdgfcl");
            return (Criteria) this;
        }

        public Criteria andLcjdgfclNotEqualTo(String value) {
            addCriterion("LCJDGFCL <>", value, "lcjdgfcl");
            return (Criteria) this;
        }

        public Criteria andLcjdgfclGreaterThan(String value) {
            addCriterion("LCJDGFCL >", value, "lcjdgfcl");
            return (Criteria) this;
        }

        public Criteria andLcjdgfclGreaterThanOrEqualTo(String value) {
            addCriterion("LCJDGFCL >=", value, "lcjdgfcl");
            return (Criteria) this;
        }

        public Criteria andLcjdgfclLessThan(String value) {
            addCriterion("LCJDGFCL <", value, "lcjdgfcl");
            return (Criteria) this;
        }

        public Criteria andLcjdgfclLessThanOrEqualTo(String value) {
            addCriterion("LCJDGFCL <=", value, "lcjdgfcl");
            return (Criteria) this;
        }

        public Criteria andLcjdgfclLike(String value) {
            addCriterion("LCJDGFCL like", value, "lcjdgfcl");
            return (Criteria) this;
        }

        public Criteria andLcjdgfclNotLike(String value) {
            addCriterion("LCJDGFCL not like", value, "lcjdgfcl");
            return (Criteria) this;
        }

        public Criteria andLcjdgfclIn(List<String> values) {
            addCriterion("LCJDGFCL in", values, "lcjdgfcl");
            return (Criteria) this;
        }

        public Criteria andLcjdgfclNotIn(List<String> values) {
            addCriterion("LCJDGFCL not in", values, "lcjdgfcl");
            return (Criteria) this;
        }

        public Criteria andLcjdgfclBetween(String value1, String value2) {
            addCriterion("LCJDGFCL between", value1, value2, "lcjdgfcl");
            return (Criteria) this;
        }

        public Criteria andLcjdgfclNotBetween(String value1, String value2) {
            addCriterion("LCJDGFCL not between", value1, value2, "lcjdgfcl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NWIDP.IMP_XQD_YWYXX
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NWIDP.IMP_XQD_YWYXX
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}