package com.yfny.corepojo.entity.demandform.model;

public class Yyyxx {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_YYYXX.YYYBS
     *
     * @mbggenerated
     */
    private String yyybs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_YYYXX.XQDH
     *
     * @mbggenerated
     */
    private String xqdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_YYYXX.YYY
     *
     * @mbggenerated
     */
    private String yyy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_YYYXX.YY
     *
     * @mbggenerated
     */
    private String yy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_YYYXX.YYMKMC
     *
     * @mbggenerated
     */
    private String yymkmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_YYYXX.YYMKMS
     *
     * @mbggenerated
     */
    private String yymkms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_YYYXX.YYGNMC
     *
     * @mbggenerated
     */
    private String yygnmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_YYYXX.YYGDMS
     *
     * @mbggenerated
     */
    private String yygdms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_YYYXX.FGNXQ
     *
     * @mbggenerated
     */
    private String fgnxq;

    public Yyyxx(String yyybs, String xqdh, String yyy, String yy, String yymkmc, String yymkms, String yygnmc, String yygdms, String fgnxq) {
        this.yyybs = yyybs;
        this.xqdh = xqdh;
        this.yyy = yyy;
        this.yy = yy;
        this.yymkmc = yymkmc;
        this.yymkms = yymkms;
        this.yygnmc = yygnmc;
        this.yygdms = yygdms;
        this.fgnxq = fgnxq;
    }

    public Yyyxx() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_YYYXX.YYYBS
     *
     * @return the value of NWIDP.IMP_XQD_YYYXX.YYYBS
     *
     * @mbggenerated
     */
    public String getYyybs() {
        return yyybs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_YYYXX.YYYBS
     *
     * @param yyybs the value for NWIDP.IMP_XQD_YYYXX.YYYBS
     *
     * @mbggenerated
     */
    public void setYyybs(String yyybs) {
        this.yyybs = yyybs == null ? null : yyybs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_YYYXX.XQDH
     *
     * @return the value of NWIDP.IMP_XQD_YYYXX.XQDH
     *
     * @mbggenerated
     */
    public String getXqdh() {
        return xqdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_YYYXX.XQDH
     *
     * @param xqdh the value for NWIDP.IMP_XQD_YYYXX.XQDH
     *
     * @mbggenerated
     */
    public void setXqdh(String xqdh) {
        this.xqdh = xqdh == null ? null : xqdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_YYYXX.YYY
     *
     * @return the value of NWIDP.IMP_XQD_YYYXX.YYY
     *
     * @mbggenerated
     */
    public String getYyy() {
        return yyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_YYYXX.YYY
     *
     * @param yyy the value for NWIDP.IMP_XQD_YYYXX.YYY
     *
     * @mbggenerated
     */
    public void setYyy(String yyy) {
        this.yyy = yyy == null ? null : yyy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_YYYXX.YY
     *
     * @return the value of NWIDP.IMP_XQD_YYYXX.YY
     *
     * @mbggenerated
     */
    public String getYy() {
        return yy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_YYYXX.YY
     *
     * @param yy the value for NWIDP.IMP_XQD_YYYXX.YY
     *
     * @mbggenerated
     */
    public void setYy(String yy) {
        this.yy = yy == null ? null : yy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_YYYXX.YYMKMC
     *
     * @return the value of NWIDP.IMP_XQD_YYYXX.YYMKMC
     *
     * @mbggenerated
     */
    public String getYymkmc() {
        return yymkmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_YYYXX.YYMKMC
     *
     * @param yymkmc the value for NWIDP.IMP_XQD_YYYXX.YYMKMC
     *
     * @mbggenerated
     */
    public void setYymkmc(String yymkmc) {
        this.yymkmc = yymkmc == null ? null : yymkmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_YYYXX.YYMKMS
     *
     * @return the value of NWIDP.IMP_XQD_YYYXX.YYMKMS
     *
     * @mbggenerated
     */
    public String getYymkms() {
        return yymkms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_YYYXX.YYMKMS
     *
     * @param yymkms the value for NWIDP.IMP_XQD_YYYXX.YYMKMS
     *
     * @mbggenerated
     */
    public void setYymkms(String yymkms) {
        this.yymkms = yymkms == null ? null : yymkms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_YYYXX.YYGNMC
     *
     * @return the value of NWIDP.IMP_XQD_YYYXX.YYGNMC
     *
     * @mbggenerated
     */
    public String getYygnmc() {
        return yygnmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_YYYXX.YYGNMC
     *
     * @param yygnmc the value for NWIDP.IMP_XQD_YYYXX.YYGNMC
     *
     * @mbggenerated
     */
    public void setYygnmc(String yygnmc) {
        this.yygnmc = yygnmc == null ? null : yygnmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_YYYXX.YYGDMS
     *
     * @return the value of NWIDP.IMP_XQD_YYYXX.YYGDMS
     *
     * @mbggenerated
     */
    public String getYygdms() {
        return yygdms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_YYYXX.YYGDMS
     *
     * @param yygdms the value for NWIDP.IMP_XQD_YYYXX.YYGDMS
     *
     * @mbggenerated
     */
    public void setYygdms(String yygdms) {
        this.yygdms = yygdms == null ? null : yygdms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_YYYXX.FGNXQ
     *
     * @return the value of NWIDP.IMP_XQD_YYYXX.FGNXQ
     *
     * @mbggenerated
     */
    public String getFgnxq() {
        return fgnxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_YYYXX.FGNXQ
     *
     * @param fgnxq the value for NWIDP.IMP_XQD_YYYXX.FGNXQ
     *
     * @mbggenerated
     */
    public void setFgnxq(String fgnxq) {
        this.fgnxq = fgnxq == null ? null : fgnxq.trim();
    }
}