package com.yfny.corepojo.entity.demandform.model;

import java.util.ArrayList;
import java.util.List;

public class YyyxxExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NWIDP.IMP_XQD_YYYXX
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NWIDP.IMP_XQD_YYYXX
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NWIDP.IMP_XQD_YYYXX
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_YYYXX
     *
     * @mbggenerated
     */
    public YyyxxExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_YYYXX
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_YYYXX
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_YYYXX
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_YYYXX
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_YYYXX
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_YYYXX
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_YYYXX
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_YYYXX
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_YYYXX
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_YYYXX
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NWIDP.IMP_XQD_YYYXX
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andYyybsIsNull() {
            addCriterion("YYYBS is null");
            return (Criteria) this;
        }

        public Criteria andYyybsIsNotNull() {
            addCriterion("YYYBS is not null");
            return (Criteria) this;
        }

        public Criteria andYyybsEqualTo(String value) {
            addCriterion("YYYBS =", value, "yyybs");
            return (Criteria) this;
        }

        public Criteria andYyybsNotEqualTo(String value) {
            addCriterion("YYYBS <>", value, "yyybs");
            return (Criteria) this;
        }

        public Criteria andYyybsGreaterThan(String value) {
            addCriterion("YYYBS >", value, "yyybs");
            return (Criteria) this;
        }

        public Criteria andYyybsGreaterThanOrEqualTo(String value) {
            addCriterion("YYYBS >=", value, "yyybs");
            return (Criteria) this;
        }

        public Criteria andYyybsLessThan(String value) {
            addCriterion("YYYBS <", value, "yyybs");
            return (Criteria) this;
        }

        public Criteria andYyybsLessThanOrEqualTo(String value) {
            addCriterion("YYYBS <=", value, "yyybs");
            return (Criteria) this;
        }

        public Criteria andYyybsLike(String value) {
            addCriterion("YYYBS like", value, "yyybs");
            return (Criteria) this;
        }

        public Criteria andYyybsNotLike(String value) {
            addCriterion("YYYBS not like", value, "yyybs");
            return (Criteria) this;
        }

        public Criteria andYyybsIn(List<String> values) {
            addCriterion("YYYBS in", values, "yyybs");
            return (Criteria) this;
        }

        public Criteria andYyybsNotIn(List<String> values) {
            addCriterion("YYYBS not in", values, "yyybs");
            return (Criteria) this;
        }

        public Criteria andYyybsBetween(String value1, String value2) {
            addCriterion("YYYBS between", value1, value2, "yyybs");
            return (Criteria) this;
        }

        public Criteria andYyybsNotBetween(String value1, String value2) {
            addCriterion("YYYBS not between", value1, value2, "yyybs");
            return (Criteria) this;
        }

        public Criteria andXqdhIsNull() {
            addCriterion("XQDH is null");
            return (Criteria) this;
        }

        public Criteria andXqdhIsNotNull() {
            addCriterion("XQDH is not null");
            return (Criteria) this;
        }

        public Criteria andXqdhEqualTo(String value) {
            addCriterion("XQDH =", value, "xqdh");
            return (Criteria) this;
        }

        public Criteria andXqdhNotEqualTo(String value) {
            addCriterion("XQDH <>", value, "xqdh");
            return (Criteria) this;
        }

        public Criteria andXqdhGreaterThan(String value) {
            addCriterion("XQDH >", value, "xqdh");
            return (Criteria) this;
        }

        public Criteria andXqdhGreaterThanOrEqualTo(String value) {
            addCriterion("XQDH >=", value, "xqdh");
            return (Criteria) this;
        }

        public Criteria andXqdhLessThan(String value) {
            addCriterion("XQDH <", value, "xqdh");
            return (Criteria) this;
        }

        public Criteria andXqdhLessThanOrEqualTo(String value) {
            addCriterion("XQDH <=", value, "xqdh");
            return (Criteria) this;
        }

        public Criteria andXqdhLike(String value) {
            addCriterion("XQDH like", value, "xqdh");
            return (Criteria) this;
        }

        public Criteria andXqdhNotLike(String value) {
            addCriterion("XQDH not like", value, "xqdh");
            return (Criteria) this;
        }

        public Criteria andXqdhIn(List<String> values) {
            addCriterion("XQDH in", values, "xqdh");
            return (Criteria) this;
        }

        public Criteria andXqdhNotIn(List<String> values) {
            addCriterion("XQDH not in", values, "xqdh");
            return (Criteria) this;
        }

        public Criteria andXqdhBetween(String value1, String value2) {
            addCriterion("XQDH between", value1, value2, "xqdh");
            return (Criteria) this;
        }

        public Criteria andXqdhNotBetween(String value1, String value2) {
            addCriterion("XQDH not between", value1, value2, "xqdh");
            return (Criteria) this;
        }

        public Criteria andYyyIsNull() {
            addCriterion("YYY is null");
            return (Criteria) this;
        }

        public Criteria andYyyIsNotNull() {
            addCriterion("YYY is not null");
            return (Criteria) this;
        }

        public Criteria andYyyEqualTo(String value) {
            addCriterion("YYY =", value, "yyy");
            return (Criteria) this;
        }

        public Criteria andYyyNotEqualTo(String value) {
            addCriterion("YYY <>", value, "yyy");
            return (Criteria) this;
        }

        public Criteria andYyyGreaterThan(String value) {
            addCriterion("YYY >", value, "yyy");
            return (Criteria) this;
        }

        public Criteria andYyyGreaterThanOrEqualTo(String value) {
            addCriterion("YYY >=", value, "yyy");
            return (Criteria) this;
        }

        public Criteria andYyyLessThan(String value) {
            addCriterion("YYY <", value, "yyy");
            return (Criteria) this;
        }

        public Criteria andYyyLessThanOrEqualTo(String value) {
            addCriterion("YYY <=", value, "yyy");
            return (Criteria) this;
        }

        public Criteria andYyyLike(String value) {
            addCriterion("YYY like", value, "yyy");
            return (Criteria) this;
        }

        public Criteria andYyyNotLike(String value) {
            addCriterion("YYY not like", value, "yyy");
            return (Criteria) this;
        }

        public Criteria andYyyIn(List<String> values) {
            addCriterion("YYY in", values, "yyy");
            return (Criteria) this;
        }

        public Criteria andYyyNotIn(List<String> values) {
            addCriterion("YYY not in", values, "yyy");
            return (Criteria) this;
        }

        public Criteria andYyyBetween(String value1, String value2) {
            addCriterion("YYY between", value1, value2, "yyy");
            return (Criteria) this;
        }

        public Criteria andYyyNotBetween(String value1, String value2) {
            addCriterion("YYY not between", value1, value2, "yyy");
            return (Criteria) this;
        }

        public Criteria andYyIsNull() {
            addCriterion("YY is null");
            return (Criteria) this;
        }

        public Criteria andYyIsNotNull() {
            addCriterion("YY is not null");
            return (Criteria) this;
        }

        public Criteria andYyEqualTo(String value) {
            addCriterion("YY =", value, "yy");
            return (Criteria) this;
        }

        public Criteria andYyNotEqualTo(String value) {
            addCriterion("YY <>", value, "yy");
            return (Criteria) this;
        }

        public Criteria andYyGreaterThan(String value) {
            addCriterion("YY >", value, "yy");
            return (Criteria) this;
        }

        public Criteria andYyGreaterThanOrEqualTo(String value) {
            addCriterion("YY >=", value, "yy");
            return (Criteria) this;
        }

        public Criteria andYyLessThan(String value) {
            addCriterion("YY <", value, "yy");
            return (Criteria) this;
        }

        public Criteria andYyLessThanOrEqualTo(String value) {
            addCriterion("YY <=", value, "yy");
            return (Criteria) this;
        }

        public Criteria andYyLike(String value) {
            addCriterion("YY like", value, "yy");
            return (Criteria) this;
        }

        public Criteria andYyNotLike(String value) {
            addCriterion("YY not like", value, "yy");
            return (Criteria) this;
        }

        public Criteria andYyIn(List<String> values) {
            addCriterion("YY in", values, "yy");
            return (Criteria) this;
        }

        public Criteria andYyNotIn(List<String> values) {
            addCriterion("YY not in", values, "yy");
            return (Criteria) this;
        }

        public Criteria andYyBetween(String value1, String value2) {
            addCriterion("YY between", value1, value2, "yy");
            return (Criteria) this;
        }

        public Criteria andYyNotBetween(String value1, String value2) {
            addCriterion("YY not between", value1, value2, "yy");
            return (Criteria) this;
        }

        public Criteria andYymkmcIsNull() {
            addCriterion("YYMKMC is null");
            return (Criteria) this;
        }

        public Criteria andYymkmcIsNotNull() {
            addCriterion("YYMKMC is not null");
            return (Criteria) this;
        }

        public Criteria andYymkmcEqualTo(String value) {
            addCriterion("YYMKMC =", value, "yymkmc");
            return (Criteria) this;
        }

        public Criteria andYymkmcNotEqualTo(String value) {
            addCriterion("YYMKMC <>", value, "yymkmc");
            return (Criteria) this;
        }

        public Criteria andYymkmcGreaterThan(String value) {
            addCriterion("YYMKMC >", value, "yymkmc");
            return (Criteria) this;
        }

        public Criteria andYymkmcGreaterThanOrEqualTo(String value) {
            addCriterion("YYMKMC >=", value, "yymkmc");
            return (Criteria) this;
        }

        public Criteria andYymkmcLessThan(String value) {
            addCriterion("YYMKMC <", value, "yymkmc");
            return (Criteria) this;
        }

        public Criteria andYymkmcLessThanOrEqualTo(String value) {
            addCriterion("YYMKMC <=", value, "yymkmc");
            return (Criteria) this;
        }

        public Criteria andYymkmcLike(String value) {
            addCriterion("YYMKMC like", value, "yymkmc");
            return (Criteria) this;
        }

        public Criteria andYymkmcNotLike(String value) {
            addCriterion("YYMKMC not like", value, "yymkmc");
            return (Criteria) this;
        }

        public Criteria andYymkmcIn(List<String> values) {
            addCriterion("YYMKMC in", values, "yymkmc");
            return (Criteria) this;
        }

        public Criteria andYymkmcNotIn(List<String> values) {
            addCriterion("YYMKMC not in", values, "yymkmc");
            return (Criteria) this;
        }

        public Criteria andYymkmcBetween(String value1, String value2) {
            addCriterion("YYMKMC between", value1, value2, "yymkmc");
            return (Criteria) this;
        }

        public Criteria andYymkmcNotBetween(String value1, String value2) {
            addCriterion("YYMKMC not between", value1, value2, "yymkmc");
            return (Criteria) this;
        }

        public Criteria andYymkmsIsNull() {
            addCriterion("YYMKMS is null");
            return (Criteria) this;
        }

        public Criteria andYymkmsIsNotNull() {
            addCriterion("YYMKMS is not null");
            return (Criteria) this;
        }

        public Criteria andYymkmsEqualTo(String value) {
            addCriterion("YYMKMS =", value, "yymkms");
            return (Criteria) this;
        }

        public Criteria andYymkmsNotEqualTo(String value) {
            addCriterion("YYMKMS <>", value, "yymkms");
            return (Criteria) this;
        }

        public Criteria andYymkmsGreaterThan(String value) {
            addCriterion("YYMKMS >", value, "yymkms");
            return (Criteria) this;
        }

        public Criteria andYymkmsGreaterThanOrEqualTo(String value) {
            addCriterion("YYMKMS >=", value, "yymkms");
            return (Criteria) this;
        }

        public Criteria andYymkmsLessThan(String value) {
            addCriterion("YYMKMS <", value, "yymkms");
            return (Criteria) this;
        }

        public Criteria andYymkmsLessThanOrEqualTo(String value) {
            addCriterion("YYMKMS <=", value, "yymkms");
            return (Criteria) this;
        }

        public Criteria andYymkmsLike(String value) {
            addCriterion("YYMKMS like", value, "yymkms");
            return (Criteria) this;
        }

        public Criteria andYymkmsNotLike(String value) {
            addCriterion("YYMKMS not like", value, "yymkms");
            return (Criteria) this;
        }

        public Criteria andYymkmsIn(List<String> values) {
            addCriterion("YYMKMS in", values, "yymkms");
            return (Criteria) this;
        }

        public Criteria andYymkmsNotIn(List<String> values) {
            addCriterion("YYMKMS not in", values, "yymkms");
            return (Criteria) this;
        }

        public Criteria andYymkmsBetween(String value1, String value2) {
            addCriterion("YYMKMS between", value1, value2, "yymkms");
            return (Criteria) this;
        }

        public Criteria andYymkmsNotBetween(String value1, String value2) {
            addCriterion("YYMKMS not between", value1, value2, "yymkms");
            return (Criteria) this;
        }

        public Criteria andYygnmcIsNull() {
            addCriterion("YYGNMC is null");
            return (Criteria) this;
        }

        public Criteria andYygnmcIsNotNull() {
            addCriterion("YYGNMC is not null");
            return (Criteria) this;
        }

        public Criteria andYygnmcEqualTo(String value) {
            addCriterion("YYGNMC =", value, "yygnmc");
            return (Criteria) this;
        }

        public Criteria andYygnmcNotEqualTo(String value) {
            addCriterion("YYGNMC <>", value, "yygnmc");
            return (Criteria) this;
        }

        public Criteria andYygnmcGreaterThan(String value) {
            addCriterion("YYGNMC >", value, "yygnmc");
            return (Criteria) this;
        }

        public Criteria andYygnmcGreaterThanOrEqualTo(String value) {
            addCriterion("YYGNMC >=", value, "yygnmc");
            return (Criteria) this;
        }

        public Criteria andYygnmcLessThan(String value) {
            addCriterion("YYGNMC <", value, "yygnmc");
            return (Criteria) this;
        }

        public Criteria andYygnmcLessThanOrEqualTo(String value) {
            addCriterion("YYGNMC <=", value, "yygnmc");
            return (Criteria) this;
        }

        public Criteria andYygnmcLike(String value) {
            addCriterion("YYGNMC like", value, "yygnmc");
            return (Criteria) this;
        }

        public Criteria andYygnmcNotLike(String value) {
            addCriterion("YYGNMC not like", value, "yygnmc");
            return (Criteria) this;
        }

        public Criteria andYygnmcIn(List<String> values) {
            addCriterion("YYGNMC in", values, "yygnmc");
            return (Criteria) this;
        }

        public Criteria andYygnmcNotIn(List<String> values) {
            addCriterion("YYGNMC not in", values, "yygnmc");
            return (Criteria) this;
        }

        public Criteria andYygnmcBetween(String value1, String value2) {
            addCriterion("YYGNMC between", value1, value2, "yygnmc");
            return (Criteria) this;
        }

        public Criteria andYygnmcNotBetween(String value1, String value2) {
            addCriterion("YYGNMC not between", value1, value2, "yygnmc");
            return (Criteria) this;
        }

        public Criteria andYygdmsIsNull() {
            addCriterion("YYGDMS is null");
            return (Criteria) this;
        }

        public Criteria andYygdmsIsNotNull() {
            addCriterion("YYGDMS is not null");
            return (Criteria) this;
        }

        public Criteria andYygdmsEqualTo(String value) {
            addCriterion("YYGDMS =", value, "yygdms");
            return (Criteria) this;
        }

        public Criteria andYygdmsNotEqualTo(String value) {
            addCriterion("YYGDMS <>", value, "yygdms");
            return (Criteria) this;
        }

        public Criteria andYygdmsGreaterThan(String value) {
            addCriterion("YYGDMS >", value, "yygdms");
            return (Criteria) this;
        }

        public Criteria andYygdmsGreaterThanOrEqualTo(String value) {
            addCriterion("YYGDMS >=", value, "yygdms");
            return (Criteria) this;
        }

        public Criteria andYygdmsLessThan(String value) {
            addCriterion("YYGDMS <", value, "yygdms");
            return (Criteria) this;
        }

        public Criteria andYygdmsLessThanOrEqualTo(String value) {
            addCriterion("YYGDMS <=", value, "yygdms");
            return (Criteria) this;
        }

        public Criteria andYygdmsLike(String value) {
            addCriterion("YYGDMS like", value, "yygdms");
            return (Criteria) this;
        }

        public Criteria andYygdmsNotLike(String value) {
            addCriterion("YYGDMS not like", value, "yygdms");
            return (Criteria) this;
        }

        public Criteria andYygdmsIn(List<String> values) {
            addCriterion("YYGDMS in", values, "yygdms");
            return (Criteria) this;
        }

        public Criteria andYygdmsNotIn(List<String> values) {
            addCriterion("YYGDMS not in", values, "yygdms");
            return (Criteria) this;
        }

        public Criteria andYygdmsBetween(String value1, String value2) {
            addCriterion("YYGDMS between", value1, value2, "yygdms");
            return (Criteria) this;
        }

        public Criteria andYygdmsNotBetween(String value1, String value2) {
            addCriterion("YYGDMS not between", value1, value2, "yygdms");
            return (Criteria) this;
        }

        public Criteria andFgnxqIsNull() {
            addCriterion("FGNXQ is null");
            return (Criteria) this;
        }

        public Criteria andFgnxqIsNotNull() {
            addCriterion("FGNXQ is not null");
            return (Criteria) this;
        }

        public Criteria andFgnxqEqualTo(String value) {
            addCriterion("FGNXQ =", value, "fgnxq");
            return (Criteria) this;
        }

        public Criteria andFgnxqNotEqualTo(String value) {
            addCriterion("FGNXQ <>", value, "fgnxq");
            return (Criteria) this;
        }

        public Criteria andFgnxqGreaterThan(String value) {
            addCriterion("FGNXQ >", value, "fgnxq");
            return (Criteria) this;
        }

        public Criteria andFgnxqGreaterThanOrEqualTo(String value) {
            addCriterion("FGNXQ >=", value, "fgnxq");
            return (Criteria) this;
        }

        public Criteria andFgnxqLessThan(String value) {
            addCriterion("FGNXQ <", value, "fgnxq");
            return (Criteria) this;
        }

        public Criteria andFgnxqLessThanOrEqualTo(String value) {
            addCriterion("FGNXQ <=", value, "fgnxq");
            return (Criteria) this;
        }

        public Criteria andFgnxqLike(String value) {
            addCriterion("FGNXQ like", value, "fgnxq");
            return (Criteria) this;
        }

        public Criteria andFgnxqNotLike(String value) {
            addCriterion("FGNXQ not like", value, "fgnxq");
            return (Criteria) this;
        }

        public Criteria andFgnxqIn(List<String> values) {
            addCriterion("FGNXQ in", values, "fgnxq");
            return (Criteria) this;
        }

        public Criteria andFgnxqNotIn(List<String> values) {
            addCriterion("FGNXQ not in", values, "fgnxq");
            return (Criteria) this;
        }

        public Criteria andFgnxqBetween(String value1, String value2) {
            addCriterion("FGNXQ between", value1, value2, "fgnxq");
            return (Criteria) this;
        }

        public Criteria andFgnxqNotBetween(String value1, String value2) {
            addCriterion("FGNXQ not between", value1, value2, "fgnxq");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NWIDP.IMP_XQD_YYYXX
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NWIDP.IMP_XQD_YYYXX
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}