package com.yfny.corepojo.entity.demandform.model;

public class Zfdm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_ZFDM.DMBM
     *
     * @mbggenerated
     */
    private String dmbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_ZFDM.DMZL
     *
     * @mbggenerated
     */
    private String dmzl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NWIDP.IMP_XQD_ZFDM.DMMC
     *
     * @mbggenerated
     */
    private String dmmc;

    public Zfdm(String dmbm, String dmzl, String dmmc) {
        this.dmbm = dmbm;
        this.dmzl = dmzl;
        this.dmmc = dmmc;
    }

    public Zfdm() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_ZFDM.DMBM
     *
     * @return the value of NWIDP.IMP_XQD_ZFDM.DMBM
     *
     * @mbggenerated
     */
    public String getDmbm() {
        return dmbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_ZFDM.DMBM
     *
     * @param dmbm the value for NWIDP.IMP_XQD_ZFDM.DMBM
     *
     * @mbggenerated
     */
    public void setDmbm(String dmbm) {
        this.dmbm = dmbm == null ? null : dmbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_ZFDM.DMZL
     *
     * @return the value of NWIDP.IMP_XQD_ZFDM.DMZL
     *
     * @mbggenerated
     */
    public String getDmzl() {
        return dmzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_ZFDM.DMZL
     *
     * @param dmzl the value for NWIDP.IMP_XQD_ZFDM.DMZL
     *
     * @mbggenerated
     */
    public void setDmzl(String dmzl) {
        this.dmzl = dmzl == null ? null : dmzl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NWIDP.IMP_XQD_ZFDM.DMMC
     *
     * @return the value of NWIDP.IMP_XQD_ZFDM.DMMC
     *
     * @mbggenerated
     */
    public String getDmmc() {
        return dmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NWIDP.IMP_XQD_ZFDM.DMMC
     *
     * @param dmmc the value for NWIDP.IMP_XQD_ZFDM.DMMC
     *
     * @mbggenerated
     */
    public void setDmmc(String dmmc) {
        this.dmmc = dmmc == null ? null : dmmc.trim();
    }
}