package com.yfny.corepojo.entity.demandform.model;

import java.util.ArrayList;
import java.util.List;

public class ZfdmExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NWIDP.IMP_XQD_ZFDM
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NWIDP.IMP_XQD_ZFDM
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table NWIDP.IMP_XQD_ZFDM
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_ZFDM
     *
     * @mbggenerated
     */
    public ZfdmExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_ZFDM
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_ZFDM
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_ZFDM
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_ZFDM
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_ZFDM
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_ZFDM
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_ZFDM
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_ZFDM
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_ZFDM
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NWIDP.IMP_XQD_ZFDM
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NWIDP.IMP_XQD_ZFDM
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDmbmIsNull() {
            addCriterion("DMBM is null");
            return (Criteria) this;
        }

        public Criteria andDmbmIsNotNull() {
            addCriterion("DMBM is not null");
            return (Criteria) this;
        }

        public Criteria andDmbmEqualTo(String value) {
            addCriterion("DMBM =", value, "dmbm");
            return (Criteria) this;
        }

        public Criteria andDmbmNotEqualTo(String value) {
            addCriterion("DMBM <>", value, "dmbm");
            return (Criteria) this;
        }

        public Criteria andDmbmGreaterThan(String value) {
            addCriterion("DMBM >", value, "dmbm");
            return (Criteria) this;
        }

        public Criteria andDmbmGreaterThanOrEqualTo(String value) {
            addCriterion("DMBM >=", value, "dmbm");
            return (Criteria) this;
        }

        public Criteria andDmbmLessThan(String value) {
            addCriterion("DMBM <", value, "dmbm");
            return (Criteria) this;
        }

        public Criteria andDmbmLessThanOrEqualTo(String value) {
            addCriterion("DMBM <=", value, "dmbm");
            return (Criteria) this;
        }

        public Criteria andDmbmLike(String value) {
            addCriterion("DMBM like", value, "dmbm");
            return (Criteria) this;
        }

        public Criteria andDmbmNotLike(String value) {
            addCriterion("DMBM not like", value, "dmbm");
            return (Criteria) this;
        }

        public Criteria andDmbmIn(List<String> values) {
            addCriterion("DMBM in", values, "dmbm");
            return (Criteria) this;
        }

        public Criteria andDmbmNotIn(List<String> values) {
            addCriterion("DMBM not in", values, "dmbm");
            return (Criteria) this;
        }

        public Criteria andDmbmBetween(String value1, String value2) {
            addCriterion("DMBM between", value1, value2, "dmbm");
            return (Criteria) this;
        }

        public Criteria andDmbmNotBetween(String value1, String value2) {
            addCriterion("DMBM not between", value1, value2, "dmbm");
            return (Criteria) this;
        }

        public Criteria andDmzlIsNull() {
            addCriterion("DMZL is null");
            return (Criteria) this;
        }

        public Criteria andDmzlIsNotNull() {
            addCriterion("DMZL is not null");
            return (Criteria) this;
        }

        public Criteria andDmzlEqualTo(String value) {
            addCriterion("DMZL =", value, "dmzl");
            return (Criteria) this;
        }

        public Criteria andDmzlNotEqualTo(String value) {
            addCriterion("DMZL <>", value, "dmzl");
            return (Criteria) this;
        }

        public Criteria andDmzlGreaterThan(String value) {
            addCriterion("DMZL >", value, "dmzl");
            return (Criteria) this;
        }

        public Criteria andDmzlGreaterThanOrEqualTo(String value) {
            addCriterion("DMZL >=", value, "dmzl");
            return (Criteria) this;
        }

        public Criteria andDmzlLessThan(String value) {
            addCriterion("DMZL <", value, "dmzl");
            return (Criteria) this;
        }

        public Criteria andDmzlLessThanOrEqualTo(String value) {
            addCriterion("DMZL <=", value, "dmzl");
            return (Criteria) this;
        }

        public Criteria andDmzlLike(String value) {
            addCriterion("DMZL like", value, "dmzl");
            return (Criteria) this;
        }

        public Criteria andDmzlNotLike(String value) {
            addCriterion("DMZL not like", value, "dmzl");
            return (Criteria) this;
        }

        public Criteria andDmzlIn(List<String> values) {
            addCriterion("DMZL in", values, "dmzl");
            return (Criteria) this;
        }

        public Criteria andDmzlNotIn(List<String> values) {
            addCriterion("DMZL not in", values, "dmzl");
            return (Criteria) this;
        }

        public Criteria andDmzlBetween(String value1, String value2) {
            addCriterion("DMZL between", value1, value2, "dmzl");
            return (Criteria) this;
        }

        public Criteria andDmzlNotBetween(String value1, String value2) {
            addCriterion("DMZL not between", value1, value2, "dmzl");
            return (Criteria) this;
        }

        public Criteria andDmmcIsNull() {
            addCriterion("DMMC is null");
            return (Criteria) this;
        }

        public Criteria andDmmcIsNotNull() {
            addCriterion("DMMC is not null");
            return (Criteria) this;
        }

        public Criteria andDmmcEqualTo(String value) {
            addCriterion("DMMC =", value, "dmmc");
            return (Criteria) this;
        }

        public Criteria andDmmcNotEqualTo(String value) {
            addCriterion("DMMC <>", value, "dmmc");
            return (Criteria) this;
        }

        public Criteria andDmmcGreaterThan(String value) {
            addCriterion("DMMC >", value, "dmmc");
            return (Criteria) this;
        }

        public Criteria andDmmcGreaterThanOrEqualTo(String value) {
            addCriterion("DMMC >=", value, "dmmc");
            return (Criteria) this;
        }

        public Criteria andDmmcLessThan(String value) {
            addCriterion("DMMC <", value, "dmmc");
            return (Criteria) this;
        }

        public Criteria andDmmcLessThanOrEqualTo(String value) {
            addCriterion("DMMC <=", value, "dmmc");
            return (Criteria) this;
        }

        public Criteria andDmmcLike(String value) {
            addCriterion("DMMC like", value, "dmmc");
            return (Criteria) this;
        }

        public Criteria andDmmcNotLike(String value) {
            addCriterion("DMMC not like", value, "dmmc");
            return (Criteria) this;
        }

        public Criteria andDmmcIn(List<String> values) {
            addCriterion("DMMC in", values, "dmmc");
            return (Criteria) this;
        }

        public Criteria andDmmcNotIn(List<String> values) {
            addCriterion("DMMC not in", values, "dmmc");
            return (Criteria) this;
        }

        public Criteria andDmmcBetween(String value1, String value2) {
            addCriterion("DMMC between", value1, value2, "dmmc");
            return (Criteria) this;
        }

        public Criteria andDmmcNotBetween(String value1, String value2) {
            addCriterion("DMMC not between", value1, value2, "dmmc");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NWIDP.IMP_XQD_ZFDM
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table NWIDP.IMP_XQD_ZFDM
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}